### PR TITLE
Fix palette generation bugs in saveGif()

### PR DESCRIPTION
**Pull request by davepagurek**
There are a few palette-related changes in here:

### 1. The palette for gifs was based only on the first frame
Resolves https://github.com/processing/p5.js/issues/5881

When building the list of colors to quantize into a palette, we accidentally were adding the first frame over and over instead of all the frames of the gif. It now sends all the frames' colors into quantization. I didn't notice this when looking at the original PR, oops!

Input sketch: https://editor.p5js.org/davepagurek/sketches/wZWa8l9jh
<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td>

</td>
<td>

</td>
</tr>
</table>

### 2. Some elements left trails in gifs
Resolves https://github.com/processing/p5.js/issues/5882

To determine what frames are unchanged between frames of gifs, we were comparing colors in the original frames. Unfortunately, the same colors in the input frames don't necessarily map to the same output frame color depending on the ordering of colors in the frames, which I'll go into a bit later. If we instead apply the gif palette first, and then check for a difference in the palette colors, we don't see any more trails. Unfortunately, this reveals some flickering caused by that nondeterminism I mentioned:

Input sketch: https://editor.p5js.org/davepagurek/sketches/ANZ-YhpXA
<table>
<tr><th>Before</th><th>Broken in a different way 🥲</th></tr>
<tr>
<td>

</td>
<td>

</td>
</tr>
</table>

The `applyPalette` method from the gif encoding library we use, for the sake of speed, caches the palette color so it doesn't have to check again when it encounters the same color. However, the cache key is not the original color, but instead a bit-reduced version of the color (presumably also for speed/memory.) Unfortunately, this means that multiple input colors get put into the same cache key, and not all of those input colors necessarily correspond to the same palette color.

To avoid this issue, I've stopped using `applyPalette` from the library, and wrote a new version. It's mostly based on the library's code, but:
- it caches colors based on the original input to avoid the flickering issue
- it also uses the same cache for all frames rather than resetting it each frame, hopefully yielding better performance for sketches that share a lot of colors between frames

Now, finally, the output looks more expected! I've kept the change I made to compare the gif palette colors rather than the source colors because, even though the original method should still work with the fixed palette application, comparing the palette involves 1/4 the number of comparisons.

Input sketch: https://editor.p5js.org/davepagurek/sketches/ANZ-YhpXA
<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td>

</td>
<td>

</td>
</tr>
</table>

#### PR Checklist
- [x] `npm run lint` passes
- [ ] [Inline documentation] is included / updated
- [ ] [Unit tests] are included / updated

I haven't added unit tests for these because exporting a gif seems a bit heavy of an operation for a unit test. I can add a manual test if you think that would be helpful though!

### CODE REVIEW

**Comment by jesi-rgb** [comment]
@davepagurek 
Dave! Always so great to know from you!

I definitely had big trouble with specific sketches that were not working properly, exactly as you are presenting here. I wasn't able to come up with a solution before the deadline though, so that's massive.

If this is resolving the problems, then go ahead with all the changes! I'll definitely look at the code and see if I can improve something, though you are miles away from me already :)

**Comment by jesi-rgb** [comment]
> When building the list of colors to quantize into a palette, we accidentally were adding the first frame over and over instead of all the frames of the gif. It now sends all the frames' colors into quantization. I didn't notice this when looking at the original PR, oops!

Totally my bad, not yours at all. I should've been more careful with that but I was quite a noobie in _hardcode_ vanilla javascript at the time. Massive thanks for this!

**Comment by davepagurek** [comment]
> Totally my bad, not yours at all. I should've been more careful with that but I was quite a noobie in hardcore vanilla javascript at the time. Massive thanks for this!

No one's to blame! It's super easy to slip by when writing and reading it (I've also done the same thing at work once or twice 😅)

> If this is resolving the problems, then go ahead with all the changes! I'll definitely look at the code and see if I can improve something, though you are miles away from me already :)

I figured I'd tag you in case you were interested, so no rush to review or anything!

**Comment by KevinWorkman** [comment]
One thing maybe worth thinking about: over on the Processing forum, GoToLoop has mentioned that this might increase the file size: https://discourse.processing.org/t/gifs-generated-with-savegif-only-contain-a-single-color/39954/6

I don't know how much of an increase this is, or if we care about an increase at all. I'm personally fine with larger files, but it might be worth thinking about.

**Comment by davepagurek** [comment]
If your gif only had one color on the first frame, this will probably increase the file size as now the gif's palette will include the whole animation's colours, but for other sketches, I think the file size will remain the same. The caching I was mentioning happens when mapping input colors (uncompressed, from the original sketch) to the 256-color gif palette. With or without caching, it still gets mapped to the same palette size; the cache is just there to remember what palette color an input color mapped to so that we don't have to check again. The old code compressed the input colors a little in order to make a cache key, and the new code doesn't. This means that, while constructing the gif, it the cache JS object will use more browser memory than before, but since that isn't part of the outputted gif, the file size should be effectively the same.

**Comment by Qianqianye** [comment]
Thanks @davepagurek. The fix looks good!

**Pull request merged**
