### PR TITLE
added doubleClicked() function

### PR DESCRIPTION
**Pull request by jay-manday**
I've implemented the requested `doubleClicked()` functionality to `src/events/mouse.js` as mentioned by @limzykenneth in issue #2038. I also added some documentation and an example as well. 

In addition to this I added `RAD_TO_DEG` and `DEG_TO_RAD` to `src/core/constants.js` as requested by @golanlevin in #2047

### CODE REVIEW

**Comment by limzykenneth** [comment]
@jay-manday Could you move the DEG_TO_RAD and RAD_TO_DEG constants to another branch and submit a separate PR just so we can review them individually? Thanks.

**Comment by jay-manday** [comment]
@limzykenneth absolutely, i reset `constants` to what they were before and will make a separate pr. I added the `doubleClicked()` method to the dom library. hopefully everything checks out! :)

**Comment by Spongman** [comment]
maybe RADIANS_PER_DEGREE and DEGREES_PER_RADIAN ?

**Comment by limzykenneth** [comment]
@jay-manday cool, not sure of @lmccart is back yet but I'll let her review this addition and merge it in if everything's fine.

Can you make the new PR for DEG_TO_RAD etc and perhaps @Spongman can discuss that over there?

**Comment by jay-manday** [comment]
apologies for the noise on this PR, I split the requested changes to Constants in a separate PR

**Comment by lmccart** [comment]
looks great, thanks!

**Comment by jay-manday** [comment]
Rad! 🎊 thanks again @limzykenneth for your time 👍

**Pull request merged**
