### PR TITLE
adds loadPixels back in re: #1588

### PR DESCRIPTION
**Pull request by shiffman**
@hobzcalvin tagging you in case you want to take a look as this reverts part of  8952a7c6869ebeeb385ce5e97adf8efb6fc26dc0

### CODE REVIEW

**Comment by shiffman** [comment]
@lmccart while working through this issue I also noticed that your commit 657d46e088948c81ebdfb47297dcbd37c79a3cbc results in an incorrect image size after calling `get()`.   You changed:

```javascript
c.width = elt.videoWidth = elt.width;
c.height = elt.videoHeight = elt.height;
```

to

```javascript
c.width = c.elt.width = elt.videoWidth;
c.height = c.elt.height = elt.videoHeight;
```

And the following example I get a 640x480 image instead of a 320x240 one.

```javascript
  var video = createCapture(VIDEO);
  video.size(320, 240);
  var snapshot = video.get(); 
```

Should I revert back as well?

**Comment by lmccart** [comment]
thanks for looking into this! argh the width/height thing is another one of those blocks of code that gets perpetually changed back and forth based on a few different use cases that break it in different ways. I'm not sure what to do. 🙁

**Comment by lmccart** [comment]
I guess this is the other use case involving createCapture(): https://github.com/processing/p5.js/issues/1490. So I think we want to test both and see if we can come up with a solution that works for both?

**Comment by shiffman** [comment]
@lmccart yeah, heh, let me look into it more and see what i can come up with!

**Comment by shiffman** [comment]
Ok, the issue is that we need the element's canvas to have a width and height whether `size()` is called or not.  When `size()` is called we want those dimensions, when it's not we want the native dimensions.  This seems to work now in both cases:

```javascript
      if (elt.width) {
        c.width = elt.videoWidth = elt.width;
        c.height = elt.videoHeight = elt.height;
      } else {
        c.width = c.elt.width = elt.videoWidth;
        c.height = c.elt.height = elt.videoHeight;
      }
```

I admit to being confused between all the different widths and heights so not sure if the above is still missing a possible use case?

However, there's a new problem where only the first call to `copy()` works and subsequent calls do not update the image being copied onto.   @lmccart if the above seems right to you, I'll add that in and try to determine what the other problem is.

**Comment by shiffman** [comment]
I could definitely use a sanity check on this but I believe I have resolved all the issues including:

1. `get()` works properly after `size()` has been called. #1588 
2. `copy()` works whether or not `size()` has been called. #1490 
3. `copy()` works more than just the first time.

**Comment by hobzcalvin** [comment]
Thanks for looping me in. I was new to the codebase with 8952a7c6869ebeeb385ce5e97adf8efb6fc26dc0 and couldn't run the tests properly, so I'm perfectly willing to believe that removing `loadPixels()` was a bad idea. I think my confusion was that `loadPixels()` doesn't seem to do anything that would affect this code as it's defined here: https://github.com/processing/p5.js/blob/8952a7c6869ebeeb385ce5e97adf8efb6fc26dc0/src/core/p5.Renderer2D.js#L248 That is, it updates `imageData` and `pixels` properties but these properties are completely unused by `get()`. I think what I overlooked is that `get()` in p5.dom.js *does* do substantive stuff that will affect `get()`, namely changing width/height values: https://github.com/processing/p5.js/blob/master/lib/addons/p5.dom.js#L1799

Anyway, not sure if that's helpful or not, but this change seems fine to me. You could perhaps add a comment noting that `loadPixels()` is needed because `p5.MediaElement`'s version does meaningful stuff.

**Comment by lmccart** [comment]
This looks good, thanks for sorting this out @shiffman!

**Pull request merged**
