### PR TITLE
feat: range iterator

### PR DESCRIPTION
**Pull request by ohayouarmaan**
resolves[#6644](https://github.com/processing/p5.js/issues/6644) : This PR adds a feature of range iterator which can be used to iterate over a certain value

Changes:
I changed the array_functions.js file inside the src/utilities and added the method range which takes in 3 optional arguments start, end, step if only one argument is provided it is assigned to the end and start gets initialized to 0 and step gets initialized to 1, if two arguments are provided then the first one gets assigned to start whereas the second one gets assigned to the end and step by default is 1, And if all three are provided then it gets assigned to start, end, step respectively

- [x] `npm run lint` passes
- [x] [Inline documentation] is included / updated
- [ ] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Comment by ohayouarmaan** [comment]
@all-contributors please add @ohayouarmaan

**Comment by ohayouarmaan** [comment]
https://github.com/all-contributors please add @ohayouarmaan for code

**Comment by ohayouarmaan** [comment]
@all-contributors please add @ohayouarmaan for code

**Comment by limzykenneth** [comment]
@ohayouarmaan For p5.js 2.0 we are not currently accepting implementation and just proposals. I will leave this PR around for now but I won't be reviewing it for the time being. Thanks.

**Comment by limzykenneth** [comment]
It was decided in the core committee and advisory committee stage that this proposal will not be brought forward for implementation in 2.0 so I'll close this for now. Thanks.

**Pull request closed without merging**
