### PR TITLE
Add issue form for p5.js 2.0 RFC proposals and make associated updates

### PR DESCRIPTION
**Pull request by GregStanton**
Addresses #6678 (This pull request addresses [a particular comment](https://github.com/processing/p5.js/issues/6678#issuecomment-1895389676) within the larger issue.)

**Changes:**
So far, I've created a draft of [the new issue form for RFC proposals](https://github.com/GregStanton/p5.js/blob/main/.github/ISSUE_TEMPLATE/1-p5.js-2.0-RFC-proposal.yml). I still need to make minor updates to the other issue forms and the config file.

### CODE REVIEW

**Comment by GregStanton** [comment]
Okay, I've updated all the issue forms that required updates. 

I decided not to update the Found a Bug form; the original idea was to indicate that this form would be used for bugs in 1.x by stating that pull requests for the issue should be submitted to the main branch. However, I figure it may be helpful to sometimes use this form for bugs in the development version of p5.js 2.0 (in the dev 2.0 branch). I suppose contributors could use the input field for the p5.js version to indicate which branch is relevant.

**Comment by GregStanton** [comment]
Also, I realized that no changes actually need to be made to the config file. I did, however, prefix the filenames with numbers, in order to make the p5.js 2.0 RFC issue form appear first. (The [order of the templates in the template chooser](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#changing-the-order-of-templates) is based on filenames.)

The idea is to give this new issue form greater visibility, since we're prioritizing work toward p5.js 2.0, and contributors may not know about it yet.

**Comment by GregStanton** [comment]
@limzykenneth: As I was preparing this pull request, I fixed a typo in each of the issue forms, but one typo remains. Specifically, the checkbox for the internationalization sub-area was misspelled as "internalization," which could cause confusion, since "internalization" is actually a word that means something else. 

I fixed this in all of the issue forms, but I remembered seeing this typo in the README file for the p5.js repo as well. When I fixed that typo in commit [e17ca92](https://github.com/processing/p5.js/pull/6748/commits/e17ca922e3507c68f88fac5b9454ad01cd461b8c), it caused some tests to fail. It'd be nice to resolve this so that the sub-areas in the README are consistent with the sub-areas in the issue forms, but it may take me a little while to investigate the cause of the failure. Do you happen to know what's going on? If not, I'd be happy to have this PR merged now. A typo isn't important enough to hold up this whole process, and it could be dealt with separately.

**Comment by limzykenneth** [comment]
Looks good. Thanks!

The typo issue we can have a look into it.

**Pull request merged**
