### PR TITLE
add README.txt to lib/ folder

### PR DESCRIPTION
**Pull request by montoyamoraga**
I added a README.txt file, making these considerations:

* I used .txt because it seemed more beginner-friendly.
* I used Markdown formatting anyway.
* I took into account that p5.dom.js is now part of p5.js

This PR is addressing processing/p5-js-website#483, which in turn was inspired by  processing/p5-js-website#474.

### CODE REVIEW

**Comment by lmccart** [comment]
It might be helpful to add a few notes for getting started. for example, a link to the get-started page, a link to the local-server page

**Comment by montoyamoraga** [comment]
great idea, thanks @lmccart, i just added some notes now.

**Comment by montoyamoraga** [comment]
@outofambit thanks, that's a great idea :)
i added some lines about how p5.js is a community and the link to the website.
i'm not 100% sure about the wording, but i like it that we include it :)

**Comment by lmccart** [comment]
thank you @montoyamoraga!

**Comment by coreygo** [comment]
Hello @outofambit @lmccart, I just noticed this merge and #3980 after creating a [potential patch](https://github.com/processing/p5.js/commit/aa339d38de71debb72a7455f183bb49f633b31a2).

I had renamed the file to `README.md` as well—partly because I was confused by Markdown in a .txt while viewing on Github and the doc itself refers to [`README.md`](https://github.com/processing/p5.js/pull/3947/files#diff-e17061ebbf39e2a2123961afd0571d6aR50)—but undid that change to make the diff easier to view and from reading [#3980](https://github.com/processing/p5.js/pull/3980#issuecomment-526858755).

I can create a new pull request with the proposed changes and the .txt extension if it looks okay otherwise… figured I should ping for feedback beforehand. 🖖

**Comment by outofambit** [comment]
hey @coreygo thanks for checking in! i agree its a bit confusing to use markdown in a `.txt` file, and i'm open to ideas around making that better.

i also think there's a little confusion around the purpose of this `README` file. the intent is to have a readme file included with the archive you can download from https://p5js.org/download/ so that people using p5 from that entrypoint have a kind of welcome doc (along with the code). so i don't think we want to include descriptions of things like `p5.pre-min.js` or the custom build outputs. does that help?

there's a better way to communicate the intent for this file, but i'm not sure what that is yet. maybe we can add a comment at the top of the file? what do you think?

**Comment by coreygo** [comment]
> the intent is to have a readme file included with the archive you can download
> …
> so i don't think we want to include descriptions of things like p5.pre-min.js or the custom build outputs.

Oh silly me. Totally missed that last night :sleeping:, makes sense.

> there's a better way to communicate the intent for this file, but i'm not sure what that is yet. maybe we can add a comment at the top of the file? what do you think?

Perhaps. Maybe something as small as `…library ZIP file, yay!` to make it super obvious.

I don't really have a strong opinion with regards to the file extension. Using Markdown anyway seems fine. Some clarification that Markdown in a plain text file is intentional might help clear up potential confusion, [README.txt#L50-L52](https://github.com/processing/p5.js/blob/master/lib/README.txt#L50-L52):
```md
## README.txt

This README file formatted with Markdown :)
```

Am happy to make a quick patch with any proposed minor changes.

**Comment by outofambit** [comment]
@coreygo i like both of your suggestions! would be happy to merge that with any other edits you have for the file. let's do it :)

**Pull request merged**
