### PR TITLE
Better loadTable function

### PR DESCRIPTION
**Pull request by workergnome**
I've re-written the loadTable function to handle more of the craziness that is the CSV file format.

I added a couple sanity checks to the code—it now checks if you try and set it to both 'tsv' and 'csv', and will throw an error.

It's now using the `reqwest` library as opposed to raw `XMLHttpRequest`.

The actual parsing code is heavily based on https://github.com/gkindel/CSV-JS —I've taken out some of the strictness—mostly, it will now accept both windows and unix line endings, as opposed to only allowing windows (`\r\n`) style line feeds.  It **will** fail if you feed it CSV files with random spaces, or blank lines.

I also added a bunch of new tests to the code.  I can't figure out how to test the preload functionality, and it would probably be a good idea to add some tests for TSV files, as well.  

Also, I'm currently using a link to my branch to host the test CSV file ([see link](https://github-raw-cors-proxy.herokuapp.com/workergnome/p5.js/csv_tests/test/unit/input/csv.csv)). That should probably be ported over to using the actual repository, but if I do that, the tests will fail, since the file's not actually there yet.  If this gets accepted, that's an easy fix.

This addresses issue #545 and #547.

### CODE REVIEW

**Comment by workergnome** [comment]
There is a potential issue with this—the reqwest framework is interpreting the loaded file's type automatically, which works with the test, but doesn't work with my local server.  The proper fix here is to explicitly state the type—but then the test data doesn't work.  

The proper response here is to upload the test data somewhere—I could stick it on a server, but is that sustainable?

**Comment by kevinb7** [comment]
You could run a static web server as part of the test harness.  This should work when running the tests on travis-ci as well.

**Comment by lmccart** [comment]
thanks for this @workergnome!
perhaps we could add a directory on p5js.org that hosts static files for cases like this?

**Comment by workergnome** [comment]
That's probably easier than rigging a static web server.  I think eventually, a static web server could be very useful, but that's probably a bigger project than just this.

**Comment by lmccart** [comment]
cool, you can just submit a PR here with the file:
https://github.com/processing/p5.js-website

maybe add a directory "p5-tests" or "p5-static"?

**Comment by kevinb7** [comment]
The nice thing about having a node based static web server is that people can run the tests without having to be connected to the network.

**Comment by workergnome** [comment]
@kevinb7 I totally agree.  Want to set up an issue to make that happen, or should I?

**Comment by kevinb7** [comment]
@workergnome I can set up an issue.  I have some time today, so I should be get a pull request in for it too.

**Comment by kevinb7** [comment]
@workergnome I'm using grunt-contrib-connect and it's serving the .csv file fine, but reqwest thinks it's a .js file and then it tries to eval it.  I tried setting the ```type``` setting to 'text' but apparently that's not a valid setting.

**Comment by kevinb7** [comment]
@workergnome I found out why your server works and grunt-contrib-connect is not.  The heroku server in the tests converts the CSV to JSON before serving it.  This is what I receive when I do a ```GET``` on the heroku server:
```
"name,age,height\nDavid,31,80\n\"David, Jr.\",11,61.5\n\"David,\nSr. \"\"the boss\"\"\",95,88"
```
What I would expect is:
```
name,age,height
David,31,80
"David, Jr.",11,61.5
"David,
Sr. ""the boss""",95,88
```
as text/plain or text/csv not application/json.

**Comment by workergnome** [comment]
Yeah--I have a fix for that. I'll push it when I get home. 



—
David Newbury
(773) 547-2272
david.newbury@gmail.com

**Comment by kevinb7** [comment]
Sounds good.  I've got it working using XHR for the time being.  I'm just fighting with grunt to start a server and keep it alive while running tests.

**Comment by kevinb7** [comment]
I have to prep for a talk I'm giving in a couple of hours, but I'll be able to look at it again later this evening.

**Comment by workergnome** [comment]
I created a new pull request with the fix—I believe it works, though we should revise the tests using what you're working on.

**Pull request merged**
