### PR TITLE
Quiet travis build

### PR DESCRIPTION
**Pull request by Spongman**
this disables the 'nyan' mocha reporter during travis builds to stop it from filling up the log files with ascii-art junk.

### CODE REVIEW

**Comment by tawez** [comment]
Why 'nyan' reporter at all?

**Comment by Spongman** [comment]
it has been nyan since 1f4a32cb8443dad56f85947680c16d836bddb238. i think changing it is outside the scope of this PR.

**Comment by lmccart** [comment]
art junk!? ;)

**Comment by Spongman** [comment]
yeah, it's like head-bopping ascii cat had some rather serious rainbow-colored, inter-planetary gastroenterological issues in the log file.

**Pull request merged**
