### PR TITLE
Create visual test system

### LINKED ISSUE #6576: Add visual tests to prevent regressions
### Topic

This is something I've been thinking of adding to our test suite, but I wanted to make an issue to discuss it first so that when I get around to adding it, it can incorporate any feedback and suggestions people have.

## Motivation

- It's pretty hard to make changes and make sure we haven't broken *something*
- We have a good set of tests, but many of these tests are brittle because they don't check that sketches look the way we expect, they check via proxy: sometimes they check one or two pixels, other times they check that p5 internals are in an expected state
- Writing unit tests that check proxy outcomes like internal state are harder to write than test sketches, which is something contributors are already familiar with

## What are visual tests?

These would be a series of small sketches that we write when we add new features. The idea is that they look correct right now, so we save an image of what they look like. Then, when future changes are made, we can run them again and make sure they still look like that saved image.

## Design

I'm thinking of implementing something like this:

You write test cases with a custom test wrapper function:
```js
testVisual('drawing a circle', (p5, screenshot) => {
  p5.setup = function() {
    createCanvas(100, 100);
  }
  p5.draw = function() {
    p5.fill('red');
    p5.circle(p5.width/2, p5.height/2, 20);
    screenshot(); // This is like `done()` in normal tests
  }
})
```

Under the hood, this translates into something like:
```js
function testVisual(name, callback) {
  test('[visual] ' + name, () => {
    const myp5 = new p5();
    return new Promise((resolve) => {
      callback(myp5, resolve);
    }).then(() => {
      // TODO: take screenshot and follow the logic below
    });
  });
}
```

Once the `screenshot` method is called, we:
- Call `canvas.toDataURL()` on the underlying canvas element
- Check for a file in a screenshots folder matching the name of the test case
  - If the file does not yet exist and we're in the CI runner, fail the test case
  - If the file does not yet exist and we're running locally, write the image to a png file with the expected name.
  - If the file does exist, load it, and compare each pixel. Pass the test case if every pixel value is the same within a small threshold (e.g. 2/255)

Ideally, I'd also add a page in the `grunt yui:dev` server to easily see the saved images and to rerun tests, but as a first step, these would just get run as part of the normal test suite, where you can use the existing test filtering to `grep` for `[visual]` to just run visual tests.

## Open questions

- The threshold might need some change based on how different it ends up being on different systems. Maybe we don't need EACH pixel to be the same, as long as like 99% of them are the same? That might need some trial and error since I don't yet know how exact we can expect results to be (or how big a change regressions generally cause.)
- How slow is it to run this for a lot of images on Github's test runner? Do we need to resize images down to something small (20x20?) before comparing so we loop over fewer pixels?

### PR DESCRIPTION
**Pull request by davepagurek**
Resolves #6576

### Changes
This adds a visual test suite to p5. It involves adding test files to `test/unit/visual/cases` that look like normal-ish test cases, but where you call `screenshot()` at various points to save an image of its current state.

Some of the constraints this is designed around:
- **We may or may not want to have these run in CI.** Currently, the same test code is run in both a manual test runner and in CI, but one can add a visual test file only to the manual test runner list. It also means it uses mocha functions under the hood, and provides alternate implementations for the manual visual test runner.
- **Antialiasing differences shouldn't fail a test.** After taking the difference between actual/expected images, I run the ERODE filter to shrink away single pixel artifacts. After that, I apply a threshold of 10/255 in each color channel to call a test case failed.

I've also added some instructions to the unit testing contributor doc on how to use these/add more.

### Screenshots of the change

image

Hover over images to see what they represent:
image

#### PR Checklist
- [x] `npm run lint` passes
- [x] [Inline documentation] is included / updated
- [x] [Unit tests] are included / updated

### CODE REVIEW

**Comment by limzykenneth** [comment]
@davepagurek I have the exploration [fork](https://github.com/limzykenneth/p5.js/tree/test-exploration) passing quite a few tests with Vitest here if you want to review if this system can work with Vitest. I can merge this at this stage as well if you want it incorporated at this point.

**Comment by davepagurek** [comment]
Thanks for the link! I was testing it out, and have made a bit of progress getting it to run after some minor changes (`import`ing scripts instead of relying on script tags in HTML, using `beforeAll` instead of `setup`, etc) although I'm currently stuck on fetching the expected images inside `vitest`. I gather it doesn't launch a local webserver of any kind, is that right? Our existing tests of loading images may have the same issue, would we have to manually spawn one in order for those to pass?

**Comment by limzykenneth** [comment]
As I understand it, it would spin up a server since the tests runs in the browser but it won't be directly usable (ie. made to serve static assets, though I may be wrong). The idea is to use mocks and stubs to get around it. I found the suggestion in the [documentation](https://vitest.dev/guide/mocking.html#requests) to use [Mock Service Workers](https://mswjs.io/) which will act like a server but could be more suitable for a test environment.

**Comment by davepagurek** [comment]
An alternate approach that doesn't need a web server would be to find something like the plugin we use to import shaders, but to import image data into maybe a base64 string. It looks like that's what happens when you `import` an image when vite is in library mode, so that could maybe work here if that's preferable to also spawning a server?

The other thing that looks like it'll need updating is how we save expected images to files if none are generated yet. Currently, it's using puppeteer's API to pass the data to nodejs. Do you know if there's any equivalent of that for the vitest runner?

**Comment by limzykenneth** [comment]
I can look into the static file serving bit to see what's possible.

> The other thing that looks like it'll need updating is how we save expected images to files if none are generated yet. Currently, it's using puppeteer's API to pass the data to nodejs. Do you know if there's any equivalent of that for the vitest runner?

I'm not entirely sure what this refers to?

**Comment by davepagurek** [comment]
> I'm not entirely sure what this refers to?

This bit of code in the PR registers a function within the puppeteer window, and then passes the data to `fs.writeFileSync`:

https://github.com/processing/p5.js/blob/5f89e239f12a608417ff132d971ccddcdc792096/tasks/test/mocha-chrome.js#L37-L52

Right now that's how the visual test runner can save a screenshot to the filesystem when one does not yet exist, used as a way to generate initial screenshots for new tests. In vitest we'd have to use some other method of passing data to nodejs to have write access to the filesystem I think.

**Comment by limzykenneth** [comment]
It might be possible but we need to look into the API and [options](https://vitest.dev/config/#browser-provideroptions) for WebDriverIO (the Vitest equivalent of Puppeteer). Although if we can avoid that if possible it would be my preference, ideally each test always run idempotently.

**Comment by davepagurek** [comment]
Another option could be to have a script that we run that spawns a puppeteer window that runs the same test code, and gives it access to the filesystem similar to how it works with puppeteer right now. It means needing the test code to be runnable in two different contexts that way, but I think that would be doable.

**Comment by limzykenneth** [comment]
That would more or less mean having two different test runners though and complicate things a bit. Playwright is the other browser test driver that Vitest supports which has more similar API to Puppeteer if desired. 

However, if the plan is to automatically generate the initial screenshot that future test will compare against (if I understand this feature correctly), we can possibly use Vite and a small HTTP server as part of a slightly more manual step which will serve the visual test code, wrap it in a POST request to the small HTTP server, which will then save it to file accordingly.

Since this feature is not meant to be run in CI, it can possibly be this more manual step? This will also keep the tests idempotent, where test cases where initial screenshot not yet exist be reported as "Pending" instead of  pass or fail, if that made sense.

**Comment by davepagurek** [comment]
That also works! Yeah it's just for test writers who are creating the original reference image, so no need for it to work in CI (I haven't looked into this aspect of vitest yet, but if the case that would generate a new screenshot is encountered in CI, it should fail the test. Currently I'm looking at an env var that's set, presumably there's some equivalent we can look at in the new system.)

**Comment by davepagurek** [comment]
@limzykenneth since we have a 2.0 branch now, how do you feel about merging this to main so that we can start using visual tests, and then I can make a PR into the 2.0 branch to add a compatible version of the tests into the new test runner?

**Comment by dhowe** [comment]
This is great. Is the idea to port over some or all of the tests currently in https://github.com/processing/p5.js/tree/main/test/manual-test-examples

**Comment by davepagurek** [comment]
@dhowe I think so! some of them are performance tests, which don't need to be converted. Others would be great to port into this system, since I don't think we're in the habit of checking manual tests for each PR (at least I'm not in the habit 😅), and that porting process probably includes scoping down the sketches into a smaller canvas size so it can be tested more quickly in CI than e.g. a fullscreen sketch

**Comment by dhowe** [comment]
> @dhowe I think so! some of them are performance tests, which don't need to be converted. Others would be great to port into this system, since I don't think we're in the habit of checking manual tests for each PR (at least I'm not in the habit 😅), and that porting process probably includes scoping down the sketches into a smaller canvas size so it can be tested more quickly in CI than e.g. a fullscreen sketch

excellent -- very useful for the typography stuff

**Comment by limzykenneth** [comment]
@davepagurek You can merge this whenever you are ready and we can look into how this can work in 2.0

**Pull request merged**
