### PR TITLE
Update release process to use np

### LINKED ISSUE #4336: CDN link on jsdeliver needs version update
#### Most appropriate sub-area of p5.js?
- [x] Other - CDN linking to library

🎉 on 1.0!
Looking to link to latest CDN, but found a minor issue with jsdeliver paths:
generic [https://cdn.jsdelivr.net/npm/p5](https://cdn.jsdelivr.net/npm/p5) – still points to v0.10.2
manual [https://cdn.jsdelivr.net/npm/p5@1.0.0](https://cdn.jsdelivr.net/npm/p5@1.0.0) - looks new, but still says v0.10.2 with today's date in header.

Probably just looking at these links too early – but wanted to share incase those details should have updated automatically.

### PR DESCRIPTION
**Pull request by limzykenneth**
Resolves #4336 

 Changes:

Moving steps to release the library to NPM and github to use `np`. The steps for bower and docs release are still the same and covered automatically. 

To create a new release, just run `npm run release` and following the command prompt.

---

TODO:
* [x] Update contributor docs (some functionalities not working perfectly)
* [x] Potentially update bower and docs release steps (releasing from Windows now supported)
* [ ] Potentially use webhooks for deploys instead

### CODE REVIEW

**Comment by limzykenneth** [comment]
@lmccart Do have a look when you can. When this is ready to merge it may be better to squash and merge as the commit history has too much testing noise.

**Comment by limzykenneth** [comment]
@lmccart I think this is as far as I'm going to take it this time round. Webhooks and CI builds may be something for another day.

The release step is now as simple as running `npm run release`. To do a dry run it's `npm run release -- --preview`. The contributor docs has been updated to reflect these. The choice of version number is handled as part of the interactive command prompt of `np`. The files write and git stuff are all rewritten to not rely on shell commands but functionally they should be the same as before.

I don't have a Windows machine to test but as far as I know it should work by default as long as `node` and `npm` works in the user's shell so there's no need for a Windows user to get a Unix environment to do the release.

I've done as much test as I can do on my end but I think the only way to know for sure if it works well is to run it on a release. When you are ready to run the next release with this, you can contact me and I'll see if I can be available then for any quick debug/fix necessary.

**Comment by lmccart** [comment]
This is great. I tried the dry run and it seemed to all work correctly. I am not sure I did the squash merge correctly, please let me know and forgive me if I messed this up. But as far as I can tell, the code is merged in now, just not directly attributed to you @limzykenneth 😳

**Comment by limzykenneth** [comment]
Thanks @lmccart, the commits seems to be squashed and committed to the repo but this PR is still opened. Shall I just close it?

**Pull request closed without merging**
