### PR TITLE
Fix alias

### PR DESCRIPTION
**Pull request by maxdevjs**
Recently I have modified Github and Twitter usernames.

Fixes:

- displayed username
- Twitter link

### CODE REVIEW

**Comment by limzykenneth** [comment]
Hi @maxdevjs, you may need to modify [this file](https://github.com/processing/p5.js/blob/master/.all-contributorsrc) instead as the readme entries are generated from that.

**Comment by maxdevjs** [comment]
Thank you @limzykenneth , absolutely right :man_facepalming: 

What is better:

- just to edit [.all-contributorsrc](https://github.com/processing/p5.js/blob/master/.all-contributorsrc)
- edit [.all-contributorsrc](https://github.com/processing/p5.js/blob/master/.all-contributorsrc), run `all-contributors generate` and then pull

?

**Comment by ihsavru** [comment]
Hi, I accidently merged your pr (I have reverted the changes), could you please open a new one.

**Comment by maxdevjs** [comment]
@ihsavru thank you very much for letting me know. Starting from the beginning now :)

**Pull request merged**
