### PR TITLE
Add param to redraw() to control the number of redraws #1389

### PR DESCRIPTION
**Pull request by nok**
I added a minor feature related to the idea or request of @emilyxxie in issue https://github.com/processing/p5.js/issues/1389.

By the way I fixed the indentations of the prior example code:

screen shot 2016-07-02 at 01 05 10

### CODE REVIEW

**Comment by nok** [comment]
There is still a failed test with the exception "code took too long to execute". On my local machine all tests passed successfully. I will check it.

**Comment by limzykenneth** [comment]
Probably just need to rerun the test on travis

**Comment by lmccart** [comment]
looks good, thanks for this. two minor suggestions for the documentation before we merge this in.
1. rather than just updating the example, let's include both examples, as they demonstrate the two different uses of the  function.
2. could you add a note in the function description that explains this optional use, and add an optional parameter to the method documentation. you can read more about inline documentation here: https://github.com/lmccart/p5.js/wiki/inline-documentation, or see [this example](https://github.com/processing/p5.js/blob/master/src/core/p5.Element.js#L117) for showing optional arguments.

**Comment by nok** [comment]
Thanks for the notes, @lmccart. I hope the documentation is comprehensible.

**Comment by lmccart** [comment]
looks great, thanks!

**Pull request merged**
