### PR TITLE
docs(reference): Copy-edits to reference docs

### PR DESCRIPTION
**Pull request by Zearin**
Changes:

Lots of copy-edits to the source (docstrings) used to generate the p5.js Reference.

Though numerous, the edits are individually minor.  Most are related to formatting or grammar.  A few are for phrasing or clarity.  I also added a few links to other areas of the reference where appropriate.

#### PR Checklist

- [x] `npm run lint` passes†
- [x] [Inline documentation] is included / updated
- [x] [Unit tests] are included / updated

†: Although the lint task completed successfully, the `yuidoc:prod` task noted that several methods were missing examples.  I didn’t remove any examples at all, so I hope this won’t cause an issue with any automated PR testing.

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Comment by Zearin** [comment]
This PR seems to be ignored because I didn’t check the unit tests box in the original post (since unit tests are n/a).

I don’t want this to get too far behind, so I’ll try and check the box to see if this PR gets reviewed by a human...

**Comment by outofambit** [comment]
hey @Zearin, thanks for this! i had already started looking at the changes earlier this week (made it through 12/61 files), but the PR is quite large which makes it a bit hard for someone else to look through and verify or offer feedback on. i saw a lot of nice copyediting for punctuation, etc. and i think some files have more involved changes. Could you list which files have more involved changes or move those into a separate PR? I think that would help us review this faster. thank you!

**Comment by Zearin** [comment]
@outofambit Thanks. :)  It’s been a while.  Sorry about the delay!  I think I’ll refresh my source and start a new PR with all the easy stuff first.

**Comment by Zearin** [comment]
Closing this issue in favor of smaller PRs.

**Pull request closed without merging**
