### PR TITLE
Provide description for WEBGL

### PR DESCRIPTION
**Pull request by maddyfisher**
Added a description for the WEBGL constant where beginners are able to understand clearly what WEBGL is and why p5.js is using it.

### CODE REVIEW

**Comment by lmccart** [comment]
@maddyfisher looking great so far! my one suggestion is to break this description into two lines for easier reading. something like this:

```js
* One of the two render modes in p5.js: P2D (default renderer) and WEBGL.
* Enables 3D render by introducing the third dimension: Z. 
```

**Comment by maddyfisher** [comment]
@lmccart yes, I agree, looks much better!

**Comment by lmccart** [comment]
@maddyfisher the linter is confusing here. the problem is not actually the periods, it's the single space after the last character (period or not). so `Delete /`·/`` actually means delete space.

**Comment by lmccart** [comment]
🙌

**Pull request merged**
