### PR TITLE
Replaced all console.error with p5._friendlyError

### LINKED ISSUE #6630: Replace console.error with friendly error system
### Increasing Access

Many functions inside `src/webgl` and `lib/addons` currently uses `console.error` to report errors. It would be more user-friendly and consistent with the p5.js environment to replace these calls with the friendly error system (FES).

### Most appropriate sub-area of p5.js?

- [X] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [X] Friendly Errors
- [ ] Other (specify if possible)

### Feature enhancement details

For example, take `parseASCIISTL` function in `webgl/loading.js`,
I have triggered an error condition and the results,
<br></br>
with console.error:
Screenshot 2023-12-13 at 10 41 06 PM
<br></br>
with FES:
Screenshot 2023-12-13 at 10 42 01 PM
It would be more user-friendly and consistent with the p5.js environment to replace these calls with the friendly error system (FES).

### PR DESCRIPTION
**Pull request by samrudh3125**
Resolves #6630 

 Changes:
All the console.error in the codebase were replaced with p5._friendlyError. Since this is my first contribution kindly accept this.

 Screenshots of the change:

Screenshot (34)

#### PR Checklist

- [x] `npm run lint` passes
- [ ] [Inline documentation] is included / updated
- [ ] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Comment by samrudh3125** [comment]
Since this is my first contribution i didnt exactly understand what is inline documentation and unit tests. Please accept the pull request as i have put a lot of time in this contribution

**Comment by samrudh3125** [comment]
@all-contributors please add @samrudh3125  for THING(S)

**Comment by samrudh3125** [comment]
all-contributors please add @YOUR-USERNAME for p5.js

**Comment by samrudh3125** [comment]
@all-contributors please add @samrudh3125 for processing/p5.js

**Comment by samrudh3125** [comment]
@all-contributors please add @samrudh3125  for a11y

**Comment by perminder-17** [comment]
Hey @samrudh3125, thanks a lot for your work on this. However, that's not exactly how it works. For example, when I use console.err(e), it means I’m unsure of what’s happening or what kind of error might be occurring, and we get a line from the p5.js library. Friendly errors, on the other hand, are designed to be more helpful to the user. They point out the specific line in your code where the issue happened and even suggest possible solutions. These errors are not only formatted clearly but also provide guidance. You can see an example below where both an error message and a friendly error message are shown.

Screenshot from 2024-10-02 09-06-02

So, closing this PR, but thanks a lot on your work.

**Pull request closed without merging**
