### PR TITLE
Add method to calculate heading between two vectors

### PR DESCRIPTION
**Pull request by pakosaldanaort**
I wrote the method **headingVectors()**  to calculate the heading between two vectors, this solve the Feature Request #3240

### CODE REVIEW

**Comment by lmccart** [comment]
Thanks! I think this method could just be called "heading".
We will need inline documentation in order to add this. See guidelines [here](https://github.com/processing/p5.js/blob/master/developer_docs/inline_documentation.md)

**Comment by pakosaldanaort** [comment]
@lmccart  I already added documentation and change the method name to "headingBetween", I didn't change the name to "heading" because javascript is not supported the Overloading

**Comment by vipulrawat** [comment]
@pakosaldanaort Is this supposed to calculate the angle between two vectors `v1` and `v2` or two create a heading vector for a specific angle?

**Comment by pakosaldanaort** [comment]
@vipulrawat is to calculate the angle of rotation between two vectors

**Comment by pakosaldanaort** [comment]
I will work on that @vipulrawat Thanks for your comments :+1:

**Comment by vipulrawat** [comment]
@pakosaldanaort Cool. I am currently assigning WIP label so that others will know that you are currently working on this PR. Remove the label when you're done. :) :+1:

**Comment by pakosaldanaort** [comment]
@vipulrawat @lmccart I already updated the documentation and the examples :+1:

**Comment by vipulrawat** [comment]
@pakosaldanaort Code looks good to me. But is there any special need for this function when the same results can be obtained with [this](https://p5js.org/reference/#/p5.Vector/angleBetween) method. 
Because the results of this code is quite different from `let a1 = v1.copy().sub(v2).heading();` mentioned in #3240. What I am missing?

**Comment by lmccart** [comment]
@pakosaldanaort can you address @vipulrawat's question? we will need to understand this in order to consider merging. thanks

**Comment by Spongman** [comment]
i think the `atan2` method is superior since it avoids the two `sqrt` calls.

even _if_ this isn't merged, i think the `angleBetween` method should use this trig. or if this _is_ merged, the `angleBetween` method should be re-implemented as a call to this method plus some `abs` & 2PI-modulo.

**Comment by outofambit** [comment]
I'm going to close this since this hasn't seen any activity in quite a while. @pakosaldanaort please comment or reopen if you would like to talk more. thanks!

**Pull request closed without merging**
