### PR TITLE
fix `normalMaterial` in 'mixedMode' manual test

### PR DESCRIPTION
**Pull request by EOstling**

### CODE REVIEW

**Comment by stalgiag** [comment]
This is great @EOstling! I think you can remove the reference comments that you added as they won't be necessary for future developers. If someone wants to know why changes were made to that section of the manual test in the future they can look at the commit history for the repository.

**Comment by EOstling** [comment]
Ok, total PR newbie here...how do I remove the reference comment?

**Comment by stalgiag** [comment]
That's cool @EOstling! Always exciting to work through something for the first time. If you remove lines 1-4 (the new lines at top and the `To do ...` comment) and remove line 20 (`removed args` comment) on the local copy of your fork in the normalize branch, and then commit the changes and push to the normalize branch, it will update here automatically in the pull request.

**Comment by stalgiag** [comment]
linking to #3575

**Comment by stalgiag** [comment]
Hi @EOstling what is your status on removing the comments? Others have been asking about fulfilling this issue. I am willing to offer more time for you to finish this but need communication from you because I don't want to let this sit here for too terribly long. Thanks!

**Comment by EOstling** [comment]
Hey @stalgiag I can work on this tonight and get a new PR in.

**Comment by EOstling** [comment]
@stalgiag should be good now.

**Comment by stalgiag** [comment]
Hi @EOstling this is close but your your Travis Build is failing. [See here](https://travis-ci.org/processing/p5.js/jobs/507299830) or click the link below "All checks have failed" above. This test is the same that should happen when you run 'npm run grunt' in your local repository. We can look at the specific error at the bottom and see that it says '/home/travis/build/processing/p5.js/test/manual-test-examples/webgl/mixedMode/sketch.js:15:24: Delete `·` [Error/prettier/prettier]`. This probably means that you have an extra space at the end line 15 which prettier does not like. This would make sense because if we look at the diffs we can also see that git seems to think that line 15 was changed by you ([line 15 is red on the left and green on the right here even though the code looks the same](https://github.com/processing/p5.js/pull/3580/files)). Anyways, these kinds of white space problems can usually be fixed by running `npm run lint:fix` in your repository. You can also manually remove the offending white space if you would like. Once `npm run grunt` (and by extension the Travis CI tests pass) we can merge this. For more information on the development process for p5 [check over here](https://github.com/processing/p5.js/tree/master/developer_docs).

**Comment by Spongman** [comment]
can you remove the `package-lock.json` changes from the PR?

**Comment by Spongman** [comment]
err, no, don't remove that file, just remove the changes you had made. at this point you might need to rebase and cherry-pick.

**Comment by stalgiag** [comment]
Or if it seems easier @EOstling you can always start a new branch from master, change only the one line in that pull request, open a new pull request with your new branch and close this PR. If you do this just make sure to @ me in the one. I know this seems a bit tricky but it really does get easier with time plus it is a nice feeling to have your changes merged into an open-source project.

**Comment by stalgiag** [comment]
Hi @EOstling ! I haven't seen any movement on this in some time. I am going to close this pull request and reopen the issue for help from others. Feel free to keep taking on issues and opening pull requests in the future!

**Pull request closed without merging**
