### PR TITLE
webgl: Per pixel lighting

### PR DESCRIPTION
**Pull request by Spongman**
`setAttributes('perPixelLighting', true)` enables use of a Phong specular lighting model.

before & after:
image

this PR includes and relies on some other PRs:
- #2428 lighting-fixes
- #2433 implicit normals (for primitive geometry)
- #2446 fromAngles (for the getAttributes sample)

this PR should simplify significantly if those are merged first.

### CODE REVIEW

**Comment by mlarghydracept** [comment]
Cool! A few thoughts as I am testing everything and preparing to merge your various awesome pull requests over the next few days - 

Can you make sure to label something if it is a work-in-progress?
Also do you think I should address your pending GL pull requests in a specific order? Should I assume the three you mentioned above are first in line? Just want to make sure there are as few conflicts as possible with merge order.

**Comment by Spongman** [comment]
awesome! yes, all these PRs are ready to commit (aside from all the bugs i missed, of course ;-)

if you merge those three PRs first (they're all independent), this one should be much simpler. i'll try to fix any conflicts that come up if i catch them in time.

**Comment by kjhollen** [comment]
😻 😻 😻 wow these results look awesome! @mlarghydracept do you want to review this one?

**Comment by mlarghydracept** [comment]
Yeah I agree. That shader has fantastic results! I would say it might be a good idea to write a manual test for this one. Something that switches in and out of the phong specular. Just to have something to test with down the line. Otherwise I would say this looks good to merge but I would like to merge #2446 first. I don't feel qualified to evaluate that one so I pinged @lmccart for a review of it. Will merge this as soon as that is merged.

**Comment by lmccart** [comment]
@mlarghydracept #2446 has been merged

**Comment by mlarghydracept** [comment]
Okay cool just tested a bunch and this is fantastic! Ready for a merge except two really small requests:

1: Could you put a short instruction in the perPixelLighting manual test? Just for future contributors to know that they should click to test. You can put it in the HTML if that is easier.

2. Also in the manual-test, can you load the teapot model in [preload()](https://p5js.org/reference/#/p5/preload)? I know that several other manual tests don't this but it is something I realize we should fix as we go because sometimes it is hard to test on slower machines because you can't tell if it is broken while loading.

Thanks again!

**Comment by mlarghydracept** [comment]
Thank you!

**Comment by sanketsingh24** [comment]
@Spongman  I just wanted to know your logic behind using [500 in line 89 of phong.frag](https://github.com/processing/p5.js/pull/2449/files#diff-38ed3d0faa51831a518d47b0717d49bbR89). I am implementing a `falloff` function which will set custom attenuation, so just wanted to know about this.

**Comment by Spongman** [comment]
oh you can ignore my code there... it's not correct because it's not scale-invariant. just replace it with whatever you have. i had a PR a while back that included an implementation of Processing's `falloff`, but it didn't make it in, unfortunately.

**Pull request merged**
