### PR TITLE
Add examples for rotationX/Y/Z

### PR DESCRIPTION
**Pull request by limzykenneth**
Thanks to @aatishb for the examples. See #1249.

### CODE REVIEW

**Comment by limzykenneth** [comment]
No idea why the test is failing...can someone have a look?

**Comment by limzykenneth** [comment]
If I'm not wrong [this line](https://github.com/processing/p5.js/blob/master/test/test-reference.html#L63) is what exclude the 3D section from failing the test. Given that only three properties in [acceleration.js](https://github.com/processing/p5.js/blob/master/src/events/acceleration.js) uses WEBGL, it might be overkill to exclude it as well. Is there some other way we can ignore a missing WEBGL error in phantomjs?

**Comment by lmccart** [comment]
I just added an exclude for this file, but I agree, this might not be ideal. I wonder if @toolness has any thoughts about alternative ways of gracefully handling webgl errors?

**Comment by limzykenneth** [comment]
@lmccart I found that instead of `/events/` for the regex, `/events\/acceleration\.js/` works as well and ensure that the rest in `events` get tested.

**Comment by toolness** [comment]
Hey, sorry I haven't replied to this yet... I have some ideas for this but they might tie into the whole documentation system, so I think I will save it for a blog post. More details coming soon!!!

**Comment by lmccart** [comment]
thanks @limzykenneth, i just updated the regex per your suggestion

**Pull request merged**
