### PR TITLE
implementation of p5.Camera.set() function

### LINKED ISSUE #6238: implementation of p5.Camera set() function
### Increasing Access

I would like to have a function like the p5.Vector set function for the camera, so I would like to propose an implementation.

This function copies information such as the eye and center of the argument camera, cameraMatrix, projMatrix to the target camera. If the target is active, update both uMV and uP. Other properties related to projection mode are not copied. So this function is supposed to be used between cameras with the same projection mode.

```js
set(cam) {
  // Copies information about the camera's view.
  // At this time, if this camera is active, uMVMatrix will be updated
  // with this cameraMatrix.
  this.camera(
    cam.eyeX, cam.eyeY, cam.eyeZ,
    cam.centerX, cam.centerY, cam.centerZ,
    cam.upX, cam.upY, cam.upZ
  );
  // Copy the camera's projection matrix.
  for (let i = 0; i < 16; i++) {
    this.projMatrix.mat4[i] = cam.projMatrix.mat4[i];
  }
  // If this camera is active, update uPMatrix.
  if (this._isActive()) {
    for (let i = 0; i < 16; i++) {
      this._renderer.uPMatrix.mat4[i] = this.projMatrix.mat4[i];
    }
  }
}
```
For example, after moving the camera with orbitControl(), this function is useful when you want to return to the initial state with some interaction.

```js
let cam, initialCam;

function setup() {
  createCanvas(100, 100, WEBGL);
  strokeWeight(3);

  // Set the initial state to initialCamera and set it to the camera
  // used for drawing. Then set cam to be the active camera.
  cam = createCamera();
  initialCam = createCamera();
  initialCam.camera(100, 100, 100, 0, 0, 0, 0, 0, -1);
  cam.set(initialCam);

  setCamera(cam);
}

function draw() {
  orbitControl();
  background(255);
  box(50);
  translate(0, 0, -25);
  plane(100);
}

function doubleClicked(){
  // Double-click to return the camera to its initial position.
  cam.set(initialCam);
}
```

https://github.com/processing/p5.js/assets/39549290/3368e9f2-1cb5-4ce6-9b8e-f9c24e9e011f

In the case of setCamera(), even if you return to the original camera, the camera will move, so the starting point is not fixed, which is inconvenient. There may be other solutions, but I felt most comfortable using the equivalent of p5.Vector's set().

Also, p5.Camera's copy() is private and not open to users, so the specifications for copying camera data are poor, so I felt that it was necessary to improve it.

However, what we want to do here is not make the copy() function available to the user. I'll leave that up to those who are interested. I think this function set() is useful, so I would like to implement it.

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### Feature request details

The details are as follows:

```js
  /**
 * Copies information about the argument camera's view and projection to
 * the target camera. If the target camera is active, it will be reflected
 * on the screen.
 * This function expects both arguments and targets to have the same projection
 * mode. For example, if one is perspective, ortho, frustum, the other must also be
 * perspective, ortho, frustum in each case.
 *
 * @method set
 * @param {p5.Camera} cam source camera
 *
 * @example
 * <div>
 * <code>
 * let cam, initialCam;
 *
 * function setup() {
 *   createCanvas(100, 100, WEBGL);
 *   strokeWeight(3);
 *
 *   // Set the initial state to initialCamera and set it to the camera
 *   // used for drawing. Then set cam to be the active camera.
 *   cam = createCamera();
 *   initialCam = createCamera();
 *   initialCam.camera(100, 100, 100, 0, 0, 0, 0, 0, -1);
 *   cam.set(initialCam);
 *
 *   setCamera(cam);
 * }
 *
 * function draw() {
 *   orbitControl();
 *   background(255);
 *   box(50);
 *   translate(0, 0, -25);
 *   plane(100);
 * }
 *
 * function doubleClicked(){
 *   // Double-click to return the camera to its initial position.
 *   cam.set(initialCam);
 * }
 * </code>
 * </div>
 * @alt
 * Set up the camera and draw a plane and a box.
 * Operate the camera using orbitControl().
 * Double-click to return the camera to its initial state.
 */
  set(cam) {
    // Copies information about the camera's view.
    // At this time, if this camera is active, uMVMatrix will be updated
    // with this cameraMatrix.
    this.camera(
      cam.eyeX, cam.eyeY, cam.eyeZ,
      cam.centerX, cam.centerY, cam.centerZ,
      cam.upX, cam.upY, cam.upZ
    );
    // Copy the camera's projection matrix.
    for (let i = 0; i < 16; i++) {
      this.projMatrix.mat4[i] = cam.projMatrix.mat4[i];
    }
    // If this camera is active, update uPMatrix.
    if (this._isActive()) {
      for (let i = 0; i < 16; i++) {
        this._renderer.uPMatrix.mat4[i] = this.projMatrix.mat4[i];
      }
    }
  }
```

### PR DESCRIPTION
**Pull request by inaridarkfox4231**
Implement the set() function of p5.Camera.

This function copies the argument camera information to the target camera, just like p5.Vector's set().
The information to be copied is the view matrix and its parameters, projection matrix and its parameters, and cameraType.
There is no particular meaning in transferring the cameraType, but since this information is determined in a way related to how the projection is set, I thought it would be appropriate to copy it.
If the target camera is active, the renderer's view and projection matrices are updated with the same matrices.

Resolves #6238

## Example
[p5.Camera.set()_DEMO](https://editor.p5js.org/dark_fox/sketches/y0tTOjprQ)
```js
let cam, initialCam;

function setup() {
  createCanvas(400, 400, WEBGL);
  strokeWeight(3);

  // Set the initial state to initialCamera and set it to the camera
  // used for drawing. Then set cam to be the active camera.
  cam = createCamera();
  initialCam = createCamera();
  initialCam.camera(100, 100, 100, 0, 0, 0, 0, 0, -1);
  cam.set(initialCam);

  setCamera(cam);
}

function draw() {
  orbitControl();
  background(255);
  box(50);
  translate(0, 0, -25);
  plane(100);
}

function doubleClicked(){
  // Double-click to return the camera to its initial position.
  cam.set(initialCam);
}
```

https://github.com/processing/p5.js/assets/39549290/f760870b-24db-472d-8783-103c62b7b667

When double-clicked, the camera whose initial state is registered is set as the active camera by set(), and the screen state is reset. As it stands now, this requires resetting the initial state somehow. setCamera() cannot be used because the active camera will change. With this function, you can restore only the settings without changing the active camera.

#### PR Checklist

- [x] `npm run lint` passes
- [x] [Inline documentation] is included / updated
- [x] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Comment by inaridarkfox4231** [comment]
I'm tired of worrying about how to write code, so I decided to write it the way I like it.
Because what we want to do here is implement the function, not clean up the code.
My idea is that after it's all over, people who are interested can do whatever they want.

**Comment by inaridarkfox4231** [comment]
I don't use forEach, but there's no rule that I have to use it, so I wrote it whatever I wanted.

**Comment by inaridarkfox4231** [comment]
I wanted to create this function because I wanted to make it easier to write code for smooth camera switching.
Check out the demo below.
[p5.Camera.set_DEMO](https://editor.p5js.org/dark_fox/sketches/MjRX-2CSO)

https://github.com/processing/p5.js/assets/39549290/718b9384-d69e-4bb6-ac4d-1df3c4de43e5

In this demo, 4 cameras are prepared and can be switched by pressing a button.
When switching cameras, a certain function is used so that the camera changes smoothly. I'd like to implement this function someday, but I'm using set() internally, so I'll think about it after this function is implemented.

For that we need the first and last camera, and set() is used to populate that information. However, if only the attached camera is used, the assignment operation is actually sufficient and the set() is not necessary.

This demo allows the camera to be manipulated with orbitControl() after switching cameras. Therefore, setCamera() cannot be used. This is because the information of the prepared camera will be rewritten. Also, if you use substitution when preparing the starting camera, the starting camera will change, so substitution cannot be used. So set() is used effectively. set() is very useful for treating the camera as a data-only object.

If this kind of thing can be done without using set(), we don't need this function. I tried to explain the usefulness as much as possible, but I don't know if I did it well. If the implementation is allowed, please give me a review.

**Comment by inaridarkfox4231** [comment]
Thanks for review and merge! ('ω')
I have one more pull request left that I want to pass by 1.7.0, so I'll do my best...

**Comment by Qianqianye** [comment]
Thanks @inaridarkfox4231 for working on it and @davepagurek for reviewing it!

**Pull request merged**
