### PR TITLE
A way to verify downloads

### PR DESCRIPTION
**Pull request by akshay-99**
Changes:

Until now there was no way to verify functions that download something to the user's system. I went through the ['file-saver' module](https://github.com/eligrey/FileSaver.js/blob/master/src/FileSaver.js ) which is used in p5 to facilitate downloads and found that it uses `createObjectURL()` function which we can temporarily override in tests to capture the file that is just about to be downloaded. This makes unit testing for download functions possible, without the need to restructure the src function itself.

I have created a helper function in the tests `testWithDownload` which uses the above approach.

I added another helper function: `testUnMinified` , which when used, only runs that test on the unminified library. It is meant to be used for testing invalid arguments on the function.

I felt this was needed because `assert.validationError` is currently defined as, 
```js
assert.validationError = function(fn) {
  if (p5.ValidationError) {
    assert.throws(fn, p5.ValidationError);
  } else {
    assert.doesNotThrow(fn, Error, 'got unwanted exception');
  }
};
```
It would expect **no error** to be thrown when running for the minified version. But some p5 functions will naturally throw an error for wrong arguments when they try to perform operations which the passed arguments simply do not support. 

`testUnMinified` would make things much simpler.

This PR adds tests for:
- saveGif
- saveCanvas
- saveFrames
- saveStrings
- saveJSON
- writeFile
- downloadFile
- save
- saveTable

#### PR Checklist

- [x] `npm run lint` passes
- [ ] [Inline documentation] is included / updated
- [x] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/master/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/master/contributor_docs#unit-tests

### CODE REVIEW

**Comment by akshay-99** [comment]
As an example, I have tested for the filetype of the file that would be downloaded. This can be further extended to verify the contents as well

**Comment by limzykenneth** [comment]
Sounds like a good idea to me.

**Comment by akshay-99** [comment]
@limzykenneth Thanks. Sorry for the late reply I was caught up drafting the proposal. So I will update this PR to add tests for all download functions before I mark ready for review?

**Comment by limzykenneth** [comment]
@akshay-99 You can mark the PR as ready for review whenever you feel it is ready for review, ideally with tests but if not just make sure to make a note of it. If you need help working on this PR, just ask here and we'll see if we can help.

**Comment by fenilgandhi** [comment]
Yes, that is the way to test methods like this, even i have used similar method in some tests of `dom` module. Also, just a good habit, keep the habit of using `assert.deepEqual` instead of `assert.strictEqual`.

**Comment by akshay-99** [comment]
> Also, just a good habit, keep the habit of using assert.deepEqual instead of assert.strictEqual as strict equality is shallow.

Yes but wouldn't using it everywhere be an overkill? The rule I follow is strictEqual for everything I can compare with === (Number, string, etc) and deepEqual for everything else (objects and stuff)

I could use deepEqual everywhere but it just wouldn't feel right to me :see_no_evil: Also I guess it would be a little bit slower.

**Comment by akshay-99** [comment]
@limzykenneth So far I have added tests for `saveGif`, `saveStrings`, `saveJSON`, writeFile, `downloadFile` and `saveTable`. I think only `p5.prototype.save` remains, which I will do tomorrow. I have created a helper `testWithDownload` so that I don't have to repeat the overriding code.

Moreover I realised that since tests that use `assert.validationError` only make sense for the un-minified library where validation of parameters is enabled, some of these might fail when running on the minified library. If I pass incorrect arguments to a function with the un-minified script, I would expect a `ValidationError`. But in the minified script, since validateParameters is not enabled, the function could crash throwing some other exception due to the wrong arguments. It just so happens that the functions on which tests `assert.validationError` was used until now do not crash for wrong arguments.
For example, `p5.prototype.arc` is a function that won't crash for the wrong arguments' tests given [here](https://github.com/processing/p5.js/blob/master/test/unit/core/2d_primitives.js#L36), it just won't draw anything on the screen.

But p5.prototype.saveTable will crash when given wrong arguments.

So to avoid problems in the future I wrote another helper, `testUnMinified`, which when used will only run that test for the un-minified library.

**Comment by akshay-99** [comment]
@limzykenneth #4468 must be merged before I push tests for saveFrames here. The tests are ready but they may fail due to the race-condition we were talking about. Once 4468 is merged, I will push the tests for saveFrames here so that they can be checked by the CI

**Comment by akshay-99** [comment]
@limzykenneth @lmccart I think this is now ready to be reviewed. Tests for all download functions have been added

**Comment by limzykenneth** [comment]
Looks good to me. Thanks.

**Pull request merged**
