### PR TITLE
Merges in webgl geometry refactor

### PR DESCRIPTION
**Pull request by indefinit**
feature additions:
obj loader - loadModel()
more 3d and 2d primitives in webgl (ellipse, rect, triangle)
modularized p5.Geometry for ad hoc mesh creation.

### CODE REVIEW

**Comment by indefinit** [comment]
Forgot to add this note.  Upon merging in the geometry refactor branch I get this warning from Grunt:

Warning: for p5.ellipse() defined in src/core/2d_primitives.js:133, all overloads must be defined in the same file ("src/3d/primitives.js" !== "src/core/2d_primitives.js") Used --force, continuing.
Warning: Cannot read property 'project' of undefined Used --force, continuing.

For now, I've forced the grunt compilation but I'm wondering if anyone has a recommendation for structuring the overloaded methods from 2d/3d.

**Comment by indefinit** [comment]
It looks like the documentation comments are what's throwing the overloads warning.  Maybe I should just add a webgl flag to each overloaded method documentation?

**Comment by lmccart** [comment]
hey @indefinit wow what a ton of work, it looks great! a couple comments:

* can you remove `lib/addons/p5.dom.min.js` from the PR? it is listed in the .gitignore and shouldn't be included in the repo.
* regarding your question about documentation. the best way to do this would be rather than making an additional entry (like you have [here](https://github.com/processing/p5.js/pull/1370/files#diff-33cc0bccd71995d911c080eb1e185610R634)), modify the entry in the [top level definition](https://github.com/processing/p5.js/blob/master/src/core/2d_primitives.js#L152) to include additional parameters and signatures (so we end up with an entry similar to what we see in the [processing ref](
https://processing.org/reference/line_.html). recently, @toolness added functionality that supports the display of multiple signatures which should help make things more clear, info [here](https://github.com/processing/p5.js/wiki/Inline-documentation#additional-signatures).

other than that, all looks good to go!

**Comment by indefinit** [comment]
Ok thanks.  I'll work on this.  Question about _validateParameters.  Should I just delete this code in the p5.prototype methods since it's known to be disabled?

**Comment by indefinit** [comment]
So close to passing all checks.  Now Travis fails on: 1) src/typography/attributes.js textStyle documentation example #1 works:
     code took too long to execute

Any ideas?  I don't recall ever working on src/typography so I don't think the error is related to my refactor.

**Comment by lmccart** [comment]
hm good question about `_validateParameters`, @toolness what do you say?

is the test failing when you run grunt locally or just with the travis CI test? when I looked at the error log from travis, it looked like it passed on 3/4 different node builds. sometimes I notice that travis will randomly fail for one of the node versions, but then work again the next time the tests are run. I'm not sure what we need to do to fix this, but I usually just ignore it and things work out ok. :) ?

**Comment by toolness** [comment]
> hm good question about `_validateParameters`, @toolness what do you say?

I need to blog more about this, but my basic philosophy right now is to transparently validate the vast majority of parameters through an automated mechanism based on our yuidoc metadata like e.g. #1287, and to resort to hand-crafted, artisanal type-checking for functions with unusual type signatures like [`save()`](http://p5js.org/reference/#/p5/save). So I think that it's okay to just remove `_validateParameters` now!

**Comment by indefinit** [comment]
@lmccart yea build passes tests fine on grunt but fails in Travis.  I'll go ahead and ignore.  

@toolness sounds good to me.  I'll go into the 2d primitives and remove _validateParameters for now.  As soon as I remove and push those changes, we'll be good to go with the merge.  Woohoo!

**Comment by indefinit** [comment]
Sweet! It looks like all checks have passed.  @lmccart Should I merge or do you want to do it?

**Comment by lmccart** [comment]
go for it!

**Pull request merged**
