### PR TITLE
Add automatic labelling to issues

### LINKED ISSUE #5636: Should issues be automatically labelled for the appropriate area of p5.js
### Topic
I am proposing a GitHub Action to be employed to automatically label new issues based on which checkboxes are checked in the "relevant part of p5.js" section. This section is included in all issue forms except for the discussion form. 

image
image

The only reasons against this that I can think of are 
1. The difficulty of setting the system up
2. People may choose an irrelevant part of p5.js

The benefits are that 
1. It's easier to search for issues 
2. People don't have to manually assign labels.

### PR DESCRIPTION
**Pull request by stampyzfanz**
Resolves #5636

 Changes:

Issues are now automatically labelled as per the check boxes ticked in the issue form which all types of issues include other than discussion issues. Additionally, the issue form is reordered as requested by [Qianqianye](https://github.com/Qianqianye).

A prototype is [here](https://github.com/stampyzfanz/TestingGithubActions/issues) which works as expected. 

 Screenshots of the change:

image
image

### CODE REVIEW

**Comment by Qianqianye** [comment]
Thanks @stampyzfanz!  Would it be possible to match the checkbox and labels to the existing labels and areas? Like `Build Process`, `Friendly Errors`?

**Comment by stampyzfanz** [comment]
I have just updated the checkboxes to be more consistent with the steward sub-area list.
image

**Comment by Qianqianye** [comment]
Thank you @stampyzfanz for working on this ✨

**Comment by Qianqianye** [comment]
Hi @stampyzfanz. I was testing the auto labelling process in the issue #5741. It seems like the Area labels are not working properly. Wondering if you could share some thoughts on it. Thank you!

**Pull request merged**
