### PR TITLE
readability changes to argument in limit function.

### PR DESCRIPTION
**Pull request by AkashGutha**
readability changes to the limit function for better readability.

### CODE REVIEW

**Comment by lmccart** [comment]
I think this is somewhat confusing because the function name itself is already `limit`.

**Comment by AkashGutha** [comment]
Yes. It's confusing . Any other ideas ??

**Comment by lmccart** [comment]
you could use max, this is how it's documented in the ref for users.

**Comment by AkashGutha** [comment]
did the changes. @lmccart

**Comment by lmccart** [comment]
looks great, thanks!

**Pull request merged**
