### PR TITLE
Allow settings object for p5.Texture

### PR DESCRIPTION
**Pull request by aferriss**
This is a draft pr. See issue #5556 for more information.

#### PR Checklist

- [ ] `npm run lint` passes
- [ ] [Inline documentation] is included / updated
- [ ] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Comment by stalgiag** [comment]
I think this okay to add. I understand how it would be needed for libraries or advanced use-cases and it has no negative impact on current use.

**Comment by stalgiag** [comment]
Part of me wishes there was a little more clarity on the possible properties for a settings object but I am not sure that is needed since anyone who digs into the code enough to find this will likely know what these are already.

**Comment by aferriss** [comment]
Thanks! @stalgiag I'm happy to add a bit more context and documentation about possible properties in that object.

**Comment by aferriss** [comment]
@stalgiag Ok, updated the documentation. Let me know what you think!

**Comment by stalgiag** [comment]
Looks good! Thank you @aferriss

**Pull request merged**
