### PR TITLE
textToPoints() not handling line-breaks correctly

### LINKED ISSUE #5474: textToPoints() not handling line-breaks correctly
textToPoints() inserts a blank character instead of a line-break

For the string 'B\nA', text() (in white) handles linebreak correctly, while textToPoints() does not:

image

```js

// load font first

function setup() {
  createCanvas(400, 400);
  textFont(font, 100);
  pts = font.textToPoints('B\nA', 0, 0, 100, {
    sampleFactor: 0.4 // increase for more points
  });
  background(0);
  fill(255);
  noLoop()
}

function draw() {
  text('B\nA', 200, 200)
  pts.forEach(p => circle(200 + p.x, 200 + p.y, 3));
}
```

### PR DESCRIPTION
**Pull request by Decoy4ever**
resolves #5474

 Changes:

Since the issue was caused was related to a line-break, we have added code that identifies line-breaks in the text if it exists. So lines are split accordingly where a line-break exists. We also added code to identify tab ('\t') characters in these lines, and replaced them with 2 spaces. What this entails is that textToPoint() is now able to print new lines, in the sense of moving to a new line prior to print the next character.

 Screenshots of the change:

Screenshot 2023-05-27 at 9 35 15 am
Screenshot 2023-05-27 at 9 35 22 am

#### PR Checklist

- [x] `npm run lint` passes
- [ ] [Inline documentation] is included / updated
- [ ] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Comment by munusshih** [comment]
Hi @Decoy4ever, thank you for your wonderful answer.
I'm working on this issue as part of my GSoC project and will integrate this as a future version of p5! yay!
We decide to adopt most of your answer but instead of `y = y + fontSize`, it should be fixed as `y = y + this.parent._renderer._textLeading;` since sometimes the `textLeading()` might not equal as the `textSize()`.

**Comment by munusshih** [comment]
#6184

**Comment by limzykenneth** [comment]
@munusshih Instead of using the patch here in your own PR later, would you like to just review this PR and suggest changes necessary if you see any for this feature? So that @Decoy4ever would still be able to have their work here merged. Thanks.

**Comment by limzykenneth** [comment]
@Decoy4ever Thanks for filing this PR. Your changes here are incorporated into #6184 as per @munusshih so I'll close this PR in favor of #6184.

@all-contributors please add @Decoy4ever for code

**Pull request closed without merging**
