### PR TITLE
OrbitControl Update

### LINKED ISSUE #2497: WEBGL : make orbitControl() smoother and more continuous
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Feature enhancement details:

I think `orbitControl()` function in WEBGL mode should behave more like (or exactly like..) [this](https://threejs.org/examples/?q=text#webgl_buffergeometry_instancing2) sketch. As of right now, when user releases button after click, the camera position goes back to previous position instantly, which doesn't feel like desired behaviour.

### PR DESCRIPTION
**Pull request by AidanNelson**
Fixes #2497.

Adds persistence to `orbitControl()` and maintains y-axis up orientation. 

This change does the following:
- uses spherical coordinates to establish current camera position w/r/t center of sketch, adjust that position based on mouse movement and convert back to cartesian coordinates,
- makes adjustment persistent by applying those coordinates to rendererGL's `camera()` function which changes cameraMatrix,
- adds `cameraCenterX/Y/Z` properties to rendererGL to allow orbitControl about a center not at the origin.

### CODE REVIEW

**Comment by kjhollen** [comment]
thanks, Aidan! the default sensitivity here feels a little high to me (I can move through the entire range of motion just by moving the mouse a few pixels)—is that the expected behavior?

**Comment by AidanNelson** [comment]
I may have become used to it being a bit twitchy!  How does it feel now?  I lowered default sensitivity to 1/5th of what it was.

**Comment by kjhollen** [comment]
It's better but I think the older behavior (and the relationship of the sensitivity factor) was easier to understand. I think you could still do something like:

```
var deltaPhi = sensitivityY * (this.mouseY - this.pmouseY) / (this.width / 2);
```

which would be closer to the old behavior, which tracks the mouse at nearly 1:1. If it's weird having both x & y depending on the width, we could opt for the smaller of the two, so that it's possible to get the full range of rotation in both directions, even if the aspect ratio is a little funky. What do you think?

**Comment by AidanNelson** [comment]
Yes, it would be good to have a width/height dependent scale!  I'm not entirely sure why I changed that in the first place...  I added the smaller or width / height as the scale factor in this latest commit, which should allow at least 1 radian / ~60 degrees of rotation in each direction.  Does that feel alright? 

Also, while using the Chrome Device Toolbar on a touch device setting that orbitControl was jumping between positions, presumably because pmouseX/Y wasn't being updated except during touch events.   I will look into a workaround, unless resetting pmouseX/Y to current mouseX/Y at the beginning of each touchEvent might be more expected behavior with regard to touch events?   That way pmouseX/Y would either store the previous frame's mouseX/Y OR the current mouseX/Y, but never the mouseX/Y of 100, 200, etc. frames ago.

**Comment by mlarghydracept** [comment]
@AidanNelson This is super nitpicky but since you are already changing the manual test - can you get rid of the HTML that tells me to "press mouse to toggle the world"? It bothers me an abnormal amount. 

In more helpful news, I just tried out this persistent orbit control on a few different sketches and got satisfying results in all of them. Excited for panning and zooming :-P

**Comment by AidanNelson** [comment]
Yes, done!  And I will start a separate thread about whether/how pmouseX/Y should be updated with touch events.

**Comment by kjhollen** [comment]
This looks good to me, Aidan! Feels much better. It looks like the update accidentally undoes the fix for #2930—if you want to patch that back in, I think then we'll be ready for merge.

**Comment by AidanNelson** [comment]
Ok.  Neither axis should be inverted now!

**Comment by kjhollen** [comment]
Awesome! Thank you!

**Pull request merged**
