### PR TITLE
Fix long standing bug where load* functions could not use callbacks in preload()

### PR DESCRIPTION
**Pull request by Jared-Sprague**
Issue: https://github.com/processing/p5.js/issues/949

The problem was that the `decrementPreload()` function was getting pushed on the argument list for load functions in `_wrapPreload()` and when no success callback was passed to the load function `decrementCallback()` was assumed to be in the position of the success callback, but when a callback was passed in, decrementPreload would never get called.

### CODE REVIEW

**Comment by Jared-Sprague** [comment]
@lmccart This pull request includes unit tests and an example to demonstrate that it works

**Comment by lmccart** [comment]
hey @Jared-Sprague thanks for this! this definitely fixes the problem, but I feel a little unsure about repeating the same code lines in every function. is there a way to do this in just one place? either somewhere around [here](https://github.com/processing/p5.js/blob/master/src/core/core.js#L212) where preload is handled, or by making helper methods that get called in each loadX() function?

**Comment by Jared-Sprague** [comment]
@lmccart I don't think there is a way to fix this without modifying each load function, because decrementCallback *has* to be called inside the load function when in preload.  However I totally can extract the common lines from each load function into a helper method.  I'll do that now!

**Comment by Jared-Sprague** [comment]
@lmccart Ok check my last commit diff and let me know what you think!

**Comment by lmccart** [comment]
`if (typeof decrementPreload === 'function')`
this looks great. one super nitpicky suggestion, would it make sense to put this above check inside the `_getDecrementPreload()`, so that function either returns a pointer to the function or null? then you could just check in the individual functions `if (decrementPreload)`. does that seem right?

**Comment by Jared-Sprague** [comment]
@lmccart sounds fine to me! Stay tuned that will only take a minute.

**Comment by Jared-Sprague** [comment]
@lmccart Ok check it out.  Note, I still have to check that (callback !== decrementPreload) because when no callback is passed in decrementPreload will be in the callback position and we don't want to call decrementPreload twice.

**Comment by lmccart** [comment]
great, thank you!

**Comment by Jared-Sprague** [comment]
@lmccart whoo hoo! Thank you too!

**Pull request merged**
