### PR TITLE
Create contributor_guidelines.md placeholder for spanish translations

### PR DESCRIPTION
**Pull request by holomorfo**
Start file for contributor guidelines translations for Spanish

#### PR Checklist

- [X] `npm run lint` passes
- [X] [Inline documentation] is included / updated
- [X] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Comment by Qianqianye** [comment]
Hi @holomorfo, please tag me if this is ready to be merged. Thanks!

**Comment by holomorfo** [comment]
> Hi @holomorfo, please tag me if this is ready to be merged. Thanks!

its still in progress, thank you, will tag you when its ready.

**Comment by Qianqianye** [comment]
Hi @holomorfo, are we still actively working on this PR after the merge of #6895?

**Comment by holomorfo** [comment]
hi @Qianqianye this PR is no longer needed, will closed it, thanks

**Pull request closed without merging**
