### PR TITLE
Converted docs/documented-method.js to ES6

### PR DESCRIPTION
**Pull request by abhinavsagar**
Part of [#3758](https://github.com/processing/p5.js/issues/3758)

### CODE REVIEW

**Comment by abhinavsagar** [comment]
@stalgiag Should the codebase itself be converted to ES6 ?

**Comment by stalgiag** [comment]
Hi @abhinavsagar thanks for the offer but most of this conversion was handled by #3874. That said there will likely be further slight modifications that might need help. Feel free to follow open issues such as #3877 and #3875 to see if there are any new todos about ES6 conversion.

**Comment by stalgiag** [comment]
I think that #3877 in particular is relevant to this particular PR. Definitely the change from `var` will make sense but we may use `const` instead of `let` for this type of variable.

**Comment by abhinavsagar** [comment]
Thanks. I will go through the open issues.

**Pull request merged**
