### PR TITLE
Add support for csscolor strings in p5.Color

### PR DESCRIPTION
**Pull request by kadamwhite**
This provides an implementation for #222, and additionally adds support for `rgb(r,g,b)`, `rgb(r%,g%,b%)`, `rgba(r,g,b,a)`, and `rgba(r%,g%,b%,a)` CSS color strings. This needs review, as there may be room for improvements to the efficiency of the code and it definitely adds some weight (taking the same approach both d3 and jQuery-Color do, we include a dictionary of named CSS color values). I would like to refactor much of this logic into `color.___` modules, but I am interested in feedback on this logic in situ.

No support is currently provided for hsl() CSS color strings.

### CODE REVIEW

**Comment by lmccart** [comment]
This is fantastic, excited to get this in there! Would you add a few notes to the documentation for the color functions noting this option?

**Comment by kadamwhite** [comment]
@lmccart Absolutely, I will add that documentation.

**Comment by kadamwhite** [comment]
@lmccart I've added docs for Color, fill, background and stroke. Any others I should hit? I also clarified in the docs that fill, stroke & color can all take a p5.Color instance, as it seemed that was the case. If any further changes are needed, please let me know and I'll address ASAP.

**Comment by lmccart** [comment]
ahh excited to be merging this in! i think you hit them all but if i find any others i'll let you know.

**Pull request merged**
