### PR TITLE
Fix to Issue #5462

### PR DESCRIPTION
**Pull request by dhowe**
fix to #5462 - remove index check from p5.Font.isSpace() and fix broken tests

### CODE REVIEW

**Comment by limzykenneth** [comment]
I'm happy to just remove the commented out parts of this PR entirely since we will still have a record of changes in git. In any case we can tentatively merge this for now and keep an eye out if anything somehow doesn't work after this.

**Comment by dhowe** [comment]
it occurs to me that we may need to handle other types of whitespace in that function, let me do a few more tests before we merge

**Comment by outofambit** [comment]
sounds good! @dhowe would you re-request a review when this is ready to look at again?

**Comment by dhowe** [comment]
ok with spaces and tabs,  can be merged as is

**Comment by limzykenneth** [comment]
@dhowe I'm not seeing new commits? Or there's no new commits for now?

**Comment by dhowe** [comment]
no new commits for now, this should be working as expected

**Review by outofambit — APPROVED** [review]
looks good to me!

were the `console.log`s in the tests here causing problems, or is that cleanup?

**Comment by dhowe** [comment]
> were the console.logs in the tests here causing problems, or is that cleanup?

just cleanup

**Comment by limzykenneth** [comment]
I'm going to merge this then. If any problems with it pops up we'll know where to look. Thanks @dhowe

**Pull request merged**
