### PR TITLE
Resolves #4687 : Uncaught TypeError in createColorPicker() 's color() if initialised without parameter

### LINKED ISSUE #4687: Uncaught TypeError in createColorPicker() 's color() if initialised without parameter
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [x] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: v0.10.2 February 29, 2020 
- Web browser and version: Google Chrome 83.0.4103.116
- Operating System: Manjaro Linux
- Steps to reproduce this:

If `createColorPicker()` is initialised without passing a `value`, and then `.color()` is called on it's object, it throws the following error: `p5.js:72972 Uncaught TypeError: Cannot read property 'mode' of undefined`

maim-1594566218

The `value` parameter is optional as [per the reference](https://p5js.org/reference/#/p5/createColorPicker), but the code doesn't work properly without that property.

```js
let c;
function setup(){
    createCanvas(400,400)
    c = createColorPicker();
}

function draw(){
    background(c.color()) // Causes error
}
```

### PR DESCRIPTION
**Pull request by haideralipunjabi**
Resolves #4687

 Changes:

Adds a check for `value` parameter, and skips accessing it's properties if `value` is undefined.

### CODE REVIEW

**Comment by stalgiag** [comment]
Hi welcome and thank you for the contribution!

This PR isn't passing the automatic linting tests. Before submitting a PR it is best to make sure that your code passes the eslint you can test this by running `npm run grunt` locally in your development environment. It looks like the spacing with your added conditional is a bit wrong. You can most likely run `npm run lint:fix` to automatically fix. Feel free to @ me if you are still having trouble.

**Comment by haideralipunjabi** [comment]
OK I will fix it

**Comment by haideralipunjabi** [comment]
I believe it should work now :smile:

**Comment by stalgiag** [comment]
Great thanks for contributing!

@all-contributors please add @haideralipunjabi for code

**Pull request merged**
