### PR TITLE
automatically add method references to constant docs pages

### PR DESCRIPTION
**Pull request by Spongman**
on the docs pages for enumerated constants, add a list of links to those methods that take those constants as parameters.

image

### CODE REVIEW

**Comment by Spongman** [comment]
i have no idea why those are failing - this PR doesn't change those files. maybe some bad interaction between eslint and travis?

**Comment by Spongman** [comment]
Oh thanks!! I'll fix these in a mo.

**Comment by lmccart** [comment]
very cool

**Comment by lmccart** [comment]
@Spongman this test is failing for me, any ideas?
I also noticed that the changes in this PR seem to go against the lint check preferences, am I missing something?
screen shot 2017-12-09 at 12 40 00 pm

**Pull request merged**
