### PR TITLE
added describe() to all 3d reference examples

### LINKED ISSUE #5705: Add describe() to all 3D related examples in documentation
### Increasing Access

As it is already present in a number of other examples, continuing to add describe() to examples is a good opportunity to make the documentation more accessible and also raise the visibility of describe() to encourage more use. 

### Most appropriate sub-area of p5.js?

- [X] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [X] Other (specify if possible)

### Feature enhancement details

This will consist of editing the reference examples of each method to contain describe() with descriptive text. I'll assign this task to myself and will be focusing on any 3D related methods as that is my focus for GSOC 2022.

### PR DESCRIPTION
**Pull request by aceslowman**
Resolves #5705

Changes:
all reference examples for 3d methods now use describe()

#### PR Checklist
- [x ] `npm run lint` passes

### CODE REVIEW

**Comment by aceslowman** [comment]
@kjhollen Moved all describe() calls into setup and now all tests are passing locally!

**Review by kjhollen — APPROVED** [review]
Looks good to me! I realize that this commit is just going with what we already have for the alt text. I think some of these could probably be improved, to focus more on what the user would see and less on describing the functionality of the code—let's put some time on your schedule to revisit this summer @aceslowman, as you update the 3D examples.

**Comment by kjhollen** [comment]
congrats on your first commit @aceslowman!! 🎉

**Comment by Qianqianye** [comment]
Congrats on your first commit @aceslowman ✨!

**Pull request merged**
