### PR TITLE
Noting that the p5.js number generator is only sudo-random

### PR DESCRIPTION
**Pull request by thecodingcookery**
In the example of the random function I noted that the random number generator is only sudo-random.

### CODE REVIEW

**Comment by Qianqianye** [comment]
Thank you! As a reminder, an issue needs to be opened before a pull request is opened, then you can tag the issue in the pull request. You can read more about it in the [GitHub Issue Flow](https://github.com/processing/p5.js/tree/main/contributor_docs#github-issue-flow). This is necessary for tracking development and keeping discussion clear. Thanks!

**Comment by thecodingcookery** [comment]
Sorry, I thought that something as small as this would not need a github issue. I will try to keep this in mind!

**Comment by Qianqianye** [comment]
Please go ahead and open an issue @thecodingcookery. Thank you!

**Comment by limzykenneth** [comment]
I think in this case it is not very important to note that this is pseudorandomness as to humans it will be indistinguishable from true randomness and it's not being used for cryptographic purposes.

Also to nitpick a bit 😝, the spelling should be `psuedo` instead of `sudo`.

**Comment by Qianqianye** [comment]
I will close this PR for now for organizational purpose, and please feel free to open a new PR after an issue is opened. Thank you!

**Pull request closed without merging**
