### PR TITLE
#6022 Issue:Update light.js

### LINKED ISSUE #6022: Objects with ambient material only show color using ambientLight
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

_No response_

### Web browser and version

_No response_

### Operating System

_No response_

### Steps to reproduce this

If this is intentional, it is not explained in the online reference. specularMaterial shows color.

### Steps:
1. Create WEBGL canvas
2. Create a camera
3. Make a colored ambientMaterial(r, g, b)
4. Make a white directionalLight(x)
5. Only grayscale visible on 3D shapes.

### Snippet:

```js

let cam
function setup() {
	createCanvas(windowWidth, windowHeight, WEBGL);
	
	cam = createCamera()
	camera(0, -100, 300)
}

function draw() {
	background(230);
	let ls = 255
	ambientMaterial(0, 255, 0)
	directionalLight(ls, ls, ls, 0, -100, -300)
	rotateY(millis()/2000)
	box(50)
}

```

### PR DESCRIPTION
**Pull request by nikhilhvr**
Resolves #6022 

 Changes:
Added a new example in light.js that example made to showcase Objects with ambient material only show color using ambientLight.

I tested the following code:

 ```
 let cam
  function setup() {
  createCanvas(100, 100, WEBGL);
  // The camera will automatically rotate
  
  cam = createCamera()
  
  // The camera will move on the
  camera(0, -100, 300)
  }

  function draw() {
 	background(230);
 	let ls = 255
 	ambientMaterial(0, 255, 0)  //Green Material
 	directionalLight(ls, ls, ls, 0, -100, -300)  //White Light
 	rotateY(millis()/2000)
 	box(100)
  }

```

#### PR Checklist

- [ ] `npm run lint` passes
- [ ] [Inline documentation] is included / updated
- [ ] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Comment by Qianqianye** [comment]
Thanks @nikhilhvr for working on it. While we are waiting for @davepagurek to review the code, could you fix the trailing spaces problem? You can read more details about it in the [testing details](https://github.com/processing/p5.js/actions/runs/4337211689/jobs/7579023319).

**Comment by davepagurek** [comment]
Sorry for the delay, busy week over here 😅 I left a comment on the issue with one more suggestion on how to show the effect of either full ambient light or no ambient light within the same example. A slider would also work as opposed to using the mouse position, but I think as long as we can show the difference between `ambientLight`'s presence or absence somehow then we're good!

It looks like the linting test is still failing, but this time due to using tabs instead of two spaces.

**Comment by davepagurek** [comment]
Hi, looks like tests are failing due to code formatting:

```
Running "eslint:source" (eslint) task
/home/runner/work/p5.js/p5.js/src/webgl/light.js:75:3: Trailing spaces not allowed. [Error/no-trailing-spaces]
/home/runner/work/p5.js/p5.js/src/webgl/light.js:83:27: Trailing spaces not allowed. [Error/no-trailing-spaces]
```

In addition to removing the spaces at the ends of lines 75 and 83, could I get you to:
- de-indent `function` on line 80 so it matches line 76
- add a space before the `{` on lines 76 and 80

That way we can keep the formatting of all our examples consistent. Thanks!

**Comment by davepagurek** [comment]
Thanks for those updates! Looks like there's still one space at the end of line 82 we need to take out for the linter to pass:
```
Running "eslint:source" (eslint) task
/home/runner/work/p5.js/p5.js/src/webgl/light.js:82:27: Trailing spaces not allowed. [Error/no-trailing-spaces]
```

**Comment by nikhilhvr** [comment]
Thanks, @davepagurek guiding me at each and every step.

**Pull request merged**
