### PR TITLE
Fix pInst in p5.Graphics

### PR DESCRIPTION
**Pull request by zenozeng**
`this` is `p5.Graphics`, however, `p5.Renderer` should take pInst:
```javascript
p5.Renderer = function(elt, pInst, isMainCanvas) 
```

### CODE REVIEW

**Comment by lmccart** [comment]
thanks @zenozeng. did this come up for you as a problem? I seem to recall there was a reason the pInst wasn't passed through, but I may be misremembering.

**Comment by zenozeng** [comment]
p5.Renderer accept pInst as its 2nd param: 
https://github.com/processing/p5.js/blob/a79920c8461d291f67345408952cd48e9811748c/src/core/p5.Renderer.js#L18

In p5.prototype.createCanvas, we use this, because this here is instance of p5.
https://github.com/processing/p5.js/blob/a79920c8461d291f67345408952cd48e9811748c/src/core/rendering.js#L92

Howerer, in p5.Graphics, this is instance of Graphics, not instance of p5.
https://github.com/processing/p5.js/blob/a79920c8461d291f67345408952cd48e9811748c/src/core/p5.Graphics.js#L41

**Comment by zenozeng** [comment]
Using wrong this will cause this issue: https://github.com/zenozeng/p5.js-svg/issues/86

Some methods (like p5.prototype.textSize) of p5 requires pInst._setProperty, this is not provided by p5.Graphics.
```JavaScript
p5.prototype.textSize = function(s) {

  if (arguments.length) {

    this._setProperty('_textSize', s);
    this._setProperty('_textLeading', s * constants._DEFAULT_LEADMULT);
    return this._graphics._applyTextProperties();
  }

  return this._textSize;
};
```

**Comment by lmccart** [comment]
aha got it, thanks!

**Pull request merged**
