### PR TITLE
p5.sound 1.0.1

### PR DESCRIPTION
**Pull request by therewasaguy**
# Changes:
Update p5.sound library to include changes from these versions:

https://github.com/processing/p5.js-sound/releases/v1.0.1
https://github.com/processing/p5.js-sound/releases/v1.0.0

## Bug Fixes
* Fix drywet function bug https://github.com/processing/p5.js-sound/pull/606
* Fix function name in documentation processing/p5.js-sound#603
* Fix repeat initialization of audioWorklet processing/p5.js-sound#593
* Fix issue with p5.Score that prevented parts from being passed as argument processing/p5.js-sound#543
* Fallback when AudioWorklet buffer array length is zero
 processing/p5.js-sound#542
* Remove extra callbacks for SoundFile cue
 processing/p5.js-sound#449
* Fix abnormal behaviour of audio output in p5.signal example section
  processing/p5.js-sound#476
* Fix error while playing sound through `p5.soundFile.play()` method
 processing/p5.js-sound#542

## Infrastructure Improvements
* Library is re-written in ESM ( ECMASCRIPT MODULES).
* Audio Nodes are written as `Class` style rather than being  written as `function` style.
* Library using features of es6 like `let` , `const` keywords and many other es6+ features.
* Testing architecture has been made more clean and robust.
* All above listed improvements are part of [Divyanshu's](https://github.com/endurance21) GSOC-20 Project , more details can be found in his [wrap-up-post](https://github.com/endurance21/GSOC-20-WrapUp).
* Improvements in pre-commit-hook action  processing/p5.js-sound#574

## Documentation Improvements
* Fixed broken anchor tags in p5.Audioln
 processing/p5.js-sound#450
* Fixed typo  in p5.fft documentation
  processing/p5.js-sound#433
* Added documentations for P5.oscillator APIs
 processing/p5.js-sound#420
* Improved documentation of p5.soundloop
  processing/p5.js-sound#437
* Fixed broken links in p5.panner3D documentations
 processing/p5.js-sound#465
* Typo improvements in p5.soundloop reference
 processing/p5.js-sound#557

## Deprecation and Renames
* Renames: outputVolume method and Main class processing/p5.js-sound#610
* We have deprecated functionality in an effort to focus the API
  * p5.Signal
  * p5.SoundFile.processPeaks

#### PR Checklist

- [x] `npm run lint` passes
- [x] [Inline documentation] is included / updated
- [x] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Comment by therewasaguy** [comment]
I've tried to document the process of releasing the p5.sound add-on library at https://github.com/processing/p5.js-sound/wiki/Releasing-a-new-version-of-p5.sound-library, but are there steps that I'm missing?

**Comment by outofambit** [comment]
thank you @therewasaguy!!!

**Comment by therewasaguy** [comment]
hey, thanks, @outofambit ! I'm looking at the guide to releasing a new version of p5.js https://github.com/processing/p5.js/blob/main/contributor_docs/release_process.md

is this something I should do? It looks like anyone can do it, tho I've not done this process before.

If/when we're at a good place for a new release of p5.js, I hope we can get the new version of p5.sound out there!

**Comment by outofambit** [comment]
@therewasaguy i'm excited to get the new p5 sound out to everyone too! there's a couple gotchas with the release process right now, would it be alright if i took care of it this time? i think we'll be ready in about 2 weeks from now! 🚀

**Comment by therewasaguy** [comment]
ah, good to know! I would be so grateful, @outofambit, as would the many people asking for a new release of the sound library specifically. Glad it can be included and thank you for offering to navigate those gotchas to make it happen!!

**Comment by limzykenneth** [comment]
@outofambit Feel free to ping me if you have problems with the release. :smiley:

**Pull request merged**
