### PR TITLE
Fixed select() issue with existing dropdown

### PR DESCRIPTION
**Pull request by JimishF**
As I mentioned in #1864, Issue has been resolved via assigning those methods of dropdown ( which were coming from `createSelect()` ) to selected dropdown, after wrapping in to p5.element ( inside `wrapElement()` ).

### CODE REVIEW

**Comment by JimishF** [comment]
Can anyone help me with this failing checks ?

**Comment by lmccart** [comment]
have you run `npm install`?

**Comment by JimishF** [comment]
Yes definitely.

**Comment by JimishF** [comment]
I did commit npm-debug.log after reading this.
image

**Comment by JimishF** [comment]
Trying new PR with new pull.

**Comment by limzykenneth** [comment]
@JimishF That message is if you think the problem is with Travis itself and you intend to submit a bug report to them, they expect you to include the debug log.

**Comment by JimishF** [comment]
Oh okay. Got it. I dont think the issue was with travis, because I was having a bunch of errors since after first time I ran grunt. Everything worked smoothly once after reproceduring things back from new fork.

**Pull request closed without merging**
