### PR TITLE
added lights function from processing

### PR DESCRIPTION
**Pull request by IceDune**
added lights method for a feature request.
issue #2645 .

### CODE REVIEW

**Comment by IceDune** [comment]
just asking but, is there any change i need to do or is the feature not required?

**Comment by kjhollen** [comment]
hi @IceDune, thanks for submitting this! I need to take a closer look at this, but a couple things I noticed at a glance:

- the `lights()` method here is defined for p5.RendererGL prototype but not on the p5 prototype. it will need to be added there too to ensure that it's accessible in the global scope—it can just refer to what you've written here. I think there are some good examples for how to do this in material.js
- can you add an example to the test/manual-test-examples folder? this would let other devs verify that the code is working as intended
- and add an example to the documentation itself, so that it will show up in the p5 reference :)

**Comment by IceDune** [comment]
@kjhollen , Sure!

**Comment by kjhollen** [comment]
Hi @IceDune, can you let me know if you're interested in making the updates requested here? or if you're busy, would it be ok if I worked on this a bit? thanks!

**Comment by IceDune** [comment]
Hi @kjhollen , i'm sorry i was a bit busy, but could i work on this. i'll try to fix it as soon as possible. thanks!

**Comment by IceDune** [comment]
@kjhollen , for the tests, in which folder under manual-test-examples should i add them to? 
Is it webgl/camera? and for testing this function, just calling `lights()` in `draw()` is enough right?
thank you.

**Comment by kjhollen** [comment]
thanks for the updates @IceDune! for manual-testing-examples I think you can make a new folder in webgl/lights and yes, all it needs to do is show `lights()` in `draw()` and include a couple shapes we can see it working.

**Comment by IceDune** [comment]
hi @kjhollen , i've added the tests, is there any change i need to apply in them? and please let me know how to add the documentation. thank you very much!

**Comment by kjhollen** [comment]
thanks @IceDune! I'll give this a more detailed read soon, but here's a guide on how to generate the inline documentation / examples that will go with the function https://github.com/processing/p5.js/blob/master/developer_docs/inline_documentation.md

**Comment by IceDune** [comment]
hi @kjhollen thank you for telling me how to write the documentation. please let me know if the test I've written is correct so that i can add it as an example. thanks a lot!

**Comment by IceDune** [comment]
hi @kjhollen , may i know if there are any changes that need to be done. thank you.

**Comment by stalgiag** [comment]
Hi @IceDune I am closing this for now so that others can take a crack at it. If you still want to work on it please post in #2645. Otherwise, just want to make sure others get a chance.

**Pull request closed without merging**
