### PR TITLE
Fix issue with orbitControl rotating inversely on the X axis

### PR DESCRIPTION
**Pull request by dekmm**
Addressing issue explained in #2930

### CODE REVIEW

**Comment by dekmm** [comment]
Not sure if the inverted rotation was intented, but I would like to add a flag so the user can choose between normal and inverted rotation.

**Comment by dekmm** [comment]
I guess I never noticed the different rotation speeds since I tested the change on a canvas of equal width and height. Must've slipped my mind that I made the change.

I'm assuming the change isn't that drastic unless a user uses some weird resolution for the canvas such as 1000x100 or has OCD and these little inconsistencies drive him crazy :P but I'll test it out and change it back if necessary.

**Comment by kjhollen** [comment]
@dekmm one context I was thinking of was using the browser's developer console, which usually results in a screen much wider than tall because the dev panel takes up the bottom half of the screen. I'm often doing this to run tests or debug.

**Comment by Spongman** [comment]
I wonder if it behaves differently if the canvas is large vs if it is small?  I think users might expect the turning rate to be related to the 'size' of the canvas, but also in a way that the horizontal & vertical turning rates are the same.

(I have a feeling that getting this exactly right would depend on inspecting the camera matrix, but on the other hand, I think that assuming a square pixel aspect ratio would probably be sufficient.)

**Comment by kjhollen** [comment]
thanks for updating this. I just merged #2962 which included a similar fix + more features, so I'm going to close this, but the update was right on. :)

**Pull request closed without merging**
