### PR TITLE
adjusted value of pointSize when passing to shader to fix issue num #…

### LINKED ISSUE #4867: Monitor scale problem.
- screen scale problem.

Hi.
I'm using a Windows 7 Ultimate 64bit PC with the latest Chrome version.
It's quite common to use at least a 125 % 'scale' screen setting for medium to larger screen resolutions.
And they can be changed rapidly to test. But if you leave the normal 'browser' zoom at 100% the sketches are not playing properly.
For example in [this sketch](https://www.openprocessing.org/sketch/984401), the arrows points are not drawn when the browser zoom setting is not set to 80%. Only lines.  
I have added a temporary workaround, asking once to adjust the zoom in an alert.
[Another sketch ](https://www.openprocessing.org/sketch/878781)also doesn't play or well when zoom isn't correct

### PR DESCRIPTION
**Pull request by AliLordLoss**
resolves #4867

### CODE REVIEW

**Comment by lmccart** [comment]
thanks @AliLordLoss!

**Comment by EmmanuelPil** [comment]
> thanks @AliLordLoss!

Dear Lauren.
Why was this topic closed, while it still wasn't solved?
Regards Emmanuel

**Comment by lmccart** [comment]
it was just resolved with this pull request. it will be in the next build

**Comment by EmmanuelPil** [comment]
Great! Thank you.

**Pull request merged**
