### PR TITLE
Add @jnsjknn to contributors

### PR DESCRIPTION
**Pull request by jnsjknn**

### CODE REVIEW

**Comment by montoyamoraga** [comment]
hi @jnsjknn we don't do this manually, we use a bot, i can do it for you if you let me know what issue / pull request / contribution i can refer to your contribution, best!

**Comment by jnsjknn** [comment]
Hi @montoyamoraga,

I apologize. I misunderstood the instructions saying I should add myself here to create a PR.

I'm contributing to #956

**Comment by montoyamoraga** [comment]
@all-contributors please add @jnsjknn for design

**Comment by montoyamoraga** [comment]
this PR is closed, done with #5097 instead

**Pull request closed without merging**
