### PR TITLE
example for noLoop

### PR DESCRIPTION
**Pull request by hackertron**
this PR is regarding this issue : https://github.com/processing/p5.js/issues/1954

specifically for :  https://p5js.org/reference/#/p5.MediaElement/noLoop

please review it !!

### CODE REVIEW

**Comment by lmccart** [comment]
I think it's confusing to have both stop() and noLoop() in there. Can this example instead just load a sound file, begin it playing with loop(), then call noLoop() when the mouse is clicked?

**Comment by hackertron** [comment]
Sure will update in few minutes !!

**Comment by hackertron** [comment]
Please review again :) 
this time the setup() will just create audio and will loop it . once user clicks on canvas noLoop() will be called .

Thanks !!

**Comment by lmccart** [comment]
looks good but for some reason the test of this is failing. have you run `grunt`? any ideas why it's failing?

**Comment by hackertron** [comment]
No i haven't ran grunt on it . I will run it ( will look instructions ) . One possible reason could be maybe my repo is not updated , it's some commits behind !!

**Comment by lmccart** [comment]
thank would be great thanks! you may need to run `npm install` after you pull the latest. some new dependencies have been added recently.

**Comment by hackertron** [comment]
Hey , i have updated my repo and did npm install too but the check is still failing . I also git cloned latest git of p5.js ran grunt ( 359 test cases) it passed all of them , once i added my piece of code it failed  ( 1 test case failed , that was mine ) . Still no idea what i am doing wrong . 

Only change i am doing is 

`**
   * Set 'loop' to false for an HTML5 media element. Element will stop
   * when it reaches the end.
   *
   * @method noLoop
   * @return {Object|p5.Element}
   * @example
   * <div><code>
   * //Clicking the canvas will stop the audio loop
   * //we will store the p5.MediaElement
   * //object in here
   * var ele;
   *
   * function setup() {
   *  //Here we create a p5.MediaElement object
   *  // using the createAudio() function.
   *  ele = createAudio('assets/lucky_dragons_-_power_melody.mp3');
   *  ele.loop();
   *  background(200);
   *  textAlign(CENTER);
   *  text("Click to stop!", width/2, height/2);
   * }
   *
   * function mouseClicked() {
   *  //here we test if the mouse is over the
   *  //canvas element when it's clicked
   *  if(mouseX >= 0 && mouseX <= width &&
   *     mouseY >= 0 && mouseY <= height) {
   *     background(200);
   *    ele.noLoop();
   * }
  * }
  *
  * </code></div>
  */`

**Comment by hackertron** [comment]
Fixed the issue . the problem was that in function setup() , i was calling ele.loop() or ele.play() .

**Comment by lmccart** [comment]
awesome thank you!

**Pull request merged**
