### PR TITLE
added inline examples for Table

### PR DESCRIPTION
**Pull request by molleindustria**
Probably an overkill but some methods are not too straightforward.

### CODE REVIEW

**Comment by lmccart** [comment]
awesome! can you explain what's happening with the gruntfile change?

**Comment by molleindustria** [comment]
I was just told to add it during setup or troubleshooting. Probably unnecessary?

**Comment by workergnome** [comment]
That addition to the grunt file means that documentation is rebuilt on code changes while running in `grunt watch`.   I think that it's probably a worthwhile change.   It might get refactored when #706 hits, but for now I might suggest leaving it in?

**Comment by lmccart** [comment]
ah thanks @workergnome, will leave it in.

**Pull request merged**
