### PR TITLE
fromAngle length parameter, 3d fromAngles

### PR DESCRIPTION
**Pull request by Spongman**
- add optional `length` parameter to `p5.Vector.fromAngle()`
- update `fromAngle()` sample to use it,
- add 3d  `p5.Vector.fromAngles()` + sample

### CODE REVIEW

**Comment by lmccart** [comment]
@Spongman can you explain the decision to add the optional length param here? is it needed for the 3D version of this method?

**Comment by Spongman** [comment]
No, it's not related to the 3D version. It just extends fromAngle() to cover the entire plane with polar coordinates instead of just the unit circle - making it useful in many more situations.

**Comment by lmccart** [comment]
yup makes sense to me. thanks!

**Comment by lmccart** [comment]
@Spongman I forgot about the setMag() function as mentioned by @iridule here https://github.com/processing/p5.js/pull/2447#issuecomment-354376498. i am feeling that it makes sense to keep the api more simple and keep setMag() and fromAngle() separate, rather than duplicating the functionality of setMag() in fromAngle(). are you ok this?

**Pull request merged**
