### PR TITLE
Wiki guide test

### PR DESCRIPTION
**Pull request by ChrisJohnRyan**
Additional benchmark for testing p5 sin and Math.sin to validate wiki edits

### CODE REVIEW

**Comment by lmccart** [comment]
thanks for this, sorry for the delay. which wiki page contains the edits?

**Comment by ChrisJohnRyan** [comment]
@lmccart linking you back to the original thread - https://github.com/processing/p5.js/issues/2339

I believe that this is the page https://github.com/processing/p5.js/wiki/Benchmarking-p5.js

**Comment by lmccart** [comment]
ah got it thanks! i resolved the conflicts, if you can add these into your PR we can merge.

**Comment by lmccart** [comment]
ah ok thanks!

**Pull request merged**
