### PR TITLE
make 'rotate' default to Z-axis

### PR DESCRIPTION
**Pull request by Spongman**
prevents 'rotate()' from crashing when not passed an axis in WEBGL mode.

### CODE REVIEW

**Comment by Spongman** [comment]
@shiffman ran into this bug during his live stream.

**Comment by mlarghydracept** [comment]
This is good!  While you are at it could you add a check to see if the user passed no arguments and log a more informative error to the effect of "The function rotate() requires at least 1 argument, the number of radians to rotate"?

Just want to avoid people getting the cryptic error that @shiffman got [over here](https://github.com/processing/p5.js/issues/2351).

**Comment by Spongman** [comment]
i already have a PR pending that improves the parameter validation stuff. i don't want to add a whole bunch of ad-hoc validation that would just be obsoleted when that's merged...

**Comment by shiffman** [comment]
Thank you for working on this!

**Pull request merged**
