### PR TITLE
Fix the Array Comparison bug in outputs.js

### PR DESCRIPTION
**Pull request by nikhilkalburgi**
Signed-off-by: nikhilkalburgi <nikhilkalburgi19@gmail.com>

Resolves: #6660

#### PR Checklist

- [x] `npm run lint` passes
- [ ] [Inline documentation] is included / updated
- [ ] [Unit tests] are included / updated

### CODE REVIEW

**Review by ayushanand308 — COMMENTED** [review]
Looks good to me but this might fail if order of properties is different in two arrays even if  though both might be equal.

**Comment by nikhilkalburgi** [comment]
Hi @ayushanand308,
What if we sort them and check?

` JSON.stringify(this.ingredients.shapes[f].slice().sort()) !== JSON.stringify([include].slice().sort()) `

This will create a **copy** , **sort** then **stringify** to compare

**Comment by limzykenneth** [comment]
@nikhilkalburgi That will be very inefficient and considering this will run on every frame, may significantly impact performance if the drawings get complex enough.

**Comment by nikhilkalburgi** [comment]
Hi @limzykenneth,
 Do you think that the initial condition is necessary as it always returns true? How can it get resolved?

**Comment by limzykenneth** [comment]
In the subsequent for loop there is already a check for existence of the element in the list so the check before that is either not needed (ie. be an `else` instead of `else if` or be something that can be completed very quickly. I think for this case not having that earlier check should be fine and is how is has worked until now effectively. The loop can be optimized a bit by breaking early as well.

**Comment by HusainModiwala** [comment]
maybe here we can use isEqual function of lodash library to compare them.

**Pull request closed without merging**
