### PR TITLE
Implements shuffle(arr, [bool])

### PR DESCRIPTION
**Pull request by GoToLoop**
https://github.com/lmccart/p5.js/issues/513
https://github.com/lmccart/p5.js/tree/master/src/data/array_functions.js

Randomizes the order of the elements of an array using "Fisher-Yates Shuffle Algorithm".
By default, passed array argument isn't modified, unless setting a non-falsy 2nd parameter too.
Otherwise, a shuffled **slice()** shallow clone array is returned.

### CODE REVIEW

**Comment by GoToLoop** [comment]
Test run for correctness:  :P

```js 
 /**
   * Randomizes the order of the elements of an array.
   * Implements Fisher-Yates Shuffle Algorithm
   * http://Bost.Ocks.org/mike/shuffle/
   * http://en.Wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle
   *
   * @method shuffle
   * @param  {Array}   array  Array to shuffle
   * @param  {Boolean} [bool] Modify passed array
   * @return {Array}   Shuffled array
   */

  p5.prototype.shuffle = function(arr, bool) {
    arr = bool || ArrayBuffer.isView(arr)? arr : arr.slice();

    for (var rnd, tmp, idx = arr.length; idx > 1;
      rnd = Math.random()*idx | 0,
      tmp = arr[--idx], arr[idx] = arr[rnd], arr[rnd] = tmp);

    return arr;
  };

function setup() {
  var regularArr = ["ABC", "def", createVector(), TAU, Math.E];
  println(regularArr);
  shuffle(regularArr, true);
  println(regularArr), println("");

  var typedArr = new Uint8ClampedArray([1, 2, 3, 4, 5]);
  println(typedArr);
  shuffle(typedArr);
  println(typedArr), println("");
}
```

**Comment by lmccart** [comment]
thanks @GoToLoop. this looks like it's failing the linter:
https://travis-ci.org/lmccart/p5.js/builds/50104223

could you try running and make sure the library builds? instructions here: https://github.com/lmccart/p5.js/wiki/Development#setup

thanks :)

**Comment by GoToLoop** [comment]
Yikes. That is complicated for me. Can n1 w/ more experience w/ that do it instead of me?
Anyways, my test run above works flawlessly!  :P

**Comment by lmccart** [comment]
ah ok, no problem. I'll do it in the next couple days unless somewhere else gets to it sooner!

**Comment by kevinb7** [comment]
@GoToLoop What platform are you developing on?

**Comment by GoToLoop** [comment]
@kevinb7, just used Processing's PDE!  LoL

**Comment by kevinb7** [comment]
@GoToLoop I see... you modified the prototype in the example.  That's one way to do it.  Maybe I can help you through the setup instructions that @lmccart linked to.  Are you on Windows, Mac, or Linux?

**Comment by GoToLoop** [comment]
Arf! I give up! That "Linter" doesn't allow expert &/or æsthetically code styles!  =(

**Comment by kevinb7** [comment]
All "for", "if", "while", etc. statements must be followed by a block using braces even if it's a single line.  Also, 80 characters is the max line length.

**Comment by GoToLoop** [comment]
That's horrible for æsthetics! Even the original code @ 1st place from StackOverflow used a style more radical than mine!
I can do that, but it's not gonna be easier to read as the original style!  *_*

**Comment by GoToLoop** [comment]
The original pull request below is much easier to understand b/c the swap happens in 1 line.
Placing them in separate lines won't be that much clearer:

```js
p5.prototype.shuffle = function(arr, bool) {
  arr = bool || ArrayBuffer.isView(arr)? arr : arr.slice();

  for (var rnd, tmp, idx = arr.length; idx > 1;
    rnd = Math.random()*idx | 0,
    tmp = arr[--idx], arr[idx] = arr[rnd], arr[rnd] = tmp);

  return arr;
};
```

**Comment by lmccart** [comment]
hi @GoToLoop I understand the frustration, everyone has their own preferred style. :)
we chose this one because it is the most explicit. by doing this, it is less likely little errors will get introduced, for example when if statements become multiple lines, we don't lose the additional lines accidentally. it's also more readable for people that are less familiar with abbreviated and condensed syntax, so a greater number of people will be able to understand and participate.

our linter generally lines up with this guide: https://github.com/rwaldron/idiomatic.js/, although we use single quotes instead of double for strings.

**Comment by kevinb7** [comment]
It should probably look something like this:
```
for (var rnd, tmp, idx = arr.length; idx > 1; idx--) {
    rnd = Math.random()*idx | 0;
    tmp = arr[idx - 1];
    arr[idx - 1] = arr[rnd];
    arr[rnd] = tmp;
}
return arr;
```
If you're looking for performance though, I'd probably do this a ```while``` loop.

**Comment by GoToLoop** [comment]
I know very well about single & multiple lines and the risk of forgetting about it.
But this code was already audited & runs flawlessly!
And there's no more to add to the  `for ()` loop. It's just swap array indices for shuffle!

**Comment by GoToLoop** [comment]
* That `idx - 1` is simply a no-no; since it's repeating the very same calculus over & over rather than do that at once and get done w/ it!
* The swap algorithm in 3 separate lines aren't easier to grasp than having them 1 line read!
* It makes the process feel more atomic/whole! Now it feels separated apart!
* Dunno whether while () is any faster than for () though!  @_@

**Comment by kevinb7** [comment]
I just checked the ```while``` vs. ```for``` loop on jsperf and they're equal now (this wasn't always the case) so disregard my comment about that.  I agree that ```--idx``` is faster.  I'd probably do ```idx--;``` on a single line that way people don't have to remember what the difference between ```--idx``` and ```idx--``` are but it's really splitting hairs at that point... calling Math.random() will dominate things perf wise.

ES6 has array destructuring which allows for statements like 
```[arr[idx], arr[rnd]] = [arr[rnd], arr[idx]]```
which transpiles down to something similar to what we have now.

**Comment by GoToLoop** [comment]
* I think `rnd = Math.random()*idx-- | 0` is more confusing than `tmp = arr[--idx]`.
* The need to subtract 1 less from _idx_ is @ the swap algorithm, not in the _rnd_ index generator!
* That is b/c last index of an array is its `length - 1`. While @ **Math.random()** we need its _length_

**Comment by kevinb7** [comment]
What I was thinking of when I made the comment about ```idx--``` was the following:
```
rnd = Math.random() * idx | 0;
idx--;
tmp = arr[idx];
arr[idx] = arr[rnd];
arr[rnd] = tmp;
```

With regards to ES6, you can use it today using [6to5](http://6to5.org/).  It supports IE9+.

**Comment by GoToLoop** [comment]
* That 6to5 seems more boiler plate & slowness. Either it's supported or not!
* I prefer using the unary operators right at the spot than a separate statement!  :p
* Since this "Linter" only cares about style rather than correct healthy code, gonna re-"fix" my code!

**Comment by GoToLoop** [comment]
Well, that's how horrible it ended up w/. Very insipid w/ separated statement lines. Oh well:

```js
  p5.prototype.shuffle = function(arr, bool) {
    arr = bool || ArrayBuffer.isView(arr)? arr : arr.slice();

    var rnd, tmp, idx = arr.length;
    while (idx > 1) {
      rnd = Math.random()*idx | 0;

      tmp = arr[--idx];
      arr[idx] = arr[rnd];
      arr[rnd] = tmp;
    }

    return arr;
  };
```

**Comment by lmccart** [comment]
hi @GoToLoop thank you for all the work getting this to work, and your point of view is appreciated! however, please be sensitive of your tone. sometimes using negative or argumentative language can be intimidating for people, and we want to make sure everyone feels welcome :)

**Comment by GoToLoop** [comment]
* @lmccart, where have I offended n1? You need to be more clearer where it happened!
* Perhaps it's my exaggerated drama which is the offending tone?
* Alas! I guess I need to be more apathic robotic human here!  *_*

**Comment by GoToLoop** [comment]
Alas, 80-char lines are too strict. 100 is more balanced!
It's improbable there are that many folks programming via a smartphone screen size!

**Comment by lmccart** [comment]
@GoToLoop let's discuss further offline, I just sent you an email.

**Pull request merged**
