### PR TITLE
Detach events

### PR DESCRIPTION
**Pull request by outofambit**
fix for #2010 

I've added a `detachListener` function that gets called when someone passes `false` to the user facing event registration methods or if they pass a new handler to be attached in place of another. Thus, users are limited to a single handler per user facing event registration method.

Also, added a test to make sure the basic machinery does what it says it will. 😸

### CODE REVIEW

**Comment by lmccart** [comment]
the code all looks great. however, the three tests are failing for me, I'm not sure why.. are they passing on your machine?

then there's the question of documentation. my proposal would be to add an example to mousePressed() documentation (in events/mouse.js) that shows detaching a listener. then updating the docs for every method that calls adjustListener() with a second signature that takes one boolean argument. does this sound reasonable?

**Comment by outofambit** [comment]
@lmccart oof sorry about the tests! (i swear i had them passing but it wasn't true.) they should be good now.

that documentation plan sounds totally reasonable. i'll have that up soon!

**Comment by lmccart** [comment]
🎉

**Comment by lyle** [comment]
It looks like this change, specifically "limit to attaching one listener per event at a time" caused #3591

**Comment by lyle** [comment]
I don't think this implementation should be changed at all - I think .drop needs to figure out how to safely add it's two events. So ignore this new issue in this context.

**Pull request merged**
