### PR TITLE
Allow a preload() method that doesn't specify any load methods to not halt the sketch

### PR DESCRIPTION
**Pull request by plural**
This fixes issue #947.

I verified that this fixes one of the broken examples in p5.play as well.

### CODE REVIEW

**Comment by plural** [comment]
I'm not super thrilled with the new method name, so please give me any suggestions there.

A coworker suggested this code be rewritten to use futures instead of wrapping the methods.  I'd be happy to take a crack that that if you want.

**Comment by lmccart** [comment]
this is great, thank you! I think the name is fine, I might also suggest "_endPreload()" or "_finishPreload()". i'll go ahead and merge, feel free to submit a PR for name change if you'd like. I think it would be nice to use promises, however I don't think it's supported yet in IE? http://caniuse.com/#search=futures

we could add a polyfill to handle this, but my question would be whether it's worth the added filesize. maybe it is?

**Comment by plural** [comment]
ahhhh, IE.  :)  @lmccart is there a target supported browsers list for p5?

bringing in an entire new lib to handle this doesn't seem like a great idea unless Promises would make a lot more things easier in the code.  I'll look at the code some more and see if it would actually improve anything substantially.

I'll think about the name so more.  It may be best to leave it along.  :)

**Comment by lmccart** [comment]
hm we are still in the process of writing up better dev guidelines, but the short answer is:
* we aim to support the two most recent versions of the major browsers (IE, safari, firefox, chrome, and the mobile versions of these)
* when things don't work, they should fail as gracefully as possible so web projects that incorporate p5 won't break completely if a part of p5 isn't supported.

**Pull request merged**
