### PR TITLE
Fix typo in curveVertex doc

### LINKED ISSUE #5564: Unnecessary word in docs
https://p5js.org/reference/#/p5/curveVertex

`Description`, paragraph 2, 1st sentence there is an extra `a`.

> The first and last points in a series of curveVertex() lines will be used to guide the beginning and end of `a` the curve.

### PR DESCRIPTION
**Pull request by beaumu**
Resolves #5564 

 Changes:
 Edited `vertex.js`:
- Removed 'a' in second paragraph of  [curveVertex]

#### PR Checklist
- [x] `npm run lint` passes
- [x] [Inline documentation] is included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[curveVertex]: https://github.com/processing/p5.js/blob/main/src/core/shape/vertex.js#L423

### CODE REVIEW

**Comment by limzykenneth** [comment]
Hi @beaumu, thanks for the changes here. Just one note, we usually use a bot to handle adding people to the contributors list, adding it manually as the case in this PR may cause the list to not be updated on the README file until it is updated again. Can you remove that addition in this PR and we'll add you to the contributors list via the bot command?

**Comment by limzykenneth** [comment]
Not sure why but there are now a lot of unrelated commits here. Can you reset git back to de7de4c32226a17f7d7625c95ba1b204ec7adc82 then make just the typo fix, commit it and force push to your branch?

Let me know if you are not sure how to do that.

**Comment by beaumu** [comment]
Thanks for the heads up! 
Was following the contributions page to try to not mess up, guess I failed 😅
Also, if I have a question about the best practices here and what's the best way of testing and/or trying out the code that has been written. To who can I ask those? 😄

**Comment by limzykenneth** [comment]
That's perfect, thanks. There's no need to worry about additional changes in the repo when you submit a PR, git will take care of it in most cases and in the case of conflicts we'll resolve it before merging without necessarily needing additional work from you.

> Also, if I have a question about the best practices here and what's the best way of testing and/or trying out the code that has been written. To who can I ask those?

You can checkout the contributors docs at the root of this repo to see if they answer any questions you have. If you have more specific questions, feel free to open an issue.

**Comment by limzykenneth** [comment]
@all-contributors please add @beaumu for docs

**Pull request merged**
