### PR TITLE
added CHANGELOG.md

### LINKED ISSUE #1922: create and maintain a CHANGELOG.md
I keep up with p5.js and the community surrounding it. However, it seems like an accident when I notice there's a version bump, and even worse still, I generally have no idea what's changed.

Using the `conventional-changelog-cli` tool, we can easily create a living document. For right now, I propose the following workflow:

Prior to cutting a new tag before the next release:
* bump version in `package.json`
* run `$ conventional-changelog  -i CHANGELOG.md -s` in the repo directory
* commit `package.json` and `CHANGELOG.md`
* Cut a tag
* Push a release

I've gone ahead and created a CHANGELOG.md for the current state of master and will create a PR for it momentarily.

### PR DESCRIPTION
**Pull request by 8-uh**
This is a CHANGELOG detailing all commits back to the beginning of the repo. Fixes #1922

### CODE REVIEW

**Comment by limzykenneth** [comment]
I like the idea of a more comprehensive change log, sometimes the change log entry can be a bit vague. However, I don't quite get how this new change log is different from just look at the commit history with git. Personally I find it a bit too noisy to be a change log as well. I suspect if it is going to be just a collection of commit messages, those who can navigate/understand it can already do it with git and those who couldn't get these information from git might find this too dense and hard to navigate.

**Comment by lmccart** [comment]
I do keep this changelog here: https://github.com/processing/p5.js/releases, which is meant to be a more human readable list of changes made. Does this cover what you are looking for?

**Comment by 8-uh** [comment]
@limzykenneth I'll agree that the changelog that I put in is... overly verbose. I just ran a simple changelog generator. It definitely needs to be pared down. This was more to have a discussion, and so far, I'm happy with the responses.

That being said, there's no universal format for a changelog, but there are some really good guidelines. To @lmccart point, I'm going to add a checklist here... anything the `releases` page does, I'll check off. Perhaps we don't need one, but I have a feeling there will be some missing things. 

- [ ] Identify whether or not [Semantic Versioning](http://semver.org/) is used on the project [^1]
- [] Easily link to sections of the document, and to the issues commits fixed or completed (Hence the use of markdown)
- [x] Releases in reverse chronological order (which the `releases` page does automatically)
- [ ] A [WIP] section above the latest release with a short bullet list of features/bugs being worked on for the next release. This is to let devs know what to expect in the upcoming releases, as well as what discussions are being had and perhaps might spark extra help from the community
- [ ] Release date in international format `YYYY-MM-DD`. It's universal and easy to parse.
- [ ] Link to issues 
- [x] Group changes to describe their impact on the project, as follows:
- - [x] Added for new features.
- - [x] Changed for changes in existing functionality.
- - [] Deprecated for once-stable features removed in upcoming releases.
- - [] Removed for deprecated features removed in this release.
- - [x] Fixes for any bug fixes.
- - [] Security to invite users to upgrade in case of vulnerabilities.
- [ ] Provide recognition to community members for creating, fixing, reworking a piece of code. For example: check out the [Phaser CHANGELOG.md](https://github.com/photonstorm/phaser/blob/master/v2/CHANGELOG.md)

Some of the unchecked ones are because I.. dunno if they've ever existed for this project. 

> I do keep this changelog here: https://github.com/processing/p5.js/releases, which is meant to be a more human readable list of changes made. Does this cover what you are looking for?
- @lmccart 

Partially, but not exactly. I know this sounds pedantic, but, there's a space some of us reside in that exists between core team developer and "end-user" developer.. and I think that space is called "Individual Contributor". I keep forks of many libraries local on my machine and run an `upstream fetch` on them whenever I'm starting a new project. Whenever I run into something in a library that seems newly broken, or doesn't work like it's supposed to, it's real easy to grab the changelog and look through it. Honestly, the changelog should reside somewhere between a Releases page (for those who just want a quick glance) and a git diffs log (there's just so much in there). I can't tell you how many times I've found solutions to other problems just by reading over a well thought out CHANGELOG.


Yes, the CHANGELOG I PR'd is... unacceptable. And I apologize for that. But, I'm gonna try again.

**Comment by limzykenneth** [comment]
I believe semver is being used (technically, since p5.js haven't break 1.0.0 yet). The rest mostly rely on availability of extra maintenance effort or some sort of easier automation but you do provide a pretty good starting point. 👍 

Try and hold up on the PR for now, let's hammer out the details with these discussions first so you don't need to put in too much effort into something that may or may not get merged, unless of course if if helps with any thought process.

**Pull request closed without merging**
