### PR TITLE
Number of smaller fixes

### PR DESCRIPTION
**Pull request by futuremarc**
`parent()` now returns the parent of a p5 Element when used with no args. `styleTranslate`, `styleRotate` and `stylePosition` all new names addressing the naming issue brought up in #808.  `stylePosition` can now take % units. `createImg` also had a few bugs and now supports a callback function as a 2nd or 3rd arg

These are a couple things that needed to be cleaned up. thanks

**edit**: apparently I made this branch after the DOM input additions, so this PR includes changes made in #834 which haven't been pulled yet; I'll go address #834 so that this can move in behind it.

### CODE REVIEW

**Comment by shiffman** [comment]
Great, I have a bunch of new "test" examples I've been working on which I'll add once this and #834 are resolved.

**Comment by futuremarc** [comment]
Added `isHidden()` since I've found that knowing if an element is hidden or visible is very useful!

**Comment by lmccart** [comment]
cool. two questions about isHidden. I'm not sure about the name. generally we don't use the is/get/set convention, opting to keep names shorter when possible (isMousePressed var is an exception, due to a naming conflict). could this be .hidden() instead?

second question is more a concern about api bloat. I completely trust your intuition this is useful, but the question for me is does it significantly simplify things or make them more understandable? p5.js does not have many getters in the core api, instead asking the user to keep track of program state themselves by using variables. I wonder if there is something useful here for beginners to understand concepts like state and control logic. 

if they didn't want to go the state var route, this is also a property that they can access themselves with the right syntax (myElement.elt.style.display). of course it's a bit long, but is this the place we might draw the line and start guiding users toward learning about the underlying html/css through good documentation and external resource linking?

curious what you and others think.

**Comment by lmccart** [comment]
rest of this PR is looking great btw!

**Comment by futuremarc** [comment]
Hey Lauren,

See you point here. It just feels like a basic thing that should be part of the DOM API, and that something like `if (myElement.elt.style.display === 'none'){ //do something} feels like it'd be a bit distant to new users rather than `if (myElement.hidden()){ //do something}`

**Comment by futuremarc** [comment]
The `createImg()` bug was actually one that was sitting in there for a while and was really interesting to solve. The images were never truly being removed from the DOM.

**Comment by futuremarc** [comment]
curious about @shiffman 's opinion on `hidden()`

**Comment by shiffman** [comment]
@futuremarc I definitely see your point, and can imagine that this is something that may ultimately make sense to include.  For now, however, I lean towards @lmccart's point about keeping the API small.  Admittedly, I'm being conservative, but I'd like to hold off on this and see a full round of students making work with p5.js and DOM and examine at the scenarios that come up over and over again.  This may  be one of those, and the fact that you have needed it is a good indication that we may also see it popping up in students' assignments. 

The primary example I can imagine is toggling a DOM element between `show()` and `hide()`.  For a simple example at the moment, I'd probably use it as an opportunity to teach about boolean variables.

**Comment by shiffman** [comment]
Also, I am not sure about this but I'd like to raise the question again about namespacing `translate()` and `rotate()` for DOM elements, rather than `styleTranslate()`, i.e.

```javascript
var div = createDiv('hello again!');
div.style('background-color', '#FF0000');
div.style('font-size', '24px');
div.style.translate(100,100);
div.style.rotate(45);
```

vs.

```javascript
var div = createDiv('hello again!');
div.style('background-color', '#FF0000');
div.style('font-size', '24px');
div.styleTranslate(100,100);
div.styleRotate(45);
```

I think I like the first one b/c the `translate()` and `rotate()` functions mirror the canvas ones in name, but are clearly being called on a DOM element's `style` which differentiates them?

Then again, is double dots is weirder and more scary/confusing.  I'm not sure.

One final option, we could do some magic behind the scenes and allow this:

```javascript
div.style('translate', 100, 100);
div.style('rotate',45);
```

But this is perhaps misleading since it's not mirroring valid CSS.

**Comment by futuremarc** [comment]
Oh hey @shiffman , very interesting solution in the end! I think `div.style('position',100,100)` would feel totally fine too.

**Comment by lmccart** [comment]
yeah this one actually feels pretty good to me, too!

**Comment by shiffman** [comment]
Great!  I would err on the side of keeping `position()`, however, as I think there are scenarios where `createSomething()` and `position()` are taught before or without ever seeing `style()`.   It's tricky because there is value in mirroring CSS for learning, but I would had to lose the simplicity of the following for quick and dirty canvas + interface.

```javascript
function setup() {
  createCanvas(640, 360);   // Make a canvas
  var button = createButton('start');
  button.position(20, 320); // Place button on bottom of canvas
}
```

**Comment by lmccart** [comment]
todo:
* https://github.com/processing/p5.js/issues/954
* pull out fix for `createImg`
* pull out addition for `parent()`

**Pull request closed without merging**
