### PR TITLE
fixed order and naming of parameters in saveCanvas

### PR DESCRIPTION
**Pull request by workergnome**
the documentation for `saveCanvas()` says:

saveCanvas(filename,extension,canvas), but in the code, the canvas was the first option.  Changed the code to reflect the documentation.

### CODE REVIEW

**Comment by lmccart** [comment]
Thanks! I think we actually want to go the other way, change the doc to match the code and have the canvas element first. Just based on looking at some of the other saveX() functions we have: https://github.com/processing/p5.js/blob/master/lib/p5.js#L5400 https://github.com/processing/p5.js/blob/master/lib/p5.js#L5366

**Comment by workergnome** [comment]
I'm not completely opposed to that—but it might be weird, since the canvas is optional, because it defaults to the current.  When I use this, I just write
 ```
   saveCanvas("myImage","png")
```

If we change the canvas to the be first param, we'd have to write
 ```
   saveCanvas(null, "myImage","png").
```
This might be overthinking it, since you could just write 

```
  save("myImage.png");

```


Thoughts?

**Comment by lmccart** [comment]
aha i see! let's stick with your revision then. i'll merge it in now.

**Comment by workergnome** [comment]
Thanks!

**Comment by lmccart** [comment]
thinking about this more, I think it might be a good idea to stick with the pattern of the other saveX() methods. looking at the doc page for `save()` itself, you can just pass in a path, or you can optionally stick the object to save before that. so I think rather than requiring the user to pass in null if they want to default to the current canvas, they could leave off the canvas pointer completely and just write `saveCanvas('myCanvas.jpg');` 

http://p5js.org/reference/#p5/save

**Comment by workergnome** [comment]
OK by me!  I'm super-swamped this week, but I'll try and get to this soon.  I'll comment on a proposed API here before coding, just to make sure that it works for you.  

Thanks!

**Comment by lmccart** [comment]
I'll go ahead and take a crack at this one.

**Comment by workergnome** [comment]
Sorry!  Go for it.

**Pull request merged**
