### PR TITLE
Fixes #5702 and #5525

### LINKED ISSUE #5702: p5.Element.style() does not correctly update the width, height, left, and top properties if they are changed in the CSS.
### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [X] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

### p5.js version

1.4.1

### Web browser and version

Chrome 103.0.5060.66 (Official Build) (64-bit) (cohort: Stable) 

### Operating System

Windows 10

### Steps:
1. Run the following piece of code
2. Notice the properties do not reflect their actual values. 

### Snippet:
```js
function setup() {
  createCanvas(800, 800);
  this.testButton = createButton('TEST');
  this.testButton.position(0, 0);

  this.testButton.style('width', '25%');
  this.testButton.style('height', '25%');
  this.testButton.style('left', '50%');
  this.testButton.style('top', '50%');

  console.log(`.width: ${testButton.width} -> actual: ${testButton.elt.offsetWidth} - (CSS 25%)`);
  console.log(`.height: ${testButton.height} -> actual: ${testButton.elt.offsetHeight} - (CSS 25%)`);
  console.log(`.left: ${testButton.left} -> actual: ${testButton.elt.offsetLeft} - (CSS 50%)`);
  console.log(`.right: ${testButton.top} -> actual: ${testButton.elt.offsetTop} - (CSS 50%)`);
}

function draw() {
  background(220);
  fill(0);
}
```

### PR DESCRIPTION
**Pull request by msed21**
Resolves #5702 and #5525

Changes:
If the `width`, `height`, `top`, and `left` properties are changed in the CSS provided to p5.Element.style(), they will be reflected
in the corresponding p5.Element properties `width`, `height`, `top`, and `left`.

#### PR Checklist
- [x] `npm run lint` passes
- [x] [Inline documentation] is included / updated
- [x] [Unit tests] are included / updated

### CODE REVIEW

**Comment by msed21** [comment]
The `width`, `height`, `left`, and `top` properties do not seem to be documented in the p5.Element reference seen [here](https://p5js.org/reference/#/p5.Element). It's possible that is was deliberately left out in place for the .size() and .position() methods which returns the correct values making this pull request somewhat unnecessary. If they were not I would be happy to add the documentation myself in this pull request.

**Comment by Qianqianye** [comment]
Hey @limzykenneth, what do you think of this PR? Also adding DOM stewards @outofambit, @SarveshLimaye to this discussion. What it'd be possible to merge this PR before the 1.4.2 release?

**Comment by limzykenneth** [comment]
Need some time to review this. I'll see if I can get to it today or this week.

**Comment by limzykenneth** [comment]
@msed21 Can you let me know here the numbers you see when running the example code you shared in your issue? I'm having trouble replicating the original issue with Firefox reporting matching numbers without this PR while Chrome has a different issue that can be better fix with another solution. I just want to check what numbers you are seeing first before making a recommendation.

**Comment by msed21** [comment]
@limzykenneth Running the example code in my issue produces the following console logs.

```
.width: 2365 -> actual: 237 - (CSS 25%) 
.height: 20275 -> actual: 203 - (CSS 25%) 
.left: 473 -> actual: 473 - (CSS 50%) 
.right: 4055 -> actual: 406 - (CSS 50%)
```
This code was run in the p5.js Web Editor on Google Chrome 103.0.5060.134 (Official Build) (64-bit)

**Comment by limzykenneth** [comment]
Yes, this is as I expected. The actual values returned by Chrome is `236.5` the final value of `2365` is because of the regex not anticipating there being a decimal point and removing it along with the `px`. An easier fix would be to fix the regex instead. Firefox does not return fractional value so it gives matching values.

**Comment by msed21** [comment]
I have created a new pull request that resolves this issue by updating the regex.

**Pull request closed without merging**
