### PR TITLE
Improve p5.Vector

### LINKED ISSUE #2318: A few thoughts about p5.Vector implementation
I can make PR, but first I would like to discuss the list below.

1.  Whenever Vector instance is created with `new p5.Vector(...)`, the default value
    for x, y and z is 0.

    Then in every Vector method that accepts Vector as argument value, default 0 is applied again and again, for example:
    ```javascript
    p5.Vector.prototype.set = function (x, y, z) {
      if (x instanceof p5.Vector) {
        this.x = x.x || 0;
        this.y = x.y || 0;
        this.z = x.z || 0;
        return this;
      }
      ...
    };
    ```
    I think it is not necessary, because the default value is already there.

2.  The default value of `n` in `p5.Vector.prototype.mult` is 0.
    When I call `mult` with no argument, my vector will be mutated.
    I think the default value of `n` should be 1.

3.  We don't check if we divide by 0 in `p5.Vector.prototype.div`.
    There is a lot of validation in other methods, but not in `div`.
    Is it done by design?

    Checking divide by 0 case in `div` method would make `p5.Vector.prototype.normalize` a bit simpler.

4.  Performance optimisations:

    - this.p5.random() => Math.random()
    - Math.PI*2 => constants.TWO_PI

    BTW. I can't get the fundamental difference between `if` and `else` parts,
    as the results seems to be the same, except the `if` part will be slower.

    ```javascript
    p5.Vector.random3D = function random3D() {
      ...
      if (this.p5) {
        angle = this.p5.random(0,constants.TWO_PI);
        vz = this.p5.random(-1,1);
      } else {
        angle = Math.random()*Math.PI*2;
        vz = Math.random()*2-1;
      }
      ...
    }
    ```

5.  Constructor could be much simpler if there were named arguments and different order of them.
    `function() => function(x, y, z, context)`

    ```javascript
    p5.Vector = function(x, y, z, context) {
      // This is how it comes in with createVector()
      if (context instanceof p5) {
        this.p5 = context;
      }
      this.x = x || 0;
      this.y = y || 0;
      this.z = z || 0;
      this.name = 'p5.Vector';
    };
    ```
    This of course should be propagated in other places, but there is only a few such a cases. 

6.  Functions should be named. This will help during debugging.

    ```javascript
    // Bad example
    p5.Vector.prototype.set = function (x, y, z) {...}

    // Good example
    p5.Vector.prototype.set = function set(x, y, z) {...}

    // Still good, but over engineered example
    p5.Vector.prototype.set = function p5VectorSet(x, y, z) {...}
    ```

### PR DESCRIPTION
**Pull request by tawez**
Improve debugging by naming all anonymous functions.
Optimize calculations performance.
Improve code readability and consistency.
Improve p5.Vector.prototype.mult behaviour:
- do nothing if n is undefined or not a valid number and throw a console warning.

Improve p5.Vector.prototype.div behaviour:
- do nothing if n is undefined or not a valid number and throw a console warning;
- do nothing if n is 0 and throw a console warning "divide by 0"

Resolves #2318

### CODE REVIEW

**Comment by tawez** [comment]
It looks like it is a problem with Travis, not the with the code itself.
Weird... and it looks like this problem occurs in other PRs.

Is there a way to retrigger Travis?

**Comment by limzykenneth** [comment]
@tawez No worries, that's "expected" see #1881 I'll restart the tests

**Comment by Spongman** [comment]
i think you should start again, and disable you editor's blatant 'reformat everything' setting.

**Comment by limzykenneth** [comment]
The current failure is related to #2338 which should be fixed in the source. If travis doesn't run the new tests on this PR then we need to manually review this then merge it in if everything seems fine and let travis do its job then.

**Comment by tawez** [comment]
@Spongman What do you mean by

> disable your editor's 'reformat everything' setting

?

**Comment by Spongman** [comment]
it seems that most of the changes in this PR are whitespace and/or formatting changes. you should probably split those out into a separate PR.

**Comment by tawez** [comment]
Well, if it will help, I can split this PR into two, 1st - code, 2nd - formating

**Comment by lmccart** [comment]
I think this one is taken care of with #2350

**Pull request closed without merging**
