### PR TITLE
Point added

### PR DESCRIPTION
**Pull request by AdilRabbani**
Added point for WebGL. This is based on the fragment shader provided by @aferriss #3017. Uses default square points for small points and circular points for larger ones.

### CODE REVIEW

**Comment by mlarghydracept** [comment]
Hi @AdilRabbani ! Are you trying to update the webgl-gsoc branch with this PR in addition to adding point functionality? I understand the impulse but I won't be able to review your actual changes very easily in this state. Maybe these tasks can be separated? I can't remember how we have handled this in the past. Anyone have any ideas on how we should keep the gsoc branch up-to-date with changes going forward?

**Comment by AdilRabbani** [comment]
I thought the webgl-gsoc branch was already up to date. Maybe @kjhollen can update the branch through master? I'll submit a new PR again.

**Comment by kjhollen** [comment]
Hi Adil, I can merge the master branch into webgl-2018-gsoc later this weekend or on Monday, but I don't plan to do this regularly over the summer. Please use webgl-2018-gsoc as the basis for future work instead of master. Thanks!

**Comment by kjhollen** [comment]
Hi @AdilRabbani, I've updated the webgl-gsoc-2018 branch by merging it with master. For future work, please start with the webgl-gsoc-2018 branch instead of master. As a reminder, you can do this with:

`git checkout webgl-gsoc-2018`
`git branch new-branch-name`

Thanks!

**Comment by AdilRabbani** [comment]
Yeah, Sorry for the trouble!

**Pull request closed without merging**
