### PR TITLE
Change loadModel() example

### PR DESCRIPTION
**Pull request by TanviKumar**
Use smaller .obj file for faster loading
Model used is suitable for canvas size of example. (current example is too small)

### CODE REVIEW

**Comment by TanviKumar** [comment]
To resolve #2904

**Comment by TanviKumar** [comment]
@almchung Done!

**Comment by kjhollen** [comment]
hi @TanviKumar, I'm not seeing your updates—can you make sure you've pushed your changes? thanks!

**Comment by TanviKumar** [comment]
Hey @kjhollen, sorry about that, changes pushed!

**Comment by TanviKumar** [comment]
@almchung @kjhollen The `model()` example uses the teapot too. Would it be advisable to change it to the corrected teapot example or the octahedron example in this PR?

**Comment by kjhollen** [comment]
great! I made one little edit because the word 'teapot' was still hanging around in the alt text for the other example.

**Comment by PAEDevelopment** [comment]
I'm sorry that I'm ignorant of the process here, and don't quite have the skills to contribute, but there are still tiny teapots in the examples and no octahedrons...

**Comment by TanviKumar** [comment]
@PAEDevelopment , the example code has been changed to reflect the requirement, I believe these changes are yet to be pushed to the site itself and should be in the near future.

**Pull request merged**
