### PR TITLE
Distance Calculation made easier.

### PR DESCRIPTION
**Pull request by ThunbergOlle**
This is pretty much my first pull request ever. Anyway:

I think there is an easier way of calculating the distance between two points. I think it should be easier to read and understand and also faster by doing this calculation instead. I may be wrong.

It cleans the code and cuts down the code length of the function.

### CODE REVIEW

**Comment by outofambit** [comment]
@Spongman can you please say more? why do you say that?

**Comment by outofambit** [comment]
Also, thank you @ThunbergOlle for submitting this pull request! and congrats on your first one ever! 🎉

**Comment by Spongman** [comment]
because the `Math.pow()` can be significantly more expensive that just multiplying a few numbers and/or taking the reciprocal. some implementations may shortcut around this, but not all do.

**Comment by Spongman** [comment]
also, i'm not quite sure about the math of the 3d case. i'm pretty sure you can remove one of the `sqrt` calls, especially since they're so expensive.

i'm wondering what the rationale is behind changing the existing implementation? it handles overflows correctly, infinities, string parameters, and arbitrary-length argument lists.

**Comment by ThunbergOlle** [comment]
Alright, I'm going to change the `Math.pow` parts to just multiply with itself. The math of the 3d case is indeed unnecessary. I will be changing that later.

The reason for chaning the existing implementation was mainly because of curiosity but I also thought I may had come up with something that may be better, so why not share it.

**Comment by ThunbergOlle** [comment]
I've fixed everything mentioned by @Spongman in the latest commit. 👍

**Comment by sanketsingh24** [comment]
Hey! I can clearly see that your implementation is alot easier to understand for others, but it is fundamental. The earlier implementation is straight from ` v8 `(also pointed out by @Spongman), and takes a lot more precautions and is thought over to be the most optimized one, and is agreed and trusted by the whole community. So I guess its better to keep the old implementation.

Also, Congrats on your first PR.

**Comment by outofambit** [comment]
@sanketsingh24 @Spongman 

Why don't we write up a list of test cases for this function? I understand the existing covers some important edge cases, but I do think this PR increases the readability considerably. It's hard to judge the tradeoffs (or understand what we could reincorporate into this PR).

So far, I'm hearing these cases are covered in the existing implementation:
* overflows/rounding correctly
* infinities
* string parameters
* arbitrary-length argument lists 

Are there others? I think this is a great opportunity to add tests for these cases.

**Comment by lmccart** [comment]
closing this due to inactivity. please feel free to open an issue following up on @outofambit's comment if you'd like to continue work on this.

**Pull request closed without merging**
