### PR TITLE
Implemented the createRadio() functionality issue #952

### PR DESCRIPTION
**Pull request by DarkPrince304**
This will make it possible to create a radiobutton in a similar way to createSelect().

Here's a demonstration of how it works (from the console):

```javascript
var a = createRadio("buttonList");
>> undefined
a;
>> 54.p5.Element {elt: div#buttonList, _pInst: undefined, _events: Object, width: 1883, height: 0}
```
By now a div element like this will be created in the HTML

```html
<div id="buttonList"></div>
```

To create the individual radio buttons:

```javascript
a.option("Button 1","one");
>>> <input type=​"radio" value=​"one" name=​"buttonList" id=​"ogrwszd4ikaf9a4i">​Button 1​</input>​
a.option("Button 2","two");
>>> <input type=​"radio" value=​"two" name=​"buttonList" id=​"7tnc2a9pget57b9">​Button 2​</input>​
a.option("Button 3","three");
>>> <input type=​"radio" value=​"three" name=​"buttonList" id=​"dzl6fvzt3mpr2j4i">​Button 3​</input>​
```

This will render the HTML to be something like:
```html
<div id="buttonList">
<input type=​"radio" value=​"one" name=​"buttonList" id=​"ogrwszd4ikaf9a4i">​Button 1​</input>​
<label for="ogrwszd4ikaf9a4i">Button 1</label>
<input type=​"radio" value=​"two" name=​"buttonList" id=​"7tnc2a9pget57b9">​Button 2​</input>​
<label for="7tnc2a9pget57b9">Button 1</label>
<input type=​"radio" value=​"three" name=​"buttonList" id=​​"dzl6fvzt3mpr2j4i">​Button 3​</input>​
<label for=​"dzl6fvzt3mpr2j4i">Button 1</label>
</div>
```
NOTE: The id of the div and the names of all buttons are the same.

If "Button 2" is selected:
```javascript
a.value("one")
>>> false
a.value("two")
>>> true
a.value("three")
>>> false
a.value()
>>> "two"
```

If no button is selected then `a.value` will return undefined irrespective of any parameters.

### CODE REVIEW

**Comment by DarkPrince304** [comment]
@shiffman : Can you review this too? :) I think createRadio() will work flawlessly now as expected.

**Comment by shiffman** [comment]
I've looked this over and it works great.  Thank you so much for contributing!  A few questions:

1.  With `createSelect()` we created a function called `selected()` since the values are associated with the individual options. Here you are using `value()`.   I think we should stick with `selected()`?
2. I noticed the `<input>` elements have generated ids.  Are you using this internally somehow?  Are they a must?  They may be confusing to for a user who peeks at the elements.

@lmccart @futuremarc feel free to weigh in.  Once we settle this a bit more, I'm happy to add an example.

**Comment by DarkPrince304** [comment]
@shiffman : Don't mention it! :)

Now to answer your questions:
1. Yes I see no problem with that. I'll change it to `selected()` so that the target audience can relate more. But the functionality would be same. I hope there are no problems with what `value()` does. So I guess only the name has to be changed to `selected()` right?
2. The ids that I have generated for the `<input>` elements are the same as the `for` attribute in the respective `<label>` tag. Since I thought the id should be unique so I used them as an id. Should I remove the id attribute? Or make them sound simpler?

Do give your feedback so I can make the appropriate changes :)

**Comment by shiffman** [comment]
1. Correct, `value()` and `selected()` can exhibit the same behavior.  This is what we have with `createSelect()`.  Though I'm sort of wondering now why we have `selected()`?  Is there a reason I'm forgetting @futuremarc / @lmccart?  Would it be more consistent to use `value()` across the board?

2. Is the label necessary?  Couldn't we make it simply generate this with no id or label?

```html
<input type="radio" value="one" name="buttonList">Button 1</input>
<input type="radio" value="two" name="buttonList">Button 2</input>
<input type="radio" value="three" name="buttonList">Button 3</input>
```

Certainly for more advanced scenarios the user can write their own HTML.  Of course, this now raises the question, is there a way to use `select()` to grab some sort of object that contains a group of `<input type="radio">` objects?

**Comment by DarkPrince304** [comment]
1. Yeah, I would like to know the same about using `value()` or `selected()`

2. I tried what you said but that didn't work for same reason. So I made it work the same way `createCheckbox()` works by creating labels.

We could make the `value` and the `id` attritbute of the `<input type="radio">` to be the same. That way I guess `select()` will work as we want it to.

**Comment by lmccart** [comment]
I believe `.selected()` can return an array of values if the "multiple" option for a checkbox is selected. I suppose this wouldn't be used for a radio select.
https://github.com/processing/p5.js/blob/master/lib/addons/p5.dom.js#L501

I'm not sure if there's any other difference... @futuremarc?

**Comment by DarkPrince304** [comment]
@lmccart I would like to know if there are any changes that need to be made to this so that I can make them and this feature gets merged too :)

**Comment by lmccart** [comment]
we are reviewing right now :) more soon...

**Comment by shiffman** [comment]
Hi @DarkPrince304 I took some time to review this today with @lmccart.  We discussed having the HTML render as follows:

```html
  <div>
    <input type="radio" value="apple" name="defaultradio0" id="defaultradio0-0"></input>
    <label for="defaultradio1-0">apple</label>
    <input type="radio" value="orange" name="defaultradio0" id="defaultradio0-1"></input>
    <label for="defaultradio1-1">orange</label>
    <input type="radio" value="pear" name="defaultradio0" id="defaultradio0-2"></input>
    <label for="defaultradio1-2">pear</label>
  </div>
```

If you create another `createRadio()` on the page the name would then be `defaultradio1` and the labels would be `defaultradio1-0`, `defaultradio1-1` etc.  Let us know what you think.

**Comment by DarkPrince304** [comment]
@shiffman Sounds great! Also what about the `value()` or the `selected()` function? Even if I change the name to `selected()` are you satisfied with the functioning of `value()` (which would be named `selected()` ) ?

**Comment by shiffman** [comment]
1. Yes, I think that as long as `value()` and `selected()` work just as they do with `createSelect()` then it's great.

2. All of the p5 `createX()` functions result in a the creation of a `p5.Element` which is an object that wraps of a native DOME element.  The `createRadio()` is a special case given that it generates multiple DOM elements.  The div acts as a container and is the element that is returned back to the user. This way the user can call `style()`, `position()`, `id()` etc. on that particular div.  This opens up a lot of tricky questions in terms of how a p5 user might use `select()` with radio buttons, but @lmccart discussed starting small and seeing how it goes with at least this.

**Comment by DarkPrince304** [comment]
Okay, a PR coming up soon. Also after this I'll open up a seperate issue for the case when there already exists a radio button on the page and how to allot name and id's to them.

**Comment by DarkPrince304** [comment]
I have made the desired changes in my new commits.

@shiffman: In the code snippet you gave I think the value of `label` should be `"defaultradio0-0","defaultradio0-1"`, etc and not `"defaultradio1-0","defaultradio1-1"`, etc. I think that was a typing mistake so I made the changes assuming that it was a typing mistake.

Also I have changed the name of `value()` to `selected()`. Now when no argument is passed to `selected()` it will return the checked element. If an argument is passed to it then it will check the element corresponding to the argument value. This is similar to how the `selected()` in `createSelect()` works. 

And one more thing I have made a check for existing radio buttons (added by user without using `createRadio()` function) which won't have so now I won't need to open an issue for that! :D
I think this will settle everything. So if there already exists two radio buttons when the page is loaded the index will start as `"defaultradio3"` and so on. :)

I think this settles everything and `createRadio()` is fully functional now!

**Comment by shiffman** [comment]
I've tested this and its all working great now.  One last detail, however, is that with `createSelect()` both `value()` and `selected()` work identically but with `createRadio()` I'm only getting `selected()` to work and `value()` gives me `undefined`.   For now let's have them duplicate functionality for radio and select. We can consider removing one or adjusting the behavior of one (for say a menu where you can select multiple elements) later.  ok @lmccart?   (and yes you are right about the counting!)

**Comment by DarkPrince304** [comment]
@shiffman Fixed and updated! :+1:

**Comment by lmccart** [comment]
thanks @DarkPrince304! @shiffman if this looks all good to you go ahead and hit merge. and thanks for reviewing!

**Comment by shiffman** [comment]
This is all set, thank you @DarkPrince304!!

**Pull request merged**
