### PR TITLE
Fixes incorrect normalMethod() call

### LINKED ISSUE #3575: webgl: 'mixedMode' manual calls `normalMaterial` incorrectly
`normalMaterial()` doesn't take these parameters:
https://github.com/processing/p5.js/blob/b2d1abce3ab5ebdeeb93558645405072521eaa13/test/manual-test-examples/webgl/mixedMode/sketch.js#L16

### PR DESCRIPTION
**Pull request by ashwathbhat**
Fixes #3575

### CODE REVIEW

**Comment by ashwathbhat** [comment]
@Spongman Could you review this?
Thankyou

**Comment by sanketsingh24** [comment]
I think this is currently being fixed in #3580 by @EOstling, If I am not wrong @stalgiag

**Comment by stalgiag** [comment]
Yes thanks @sanketsingh24 that is right. If someone else has claimed an issue and/or opened a pull request then it is part of the community standards to give that person a fair chance to finish working on the pull request. The goal is for everyone to get a fair chance to continue. That said, if a pull request or claimed issue sits unresolved for a long period of time then someone else is able to take it. A good rule of thumb is that if there is a pull request open for an issue then it is currently a work in progress and no one should open a pull request doing similar work. @ashwathbhat I am going to close this for now. If the other pull request isn't merged within a week then I will ping you here and this can be reopened. In the meantime there are many other issues that are unclaimed such as the documentation fix on #3545.

**Comment by ashwathbhat** [comment]
Sorry, hadn't noticed the #3580 since the issue was not mentioned in the PR.
@stalgiag It's fine. Will work on other issues.

**Comment by stalgiag** [comment]
That makes sense. Thanks for being understanding!

**Comment by ashwathbhat** [comment]
@stalgiag Could this PR be reopened?

**Comment by stalgiag** [comment]
I would but the repository that opened the pull request is missing. Did you delete your fork?

**Comment by ashwathbhat** [comment]
Yes, I did. I thought @EOstling would fix the issue.
Should I create a new pull request?

**Comment by stalgiag** [comment]
If you would like! If you are going to just make sure to quickly mention that you are on [it in the issue.](https://github.com/processing/p5.js/issues/3575)

**Comment by ashwathbhat** [comment]
Sure, will do it.

**Pull request closed without merging**
