### PR TITLE
show dom example execution

### LINKED ISSUE #4645: DOM examples not executed in the reference
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [x] Dom
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Feature enhancement details:
Currently, several DOM examples are not executed in the reference. It is always helpful to have the example code executed so that novice programmers can get a clear idea of how the code works. For some examples, making them work and look good might require small changes to the code, especially when canvas size is greater than 100x100 and when DOM functions add HTML elements that take a lot of space (i.e.: go beyond 100x100 px). 

Here's a list of the examples that could be executed: 

- [ ] [removeElements()](https://p5js.org/reference/#/p5/removeElements)
- [ ] [selectAll()](https://p5js.org/reference/#/p5/selectAll)
- [ ] [ input()](https://p5js.org/reference/#/p5/input)
- [ ] [createDiv()](https://p5js.org/reference/#/p5/createDiv)
- [ ] [createP()](https://p5js.org/reference/#/p5/createP)
- [ ] [createImg()](https://p5js.org/reference/#/p5/createImg)
- [ ] [createA()](https://p5js.org/reference/#/p5/createA)
- [ ] [createButton()](https://p5js.org/reference/#/p5/createButton)
- [ ] [createCheckbox](https://p5js.org/reference/#/p5/createCheckbox)
- [ ] [createInput](https://p5js.org/reference/#/p5/createInput)
- [ ] [createInput](https://p5js.org/reference/#/p5/createInput)
- [ ] [createCapture()](https://p5js.org/reference/#/p5/createCapture)
- [ ] [createElement()](https://p5js.org/reference/#/p5/createElement)
- [ ] [createSpan()](https://p5js.org/reference/#/p5/createSpan)

### PR DESCRIPTION
**Pull request by Aloneduckling**
Resolves #4645
 Changes:

Removed the `class` norender from the mentioned `div`s. The DOM examples will now be executed. 

 Screenshots of the change:

#### PR Checklist

- [x] `npm run lint` passes
- [x] [Inline documentation] is included / updated
- [ ] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Comment by lmccart** [comment]
thanks @Aloneduckling! could you post some screenshots of how this looks rendered? it was my memory that we included the "norender" class because the elements tended to visually clutter the page in a confusing way. just want to double check that's not the case.

**Comment by Aloneduckling** [comment]
> thanks @Aloneduckling! could you post some screenshots of how this looks rendered? it was my memory that we included the "norender" class because the elements tended to visually clutter the page in a confusing way. just want to double-check that's not the case.

Hello! 
 I checked the website locally. I found out that examples are working fine but some are not. I have attached the screenshots. 
Working properly: 
working
Not Working Properly
notWorking
I did some quick fixing on the above example by adding styles through the console, here are the result
notWorkingFix

Also, I have not added anything else to the code just removed the class "norender" the above fix is done through the chrome dev tools

**Comment by lmccart** [comment]
@Aloneduckling thanks for putting together this preview! Rather than manipulating via css, could you add some `position()` or `width()` calls when needed into the code to position these elements as you've done with css?

**Comment by Aloneduckling** [comment]
@lmccart, I have removed the style issues. I have used position(), size(), and style() in some places. Is that ok? I have also made some changes for a better display of examples, like adjusting the buttons' width to fit inside the canvas and other things. Screenshots are attached below for the same.

1.

inputcorrected

2.

useStyle

3.

corrDivStyle

**Comment by lmccart** [comment]
looks good, thanks @Aloneduckling!

**Comment by Aloneduckling** [comment]
@lmccart,
I forgot to mention that I haven't updated this PR, I just wanted to confirm if the changes and adjustments I made were correct. I think reverting this PR might create problems for others, so avoiding it would be good. I will open another issue and create PR after your confirmation for the same.

**Comment by lmccart** [comment]
@Aloneduckling oh I see. Yes if you could open a new PR that adds in these changes, that would be great.

**Comment by Aloneduckling** [comment]
@lmccart,
I have created a new PR

**Pull request merged**
