### PR TITLE
Add contributor to all-contributorsrc(Minjun Kim)

### PR DESCRIPTION
**Pull request by mjaything**
Addesses #2309

 Changes:

Added myself to the contributors list

 Screenshots of the change:

#### PR Checklist

- [X] `npm run lint` passes
- [ ] [Inline documentation] is included / updated
- [ ] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/master/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/master/contributor_docs#unit-tests

### CODE REVIEW

**Comment by mjaything** [comment]
Thanks @montoyamoraga ! Do you know how to update readme? #2309 says it's updated when `all-contributors generate` is run, but I'm unsure what it means.

**Comment by montoyamoraga** [comment]
@all-contributors add @mjaything please

**Comment by montoyamoraga** [comment]
@all-contributors please add @mjaything for bug and translation

**Comment by montoyamoraga** [comment]
@all-contributors please add @mjaything for 🐛  and 🌍

**Comment by montoyamoraga** [comment]
@all-contributors please add @mjaything for 🐛

**Comment by montoyamoraga** [comment]
@mjaything i hadn't used the all-contributors bot or the CLI tool, i tried the bot and i think it didn't work since we had already manually included you on the .all-contributors.src file :)

then, i forked this repo, cloned it to my computer installed the npm dev-dependencies with
```
npm install -only==dev
```

then i fixed some contributors that were duplicate, or had their avatar picture wrong, or had a contribution keyword like "docs" or "documentation" instead of "doc".

and then i run the all-contributors CLI tool for generating the readme and pushed and now i am merging with this repo so that you appear, yay :)

**Comment by mjaything** [comment]
Oh wow that was quite a journey, thanks so much! People manually typing in wrong contribution keyword might happen repetitively in the future I guess.

**Comment by montoyamoraga** [comment]
@mjaything yeah, that is why it's better to either use the bot, or copy/paste an existing contributor and adapting it :)

**Pull request merged**
