### PR TITLE
Updates to p5.Matrix and bug fix for canvas resize in webgl mode

### PR DESCRIPTION
**Pull request by indefinit**

### CODE REVIEW

**Comment by indefinit** [comment]
fix to bug referenced in #757

**Comment by lmccart** [comment]
cool! looks like a bunch of files in docs/ changed format or some detail of their metadata. any idea what happened? it's no big deal, but it would be cleaner I guess to be able to see just the relevant changes with these commits.

**Comment by indefinit** [comment]
hmm, been trying to git revert changes to see if I can get rid of the file mode change introduced in #41bf55d32c7395d011ca705cab1f9ded3d33dc25.  Git is not being kind right now...

**Comment by futuremarc** [comment]
git reset --hard 41bf55d32 (--hard to reset working tree and index, --mixed to reset index, --soft for neither but moves HEAD)

--hard is dangerous

**Pull request closed without merging**
