### PR TITLE
Fix for #1416: Update Font.textBounds to take text's alignment and baseline into account

### PR DESCRIPTION
**Pull request by mikewesthad**
Fix for #1416:

Updating `Font.textBounds` to take into account the text's baseline and alignment when calculating the bounding box:

- `textBounds` uses `_handleAlignment` to shift the bbox's x, y based on baseline and alignment.  This required that `_handleAlignment` take an optional `textWidth` parameter (to prevent recursion with `_handleAlignment` calling `textBounds` to find the width).
- Caching now uses the renderer's baseline and alignment in the key.

Caching tested via code like this:

```js
var string = "test";
textAlign(LEFT, BASELINE);
fill("#00A8EA");
text(string, 100, 100); // No cache hit
text(string, 100, 100); // Cache hit
textAlign(CENTER, CENTER);
fill("#FF8132");
text(string, 100, 100); // No cache hit
text(string, 100, 100); // Cache hit
```

The bug [demo](http://codepen.io/mikewesthad/pen/QNPxLz) on codepen now looks like this when tested against this PR.  The orange dots represent the (x, y) coordinates of text draw command and the boxes are the text bounds.

image

### CODE REVIEW

**Comment by dhowe** [comment]
nice!

**Comment by dhowe** [comment]
Nice work! This looks really close but the dot-position for valign=TOP looks incorrect to me. Here is what we get in Processing (which is our target):

screen shot 2016-05-15 at 8 46 50 pm

**Comment by mikewesthad** [comment]
@dhowe thanks for checking that! Hmm, none of the changes I made should effect the dot placement relative to the text. The [codepen demo](http://codepen.io/mikewesthad/pen/QNPxLz) is using v0.5.0 p5 and has the same vertical alignment of text mismatch with processing.

Since I was just focusing in on the bbox, think the vertical alignment mismatch is an existing bug that warrants a separate issue/PR? Happy to help & look into a fix.

**Comment by dhowe** [comment]
mmm, I wondered if that was unrelated -- so, yes please do...

**Comment by mikewesthad** [comment]
Opened #1421 - investigating the issue of font vertical alignment there

**Pull request merged**
