### PR TITLE
fix matrix angle modes

### PR DESCRIPTION
**Pull request by Spongman**
in order to fix matrix rotation use of angleMode, this PR ensures that the `p5` instance is threaded through matrix creation/manipulation.

it also moves the `p5` parameter to the `p5.Matrix` constructor to the last parameter in order to simplify the calling & handling of that parameter.

### CODE REVIEW

**Comment by Spongman** [comment]
fixes #2422

**Comment by mlarghydracept** [comment]
Hi! I was just running through and testing with the manual tests first and we are losing a reference to the matrix object somewhere. I am not sure if it is the only culprit but I would look at the beginning of `p5.Matrix.rotate()`. The simplest way to recreate the problem - 
```
function setup() {
createCanvas(windowWidth, windowHeight, WEBGL);
}
function draw(){
rotateX(frameCount * 0.02);
sphere(100);
}
```

**Comment by Spongman** [comment]
oh. hold on. i messed up.

**Comment by Spongman** [comment]
noooooooooooooo........

**Comment by mlarghydracept** [comment]
Nice fix!

**Pull request merged**
