### PR TITLE
p5.dom: p5.MediaElement additions

### PR DESCRIPTION
**Pull request by therewasaguy**
- [Add](https://github.com/processing/p5.js/compare/master...therewasaguy:domAudioSource?expand=1#diff-84dfcaf5d56a24f4ee13a32c644817b0R1113) showControls() / hideControls() to access browser's default audio/video controls.

- [Fix](https://github.com/processing/p5.js/compare/master...therewasaguy:domAudioSource?expand=1#diff-84dfcaf5d56a24f4ee13a32c644817b0L893) a bug with Chrome where .load() must be called after .stop() before it can .play() again

- MediaElements can [route their audio into p5.sound or Web Audio API](https://github.com/processing/p5.js/compare/master...therewasaguy:domAudioSource?expand=1#diff-84dfcaf5d56a24f4ee13a32c644817b0R1042) with the ``connect()`` method

- MediaElements can trigger events at specific times during playback using [``myMediaElement.setTimeline(callback, time, value)``](https://github.com/processing/p5.js/compare/master...therewasaguy:domAudioSource?expand=1#diff-84dfcaf5d56a24f4ee13a32c644817b0R1136). [Here's an example](http://therewasaguy.github.io/p5-music-viz/demos/07_lyrics/) that shows lyrics as a song plays.

Curious if anyone has any feedback on this, it could totally change! Also the latter two could potentially live in p5.sound instead of p5.dom, but I think it makes more sense to have all the MediaElement/dom-related stuff in one library.

### CODE REVIEW

**Comment by indefinit** [comment]
Wow nice work on the MediaElement timeline events! This is huge!  Potential really small suggestion re "setTimeline" method naming convention- to me the naming sounds a little confusing, since you're not really setting a timeline but rather scheduling a timeline event.  Maybe scheduleEvent? Or scheduleTimelineEvent is more appropriate?  Really excited to use this!

**Comment by therewasaguy** [comment]
@indefinit I like your suggestion of scheduleEvent or scheduleTimelineEvents.

Another option that seems to resonate is "Cue," recommended by @workergnome and @sarahgp. In my mind that encompasses the idea of an Event happening at a point in Time with just a few characters.

addCue
removeCue
clearCues

Does anybody else have feedback on this syntax for scheduling events to happen at a specific time during media playback in p5.dom?

``var callbackID = myMediaElement.addCue(callback, time, valueToBePassedToTheCallback)``

``myMediaElement.removeCue(callbackID)``

**Comment by therewasaguy** [comment]
Updated syntax based on conversations here at p5con. @antiboredom wanna give this a shot with an audio/video grep?

```
var callbackID = myMediaElement.addCue(timeStamp, myCallback, valueToBePassedToTheCallback)
```

```
function myCallback(value) {
  // do stuff
}
```

**Comment by therewasaguy** [comment]
closing this PR with a rebased version

**Pull request closed without merging**
