### PR TITLE
Two new examples for loadPixels

### PR DESCRIPTION
**Pull request by AdilRabbani**
Added two new examples for loadPixels(). One generates a simple texture using pixels and the other averages image pixels.

### CODE REVIEW

**Comment by limzykenneth** [comment]
In #1954 the `loadPixels()` function that needed example is for the version of `loadPixels()` for the [WebGL renderer](https://github.com/processing/p5.js/blob/master/src/webgl/p5.RendererGL.js#L614) (currently not showing up in the reference because it is marked as a private function, probably still work in progress). I feel we don't need extra example in this instance of `loadPixes()` as it doesn't demonstrate additional functionality of the method that isn't already covered by the original example.

P.S. There seems to be a lot of noise in in the commits that are just adding and removing whitespace.

**Comment by limzykenneth** [comment]
You can run `grunt test` locally to run the same tests that are ran on Travis and you can also run `npm run lint:fix` to try to automatically fix any code style issues.

**Comment by Spongman** [comment]
I think that actually the #1954 issue is in error. The renderer methods are not exposed as part of the API, and _shouldn't_ appear in the reference docs.

The correct list of methods missing examples can be found by running `grunt yui doc:prod`.

**Comment by limzykenneth** [comment]
Yeah, I'm thinking maybe they are outdated since we've only added the `@private` tag recently

**Pull request closed without merging**
