### PR TITLE
Added support for cross origin requests

### PR DESCRIPTION
**Pull request by sc231997**
closes: #3463 

elt.crossOrigin = 'Anonymous' attribute added

### CODE REVIEW

**Comment by sc231997** [comment]
> I think it would be better if you would include a short description along with the issue number in the PR, with the catchphrase "closes: #XXXX", which would help the maintainers to automatically close the related issue 😃. Also the title should not contain just the issue number.

Sorry. Actually, I am new to this. I will keep that in mind from next time.

**Comment by sanketsingh24** [comment]
I think if you would use "closes: #xxxx" or "fixes: #xxxx" it will link the issue.

**Comment by outofambit** [comment]
Thank you for providing some more context @sc231997! and welcome to the p5 repo! 😃

**Comment by lmccart** [comment]
thanks @sc231997!

**Comment by Ajayneethikannan** [comment]
I am very  sorry for commenting on a merged Pull Request, 
I came to know about CORS recently only.
I think setting img.crossOrigin = "Anonymous" always, even if the image is in the same domain,
results in 2 HTTP requests, resulting in unnecessary overhead for same domain images .
(I am not very clear about CORS, please correct me if I am wrong)
If necessary,  we can change it in such a way that we are setting the crossOrigin attribute , only if the src belongs to a different domain.
Thank you!

**Comment by outofambit** [comment]
Hi @Ajayneethikannan, thanks for sharing your concern! Would you please open a new issue for this and we can discuss there? I’m not familiar with that behavior for CORS and I think its worth investigating. Thank you!

**Comment by Ajayneethikannan** [comment]
@outofambit I have opened a new issue, as you suggested for discussion, 
Thank you!

**Pull request merged**
