### PR TITLE
Line.vert fix for small units

### LINKED ISSUE #7200: Line vert shader offsets too much on small coordinates
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [ ] Other (specify if possible)

### p5.js version

1.10.0

### Web browser and version

Chromium: 128.0.6613.85

### Operating system

_No response_

### Steps to reproduce this

The change here #7064 introduced a bug for small coordinates. 

I'm working on updating p5.xr to work with v1.10.0. WebXR uses real world coordinates, as in 1 unit = 1 meter (handy !), so this rendering issue would come up all the time. See the difference with the old shader and the new one:

https://github.com/user-attachments/assets/4e1e6eed-80c3-49bd-b5db-2e5988bc6caa

https://github.com/user-attachments/assets/548fd066-e90c-4ac3-a560-3d40a23024fd

### PR DESCRIPTION
**Pull request by TiborUdvari**
Resolves #7200

Resolves #[Add issue number here]

 Changes:

 Screenshots of the change:

#### PR Checklist

- [ ] `npm run lint` passes
- [ ] [Inline documentation] is included / updated
- [ ] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Comment by perminder-17** [comment]
Hi @TiborUdvari , it's a great work.

Thank you for opening the pull request! I just tested the issues you were facing, specifically the offset for small coordinates being too high. Fortunately, it doesn't seem to reopen the initial issue (https://github.com/processing/p5.js/issues/6956).

Your implementation of `dynamicScale` and `dynamicZAdjustment` is great and working well.

I do have one question regarding the "popping" effect you are talking here https://github.com/processing/p5.js/issues/7200#issuecomment-2326473376. I wasn't able to reproduce it using the code in your PR. Could you share the code where you encountered this effect? Additionally, if it’s still reproducible, does the logic Dave mentioned (`facingCamera == 1.0 ? 1.0 : mix(0.999, 0.995, facingCamera)`) resolve the issue, or do we need to explore other solutions?

**Comment by TiborUdvari** [comment]
I don't think I understood 100% the issues with the popping effects, so I didn't go further on this. What I didn't like about my solution is that it was a mix between two solutions and I didn't understand the whole problem space, so I didn't go further on it. It does apply a quick fix for what we have now though. 

I had to monkey patch p5.xr with the previous version of the shader as a temporary solution, as it really affects most of the AR examples, as they use mostly real world coords, in meters. 

Unfortunately didn't have the time to go deeper on this.

**Comment by perminder-17** [comment]
>  I didn't like about my solution is that it was a mix between two solutions and I didn't understand the whole problem space

This might not be the cleanest solution, but given the current options, I think your solution works well. As for the flickering or popping effects, I couldn't reproduce them on my end. I also reviewed the reference documentation with your code, and everything looks fine to me. Thanks for the fix!

**Review by perminder-17 — APPROVED** [review]
I'll approve this from my side, and the maintainers can update or merge it when they have time.

**Pull request merged**
