### PR TITLE
Fix broken links in contributor_docs/access.md

### LINKED ISSUE #7218: Fix broken links in contributor_docs/access.md
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [X] Other (specify if possible)

### p5.js version

v1.10.0 (latest)

### Web browser and version

Firefox v130.0, though would affect all.

### Operating system

Windows, though would affect all.

### Steps:
1. Go to: https://github.com/processing/p5.js/blob/main/contributor_docs/access.md
2. Click on respective links (listed in table below).
3. Get a 404 or 526 error.

### Solutions:

Replace links to the suggested links below.

| Source link text: | Current link: | Suggested link: |
|---|---|---|
| 2019 Contributors Conference | https://p5js.org/community/contributors-conference-2019.html | https://p5js.org/hi/events/contributors-conference-2019/ |
| p5.js Access Day 2022 | https://p5js.org/community/p5js-access-day-2022.html | https://p5js.org/events/p5js-access-day-2022/ |
| I am Disabled: On Identity-First Versus People-First Language | https://thebodyisnotanapology.com/magazine/i-am-disabled-on-identity-first-versus-people-first-language/ | Remove citation |
|  |  |  |
|  |  |  |

Note: I am not sure how to handle the "I am Disabled: On Identity-First Versus People-First Language" link. The original linked site (https://thebodyisnotanapology.com/) is non-existant. I did a quick Google search, and the page results all reference thebodyisnotapolgy.com to read more. Since the citation (below) also references another (working) article, I suggest removing the article with the broken link. 

>There are differing preferences between ‘person-first’ vs. ‘identity-first’ language within the disability community. Read [Unpacking the debate over person-first vs. identity-first language in the autism community](https://news.northeastern.edu/2018/07/12/unpacking-the-debate-over-person-first-vs-identity-first-language-in-the-autism-community/) and [I am Disabled: On Identity-First Versus People-First Language](https://thebodyisnotanapology.com/magazine/i-am-disabled-on-identity-first-versus-people-first-language/).

Let me know if the above works, and I'll submit a PR.

### PR DESCRIPTION
**Pull request by aleannab**
Resolves #7218 

Changes:
Updates broken links as suggested.

### CODE REVIEW

**Comment by Qianqianye** [comment]
Thanks @aleannab for the fix.
Hi @natdecker, in the [access statement](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md),  the link in the footer [I am Disabled: On Identity-First Versus People-First Language](https://thebodyisnotanapology.com/magazine/i-am-disabled-on-identity-first-versus-people-first-language/) is not working, do you have any suggestion on a new link? Thank you!

**Comment by visheshrwl** [comment]
@Qianqianye we can use `https://educationonline.ku.edu/community/person-first-vs-identity-first-language`

**Comment by natdecker** [comment]
Aw that’s too bad that link is dead. I had chosen that blog post because it was written by a disabled person sharing her thoughts on the discussion of identity vs. person first language. But I found this other article that I think is even better and also written by a disabled person: https://editorstorontoblog.com/2024/02/23/disability-affirming-language-person-first-versus-identity-first-language/

And this is from Pratt, but it’s pretty good: https://libguides.pratt.edu/c.php?g=1278195&p=9399990

And this is a good guide: https://ogs.ny.gov/system/files/documents/2024/02/person-first-and-identity-first-glossary_english_final.pdf

I think so long as we are making clear that there are differing opinions between the two, that there is not one “right” choice, and that it is best to follow the language a disabled person is using to describe themselves. 

Best,

Nat

**Comment by Qianqianye** [comment]
Thanks @aleannab @visheshrwl @natdecker. I have added the first and third links @natdecker mentioned in the footer.

**Pull request merged**
