### PR TITLE
Check for the existence of _friendlyAutoplayError before calling it

### PR DESCRIPTION
**Pull request by davepagurek**
Resolves https://github.com/processing/p5.js/issues/5820

#### The problem

Sometimes, videos never start playing on mobile. It's a bit flaky, but it seems to happen only if the following conditions are met:
- The video is not cached
- The user has not interacted with the page yet (so, this won't be reproducible in the p5 editor, where you have to click the play button, but is reproducible in codepen)
- p5.min.js is loaded instead of p5.js

I hooked up Firefox mobile on Android to my computer for remote debugging, and found that this is what's happening:
- For whatever reason, when the video isn't fully loaded yet, it throws a NotAllowedError when you immediately tell a video to play even if it would work when you reload the page
- We have existing code to handle this and retry, but before doing so, it tries to run `p5._friendlyAutoplayError()`
- In a minified build, this function doesn't exist, so a new error is thrown
- This interrupts the retry logic and the video never starts

#### The change

I now just check for the existence of `p5._friendlyAutoplayError` before trying to call it, and fall back to a `console.error` otherwise.

I wasn't sure how to add a test for something like this, let me know if you have any suggestions!

#### PR Checklist

- [x] `npm run lint` passes
- [ ] [Inline documentation] is included / updated
- [ ] [Unit tests] are included / updated

### CODE REVIEW

**Comment by Qianqianye** [comment]
Thanks @davepagurek! Hey @outofambit, any suggestions on how to add a test for this? Thank you!

**Comment by davepagurek** [comment]
Sounds good, thanks @outofambit! I've updated the code.

**Comment by msawired** [comment]
Hello, a user reported an issue with videos not playing on OP. I looked into it and found out that this is true for all versions since v1.5.0.
example that works with v1.5.0: https://editor.p5js.org/msawired/sketches/1o2O_6jLY
You can change the p5js version to 1.6.0+ to see that video doesn't work (Tested in Chrome. Safari shows only the first frame for some reason). 
I traced the issue back to this commit so pinning a flag here. ⛳️

**Comment by davepagurek** [comment]
@msawired just to confirm, if you go one commit earlier on `main` (https://github.com/processing/p5.js/commit/19c1c90f1407b02c1028a4c053fdaf73515ba61e), it works?

**Comment by davepagurek** [comment]
It looks like it works if you comment out your call to `movie.size(width, height);` which leads me to believe it's maybe not this change. I'm going to open a new issue here: https://github.com/processing/p5.js/issues/6581

**Comment by msawired** [comment]
I didn’t check on the specific commit, just the version. Looked up the commits, and this one seemed most relevant with v1.5 diff with v1.6. I may be wrong on the specific commit. On Nov 23, 2023, at 14:40, Dave Pagurek ***@***.***> wrote:﻿
It looks like it works if you comment out your call to movie.size(width, height); which leads me to believe it's maybe not this change. I'm going to open a new issue here: #6581

**Pull request merged**
