### PR TITLE
Fix uncaught "Failed to fetch"

### LINKED ISSUE #5105: loadImage causes Uncaught (in promise) TypeError: Failed to fetch
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [x] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: 1.3.0
- Web browser and version: Electron (Chromium) 10.3.2
- Operating System: Windows & MacOS
- Steps to reproduce this: Disconnect from the internet and use loadImage()

The fetch() in loadImage() does not include a .catch()

Will provide a PR

### PR DESCRIPTION
**Pull request by JuanIrache**
Resolves #5105

 Changes:
Add .catch() to fetch function in loadImage

#### PR Checklist

- [x] `npm run lint` passes
- [x] [Inline documentation] is included / updated
- [x] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Comment by limzykenneth** [comment]
Hi @JuanIrache, can the additional changes be reverted and just keeping the addition of a `catch` block? Or is there some other reason for the additional changes?

**Comment by JuanIrache** [comment]
@limzykenneth Yes. The second commit is just formatting. Otherwise npm run lint was not passing. I literally just applied the changes lint was suggesting.

Should I revert that one and submit the PR again? (Even with lint not passing)

**Review by outofambit — APPROVED** [review]
this seems reasonable and safe to me! i was able to filter out the whitespace changes for review with https://github.com/processing/p5.js/pull/5106/files?diff=unified&w=1

i feel like [this code](https://github.com/processing/p5.js/blob/c86c76cdd93c1b6ca4e646b56610262aa261f467/src/image/loading_displaying.js#L128-L135) was originally supposed to cover this case, but i cannot figure out how it would actually get called. regardless, the fetch itself can fail and this is the right error message to use.

thanks @JuanIrache !

**Comment by JuanIrache** [comment]
Thank you @outofambit & @lmccart . Glad I could contribute a little bit.

I'm not sure this is the right place to ask, but how could I use a "built" version of p5 with this patch included? I usually just npm install it. With some libraries you could just "npm install processing/p5.js" to get the github version, but in this case that does not get the right (built?) structure. Or maybe you could point me to instructions on how to build it myself? Appreciated.

**Comment by lmccart** [comment]
hi @JuanIrache, we don't distribute nightly or in progress builds between releases, but you can build it yourself. if you run `npm run grunt` it should build the library and places the files in the `lib/` folder

**Comment by JuanIrache** [comment]
Thank you!

**Pull request merged**
