### PR TITLE
Tweak to loadFont and clean-up tests

### PR DESCRIPTION
**Pull request by dhowe**
Break out font-tests into a separate file with suites for both preload and callback-style calls;
   see test/unit/typography/font_loading.js

Added optional 2nd callback to p5.loadFont() for error-handling

### CODE REVIEW

**Comment by lmccart** [comment]
do you mind rebasing or syncing up with the newest? I tried and thought I knew how to resolve the conflict but I'm still getting a failed test.

**Comment by dhowe** [comment]
will do

**Comment by dhowe** [comment]
should be good now

**Comment by lmccart** [comment]
thanks!

**Pull request merged**
