### PR TITLE
Include OpenType within the built library file (fixes #781)

### LINKED ISSUE #781: Integrate OpenType into built library?
@dhowe Back in May we looked at issues relating to AMDClean and OpenType that required us to concatenate the files vs including opentype directly. I'd like to understand better how we're using OpenType within p5, so that (in our new, post-#776 browserify world) we can return to this issue and better integrate the two if appropriate.

### PR DESCRIPTION
**Pull request by kadamwhite**
Concatenating OpenType.js onto the end of our module was meant only to be a temporary measure to work around issues where the requirejs build would blow up when trying to include OpenType. Now that we are no longer using RequireJS, we can require the dependency directly, bundle it into our released lib, and manage it all via NPM/browserify.
    
@dhowe Please review and give this a thorough field test, if you can; this PR adds a test to validate that `loadFont` works correctly, but I haven't done any more rigorous testing of the font code!
    
This PR is built upon #827, so that PR should be merged prior to merging this :)

### CODE REVIEW

**Comment by kadamwhite** [comment]
For a diff of only the non-#827 changes:

(removed src/external wholesale)
```diff
diff --git a/Gruntfile.js b/Gruntfile.js
index 1e03d0a..2e7b7cc 100644
--- a/Gruntfile.js
+++ b/Gruntfile.js
@@ -177,18 +177,6 @@ module.exports = function(grunt) {
       }
     },
 
-    // Concatenate p5 together with OpenType
-    // TODO: There may be an opportunity to move this into the main p5 build
-    concat: {
-      p5: {
-        src: [
-          'lib/p5.js',
-          'src/external/opentype.min.js'
-        ],
-        dest: 'lib/p5.js',
-      },
-    },
-
     // The actual compile step:  This should collect all the dependencies
     // and compile them into a single file.
     requirejs: {
@@ -273,7 +261,6 @@ module.exports = function(grunt) {
 
   // Load the external libraries used.
   grunt.loadNpmTasks('grunt-browserify');
-  grunt.loadNpmTasks('grunt-contrib-concat');
   grunt.loadNpmTasks('grunt-jscs');
   grunt.loadNpmTasks('grunt-contrib-jshint');
   grunt.loadNpmTasks('grunt-contrib-watch');
@@ -287,7 +274,7 @@ module.exports = function(grunt) {
 
   // Create the multitasks.
   // TODO: "requirejs" is in here to run the "yuidoc_themes" subtask. Is this needed?
-  grunt.registerTask('build', ['browserify', 'concat', 'uglify', 'requirejs']);
+  grunt.registerTask('build', ['browserify', 'uglify', 'requirejs']);
   grunt.registerTask('test', ['jshint', 'jscs', 'build', 'connect', 'mocha']);
   grunt.registerTask('test:nobuild', ['jshint:test', 'jscs:test', 'connect', 'mocha']);
   grunt.registerTask('yui', ['yuidoc']);
diff --git a/package.json b/package.json
index bacb076..94ceb26 100644
--- a/package.json
+++ b/package.json
@@ -40,6 +40,7 @@
   ],
   "dependencies": {
     "brfs": "^1.4.0",
+    "opentype.js": "^0.4.9",
     "reqwest": "^1.1.5"
   },
   "main": "./lib/p5.js",
diff --git a/src/io/files.js b/src/io/files.js
index 632d05e..5dc786b 100644
--- a/src/io/files.js
+++ b/src/io/files.js
@@ -1,5 +1,3 @@
-/* global opentype:false */
-
 /**
  * @module IO
  * @submodule Input
@@ -12,6 +10,7 @@
 
 var p5 = require('../core/core');
 var reqwest = require('reqwest');
+var opentype = require('opentype.js');
 require('../core/error_helpers');
 
 
@@ -29,8 +28,8 @@ require('../core/error_helpers');
  * @return {Object}                   p5.Font object
  * @example
  *
- * <p>Calling loadFont() inside preload() guarantees to complete the
- * operation before setup() and draw() are called.</p>
+ * <p>Calling loadFont() inside preload() guarantees that the load
+ * operation will have completed before setup() and draw() are called.</p>
  *
  * <div><code>
  * var myFont;
diff --git a/test/unit/io/files_input.js b/test/unit/io/files_input.js
index c82febb..539326b 100644
--- a/test/unit/io/files_input.js
+++ b/test/unit/io/files_input.js
@@ -1,5 +1,3 @@
-/* global opentype: false */
-
 suite('Files', function() {
 
   var loadJSON = p5.prototype.loadJSON;
@@ -18,12 +16,6 @@ suite('Files', function() {
   });
 
   suite('loadFont() in Preload', function () {
-
-    test('should be opentype', function() {
-      assert.ok(opentype);
-      assert.isObject(opentype);
-    });
-
     test('should be a function', function() {
       assert.ok(loadFont);
       assert.typeOf(loadFont, 'function');
@@ -34,6 +26,14 @@ suite('Files', function() {
       assert.ok(result);
       assert.isObject(result);
     });
+
+    test('should load the font', function(done) {
+      result = loadFont('/test/unit/assets/acmesa.ttf', function() {
+        assert.typeOf(result.font, 'object');
+        assert.equal(result.font.familyName, 'A.C.M.E. Secret Agent');
+        done();
+      });
+    });
   });
 
   suite('loadJSON() in Preload', function () {

```

**Comment by kadamwhite** [comment]
@lmccart @dhowe What more needs to be done here? I've tested `loadFont` locally in a variety of scenarios, as well as `textBounds`—it looks like opentype objects are being properly constructed. If there's anything else that needs to be tested, let me know.

**Comment by dhowe** [comment]
Have you been able to test font-loading via preload() from within our mocha tests? This is one item still on my list... In fact, as best I can tell we're not testing any of our registered preload functions ("loadJSON", "loadImage", "loadStrings", "loadXML", "loadShape", "loadTable", "loadFont") in our unit tests -- at least not from preload(), though there is code that might have done this once (see test/unit/io/files_input.js)..

**Comment by kadamwhite** [comment]
@dhowe I will take a look tomorrow or Thursday; thanks for flagging that, I see the code you're referencing.

As an aside, these loading tests require served assets to be available and therefore are the reason we run the specs on the connect server. Long-term I'm wondering if it would make sense to make two suites of tests, one that requires the connect server and one that does not? The former could potentially be executed more rapidly and could provide better performance in the context of a watch task. Thoughts, @lmccart @therewasaguy @dhowe @shiffman ?

**Comment by lmccart** [comment]
thanks for working on this @kadamwhite, it looks good to me and I'm ready to merge whenever @dhowe gives the go ahead. 

I like the idea of separating into two test suites.

**Comment by dhowe** [comment]
Looks good to me as well. The main pending issue (as I mention above) is preload testing, but this is not specific to opentype or font-loading, so we can address it post-merge. You should also be able to merge #835 (either before or after this one)

**Comment by lmccart** [comment]
hm just merged this but when I run grunt I'm getting error `Running "browserify:p5" (browserify) task
>> Error: Cannot find module 'opentype.js' from '/Users/lmccart/Documents/p5/p5.js/src/io'`

**Comment by dhowe** [comment]
did you run 'npm install'?

**Comment by lmccart** [comment]
derp, thanks. sorry! all good.

**Comment by dhowe** [comment]
cool, and when you merge #835, then unit test should start to pass again (this fails now: http://localhost/git/p5.js/test/test.html?grep=Files)

**Pull request merged**
