### PR TITLE
update p5.sound v0.3.2

### PR DESCRIPTION
**Pull request by therewasaguy**
* New FFT methods by @mkontogiannis
  * getOctaveBands
  * linAverages
  * logAverages

* SoundFile `onended` does not trigger on pause, fix by @aksperiod 

* Remove calls to `AudioContext.prototype.hasOwnProperty` in case [this](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/QOR76GjwrkA) is an issue

### CODE REVIEW

**Comment by lmccart** [comment]
👍

**Comment by Burans** [comment]
Could someone clarify please -  is `onended` supposed to be triggered on pause or is that a bug? Im using v0.3.2 2016-11-01. Thank you!

**Comment by aksperiod** [comment]
@Burans I fixed this in https://github.com/processing/p5.js-sound/pull/142. On my phone right now so can't check what happened, but it did get merged.

**Comment by Burans** [comment]
@aksperiod Thanks for the reply. I isolated the functionality to test if the problem was not my code. This example triggers `soundStopped` function both on stop and pause.  I'm using v0.3.2 2016-11-01
```
var sound;

function preload(){
    sound = loadSound('sound.mp3');
}
function setup(){
    sound.onended(soundStopped);
    sound.play();
}
function mousePressed(){
    sound.stop();
}
function keyPressed(){
    sound.pause();
}
function soundStopped(){
    console.log('stopped');
}
```

**Pull request merged**
