### PR TITLE
Minor corrections regarding of the text function.

### PR DESCRIPTION
**Pull request by inaridarkfox4231**
there are two problems:

1. If you specify CENTER or BOTTOM for the second argument of textAlign without the 4th and 5th arguments of the text function, some lines will disappear.
2. If CENTER is specified for rectMode, some lines may disappear when box is set by the text function.

These fixes are meant to resolve these issues.

Resolves: #5880

 Changes:

[sampleCode for problem 1](https://editor.p5js.org/dark_fox/sketches/I6E6F_Bzh)
```javascript
function setup() {
  createCanvas(400, 400);
  background(0);
  noStroke();
  fill(255);

  textSize(18);
  textAlign(CENTER, TOP);
  text("first\nsecond\nthird", 80, 200);
  textAlign(CENTER, BASELINE);
  text("first\nsecond\nthird", 160, 200);
  textAlign(CENTER, BOTTOM);
  text("first\nsecond\nthird", 240, 200);
  textAlign(CENTER, CENTER);
  text("first\nsecond\nthird", 320, 200);

  textSize(14);
  text("TOP", 80, 120);
  text("BASELINE", 160, 120);
  text("BOTTOM", 240, 120);
  text("CENTER", 320, 120);
  stroke(255);
  line(0,200,400,200);
}
```
left: before change. right: after change.
Screenshots of the change:
screenShot1

[sampleCode for problem 2](https://editor.p5js.org/dark_fox/sketches/GFw5zBkaSg)

```javascript
function setup() {
  createCanvas(400, 400);
  background(0);
  noStroke();
  fill(255);
  rectMode(CENTER);

  textSize(24);
  textAlign(CENTER, BASELINE);
  text("first\nsecond\nthird\nfourth", 50, 200, 100, 400);
  textAlign(CENTER, TOP);
  text("first\nsecond\nthird\nfourth", 150, 200, 100, 400);
  textAlign(CENTER, CENTER);
  text("first\nsecond\nthird\nfourth", 250, 200, 100, 400);
  textAlign(CENTER, BOTTOM);
  text("first\nsecond\nthird\nfourth", 350, 200, 100, 400);

  noFill();
  stroke(255);
  rect(50, 200, 100, 400);
  rect(150, 200, 100, 400);
  rect(250, 200, 100, 400);
  rect(350, 200, 100, 400);
}
```

left: before change. right: after change.
Screenshots of the change:
screenShot2

#### PR Checklist

- [x] TypoGraphy

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Review by dhowe — APPROVED** [review]
Looks very good to me. A bit unusual perhaps to put 2 statements on one line (as in 270), but it seems to pass the linter, so all good

**Comment by dhowe** [comment]
@raclim looks good to merge - 2 fixes to live bugs with text-alignment

**Comment by inaridarkfox4231** [comment]
I'm sorry, it would have been better to split it into two lines...is it okay to leave it as is?

**Comment by dhowe** [comment]
Perhaps update the PR -- just for practice :)

**Comment by inaridarkfox4231** [comment]
thank you very much for advice! ('ω')

**Comment by dhowe** [comment]
> thank you very much for advice! ('ω')

thanks for the fix!

**Comment by Qianqianye** [comment]
Thank you @inaridarkfox4231 and @dhowe ✨!

**Pull request merged**
