### PR TITLE
Fixed typo on line 151

### PR DESCRIPTION
**Pull request by tankeith**
Resolves #[Add issue number here]

 Changes:

 Screenshots of the change:

#### PR Checklist

- [ ] `npm run lint` passes
- [ ] [Inline documentation] is included / updated
- [ ] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Review by montoyamoraga — APPROVED** [review]
thanks! this is great :)

**Comment by montoyamoraga** [comment]
@all-contributors please add @tankeith for docs

**Comment by tankeith** [comment]
@montoyamoraga 

Thanks, this was my first ever pull request! :)

**Comment by montoyamoraga** [comment]
@tankeith congrats, you did great ~

**Pull request merged**
