### PR TITLE
Fix loadShader preload

### PR DESCRIPTION
**Pull request by Spongman**
from #2717, just the `loadShader` preload fix.

### CODE REVIEW

**Comment by lmccart** [comment]
thanks. i don't see an issue associated with this, please open one first. thanks

**Comment by lmccart** [comment]
i guess i'm unclear why that issue is closed then. please reopen if it's not fixed yet and tag this PR with that issue in the description. thanks.

**Comment by Spongman** [comment]
i cannot re-open an issue that i did not close.

**Comment by lmccart** [comment]
i feel like you are being argumentative here and it is stressful. i am trying to merge the high volume of pull requests you have submitted and make sure that the changes and decisions behind them are documented. if you can't reopen that issue, you could open a new one to explain which part is not yet fixed. thank you.

**Comment by Spongman** [comment]
on the contrary, i'm trying to do what you ask. however, in this case, i'm unable to do so because github won't allow me. maybe i misunderstood your instructions.

**Comment by Spongman** [comment]
closes #2821

**Pull request merged**
