### PR TITLE
p5.Graphics and setAttributes

### LINKED ISSUE #3836: setAttributes() breaks rendering of WebGL p5.Graphics
While working on another issue I noticed that `setAttributes()` causes errors with p5.Graphics objects. I have a working branch where I have partially fixed this. In my branch, I have this working:

```
let pg;
function setup() {
  createCanvas(500,500);
  background(0,0,255);
  pg = createGraphics(250, 500, WEBGL);
  pg.setAttributes('alpha', true);
  pg.clear();
  pg.box(100);
}
```
but the rendering is still a bit off when both canvases are 3D as in:
```
let pg;
function setup() {
  createCanvas(500,500, WEBGL);
  background(0,0,255);
  pg = createGraphics(250, 500, WEBGL);
  pg.setAttributes('alpha', true);
  pg.clear();
  pg.box(100);
}
```
I will fix this part as well and open a PR soon. I just wanted an open issue to track this work.

### PR DESCRIPTION
**Pull request by stalgiag**
fixes #3836

Now every combination of 2D and 3D canvases and graphics objects work together with modified and unmodified attributes.

### CODE REVIEW

**Comment by themike27** [comment]
I think this isn't working again.
When I put `pg.setAttributes('alpha', true);` it returns me this error: `Uncaught TypeError: Cannot read property 'push' of undefined`

**Comment by stalgiag** [comment]
Hi @themike27 are you sure that you are using the most recent version of p5? [Here is a working example.](https://editor.p5js.org/stalgiag/sketches/ApPPeBo7K) If you are using the most recent version and you are still experiencing the problem, please open an issue with a code example. Thanks!

**Comment by themike27** [comment]
Oh I just saw that the command `npm i p5` installs the `0.8.0` (six months ago) and not the lastest `0.9.0` (three months ago), do you know how can I install the latest through `npm`?

**Comment by stalgiag** [comment]
Hm odd. You can try `npm install p5@0.9.0`

**Comment by themike27** [comment]
Yes! That was it! Thank you so much!

**Pull request merged**
