### PR TITLE
Check for per vertex transparency when blending

### PR DESCRIPTION
**Pull request by davepagurek**
Resolves https://github.com/processing/p5.js/issues/6539

### Changes
- Checks (and caches) whether any per vertex colors include transparency
- Enables blending if that is true

### Screenshots of the change

Before:
image

After:
image

Live: https://editor.p5js.org/davepagurek/sketches/QFQV0_K_E

#### PR Checklist

- [x] `npm run lint` passes
- [x] [Inline documentation] is included / updated
- [x] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Comment by Qianqianye** [comment]
Thanks @davepagurek. @acamposuribe, could you help review this PR since you opened the related issue? Thanks!

**Comment by davepagurek** [comment]
Tagging other WebGL stewards and contributors, let me know what you think! @aferriss, @aceslowman, @ShenpaiSharma, @ChihYungChang, @teragramgius, @JazerUCSB, @richardegil, @itsjoopark, @Gaurav-1306, @jeanetteandrews, @perminder-17

**Review by aferriss — APPROVED** [review]
Looks great! Thanks Dave!

**Review by perminder-17 — APPROVED** [review]
Looks good to me. I think we are good to merge. Thanks.

**Comment by davepagurek** [comment]
Thanks everyone!

**Pull request merged**
