### PR TITLE
Documentation for clear()

### PR DESCRIPTION
**Pull request by ashwathbhat**
Fix for #3545

### CODE REVIEW

**Comment by ashwathbhat** [comment]
@stalgiag Would be nice if you could help me out a bit here.

**Comment by stalgiag** [comment]
Hi @ashwathbhat this is close. Just as a rule of thumb your branch should always pass the linting and tests that are run when you run `npm run grunt`. [Check out the developer docs](https://github.com/processing/p5.js/tree/master/developer_docs) for more info. In this case, these tests aren't passing because of a simple formatting issue. Here is the console output:
```
<myDevelopmentDirectory>\p5.js\src\color\setting.js:186:76: Delete `·` [Error/prettier/prettier]
<myDevelopmentDirectory>\p5.js\src\color\setting.js:187:66: Delete `·` [Error/prettier/prettier]
<myDevelopmentDirectory>\p5.js\src\color\setting.js:189:81: Delete `·` [Error/prettier/prettier]
```
This is because there is a space before the new line on lines 186, 187, and 189. These kind of formatting issues can be auto-fixed with `npm run lint:fix`. 

Also just another small note, it would be a good idea to get rid of the word function after 'createDiv' in your changes for grammar reasons. 

When you are done making these minor changes, you can run `npm docs:dev` and check out the reference example for clear and make sure that your explanation of the function looks good, then push to your 'patch-2' branch and it will automatically update this PR.

**Comment by ashwathbhat** [comment]
Hi @stalgiag. Thank you for guiding me on this. I went through the developer docs and will now make suitable changes and update it here.

**Comment by stalgiag** [comment]
Great! Thanks @ashwathbhat

**Pull request merged**
