### PR TITLE
Renderers: sphere and cube primitives

### PR DESCRIPTION
**Pull request by indefinit**

### CODE REVIEW

**Comment by kadamwhite** [comment]
This changed the file mode on a lot of files, e.g. changing the gruntfile to 755 from 644 -- that seems unrelated to this change, and possibly unnecessary, so it's worth keeping an eye on that in future diffs.

**Comment by indefinit** [comment]
Hmm, ok I can take a look again.  I had merged back the changes from master so they were at parity with that branch and added a PR from Karenpeng on my fork so perhaps something got added in the shuffle?

**Comment by indefinit** [comment]
Thinking about this some more and considering the dev ops conversations we had this week, maybe it makes sense for us to remove the renderers branch altogether and work off the master after the remaining changes are pulled in.  For webgl we won't need to touch the gruntfile, or other Graphics2D based objects so it would seem like a fail safe to cut the cord and work off the most updated branch.  @K.Adam White, what do you think?

**Comment by lmccart** [comment]
i think this makes sense, just to avoid the chance of diverging branches. this means we can delete the renderers branch, too i guess?

**Comment by indefinit** [comment]
Yea let's get rid of renderers and we can submit PRs on Master from now on.

**Pull request merged**
