### PR TITLE
Commit package-lock.json

### PR DESCRIPTION
**Pull request by limzykenneth**
Commit package-lock.json for npm 5. I don't expect problem with the dependency tree but it may be best to try out this fork first before merging.

### CODE REVIEW

**Comment by limzykenneth** [comment]
I may have messed something up as the test is not passing but I'm not sure exactly what... 😞

**Comment by Zalastax** [comment]
Great idea!
Before merging read my comment on the choice your making then: https://github.com/processing/p5.js/pull/2362#issuecomment-344681398. I'm fine with both choices as long as you know that you're making it.

I guess you could rebase the commit and push it again if you want to trigger a rebuild. Or someone with Travis rights could do it. I think it needs to be updated for the latest package.json anyways.

**Comment by limzykenneth** [comment]
@Zalastax i have travis rights but it is trying to test a branch that doesn't exist so it won't pass either way, I think it's ok to ignore it. 😜 

And yeah, do decide if npm or yarn lock file are preferred. I personally prefer npm as that feels more like a standard.

**Comment by lmccart** [comment]
I agree, I'd like to stick with npm. I've just pushed the latest copy of package-lock.json so I will close this pr. thanks!

**Pull request closed without merging**
