### PR TITLE
Automating the release process

### PR DESCRIPTION
**Pull request by sakshamsaxena**
Referencing #707 as it was the main inspiration behind this PR.

#### Chores
* Added `empty-example` folder in `lib` with an empty `sketch.js` and a basic `index.html`. This goes into the ZIP which we put up in the GitHub Release. Also useful for anyone who wants to quickly write up some test code.
* Removed `.gitkeep` (actually that went in a bit too early at 61f9ce425dc34a2302bb36a9f13eb62ae543bcd9) 
* JSHint now understands ES6 shenanigans 
* Moved all the Grunt Tasks to a new folder `tasks`
* `loadNPMTasks` are now arranged in alphabetical order ( :sweat_smile: )

#### Features
Implemented a Grunt Task which uses sub tasks to draft and cut a release end-to-end. The entire process broken down :
* Run the Test Suite
* Run the [Release-It](https://github.com/webpro/grunt-release-it) Task
    * Version Increment (__is provided as an argument__)
    * Building Library and Docs
    * Committing and Tagging
    * Pushing 
    * Release on NPM
* Push the newly built library to [p5.js-release](https://github.com/lmccart/p5.js-release) repo for Bower
* Push the newly built reference to [p5.js-website](https://github.com/processing/p5.js-website)
* Create a Zip file `p5.zip` of `lib` folder, which would be used in the GitHub Release
* Create a release with the latest tag (__no changelog for now__)
* Upload the Library files and the ZIP file to the GitHub Release.

#### Requirements
* Logged in NPM CLI : Check if you are logged in by `npm whoami`
* High Bandwidth : Lots of things to download/pull/push (~190 MB total I presume)
* An environment variable named __GITHUB_TOKEN__ with the value of your Access Token : Make one by going [here](https://github.com/settings/tokens). Once you have it, in your shell, run `export GITHUB_TOKEN=<your token here>`.

#### Usage
`grunt release-p5:VALID_SEMVER`
May require you to enter username/password while pushing/pulling to repos.

### CODE REVIEW

**Comment by lmccart** [comment]
🎉 🎉 🎉 yes!!! 👏 👏 👏

**Comment by lmccart** [comment]
this worked great! I had to make one small change to get it to run on my machine. when you have a chance, can you pull the latest and confirm that this change works on yours as well? https://github.com/processing/p5.js/commit/2576f52b7f5335ebe8c9da9ab68ae67f4bc7b28b

**Comment by sakshamsaxena** [comment]
Oh my! Thank You! I'm glad it worked well! 
Sure I'll let you know about it soon! Thanks again !

**Comment by sakshamsaxena** [comment]
> this worked great! I had to make one small change to get it to run on my machine. when you have a chance, can you pull the latest and confirm that this change works on yours as well? 2576f52

I see. On my Ubuntu, `cp` from GNU coreutils is used, and there is absolutely no difference between `-r, -R, --recursive` ([man page](https://www.gnu.org/software/coreutils/manual/html_node/cp-invocation.html#cp-invocation)). However, in OSX systems, the BSD version of `cp` is usedwhich doesn't have either `-r` or `--recursive` ([man page](https://www.freebsd.org/cgi/man.cgi?cp)). So yes your fix makes it universal as `-R` is supported in both versions. We're good to go!

Also, a bit off track, but would like to share this anyway : [https://jondavidjohn.com/linux-vs-osx-the-cp-command/](https://jondavidjohn.com/linux-vs-osx-the-cp-command/)

**Comment by lmccart** [comment]
ah cool, I figured it was probably something like that. thanks for the reference link

**Pull request merged**
