### PR TITLE
Fixed failing test case in p5.texture

### PR DESCRIPTION
**Pull request by sanketsingh24**
Fixes: #3555

Fixed failing test cases, and a typo (Instead of checking height, It was set to width).

### CODE REVIEW

**Comment by sanketsingh24** [comment]
For some reason, these tests were failing before in my local machine, not now, but are failing in travis build now :anger: I'll see into this.

**Comment by stalgiag** [comment]
Hi @sanketsingh24 I think this change should happen as that looks like a typo but probably not the reason for #3555

**Comment by sanketsingh24** [comment]
Yea got that a little late :sweat: fixing #3555 now and then will review your PR

**Comment by sanketsingh24** [comment]
These checks don't fail in my local machine now, ran both node v8.15.0 & v10.15.2, so I am removing the link and just fixing the typo.

**Comment by stalgiag** [comment]
Perfect thanks @sanketsingh24!

I think that eventually these tests should use the  `promisedSketch` / `testSketchWithPromise` methods as @meiamsome suggested in #3555 but I am going to merge this now and open an issue for that change. Thanks again!

**Comment by sanketsingh24** [comment]
I also thought that, but due to urgency, I just went with this implementation. :+1:

**Pull request merged**
