### PR TITLE
use es6-style class for some classes.

### LINKED ISSUE #3758: ES6 Transition: Concerns & Progress
Hello everyone! 

I'm investigating the means of fully transitioning p5 to ES6. I've already spoken to some of the developers outside of Github and was hoping to shine some light on some of the intricacies that I've observed in the code.

I've noticed there are 42 instances of `module.exports = p5;` in the bundled .js files. And I hope this issue serves as a clarification of the assumption that I have:

From what I understand each `module.exports = p5;` is effectively exposing p5 after extending it in its own respected files/module, be it curves.js, vertex.js, etc. 

Although what seems to be the case is that most modules usually inherit/require from main.js, there are few instances of sequential inheritance of p5. 

For instance:
In `string_functions.js` we have:
```
var p5 = require('../core/main');
require('../core/error_helpers');
....
module.exports = p5;
```
Both `main` and `error_helpers` have their own respective `modules.exports = p5`. However `string_functions` is exporting the instance of p5 inheritted from `main`.

My question in regards to this specific instance is by the end of `string_functions` when we are exporting p5, will this instance have all the prototypal functions defined in `error_helpers`? 

From my understanding, the inheritance scheme seems to be a directed acyclical graph with a single root node (`main.js` - **A** in picture) and a single leaf node which is p5 at its final stage after all the additions to the prototype occur in multiple files ( **F** in picture or equivalently `p5()` in browser).

1sQcP

I know javascript is independent of the order the code is written unlike C++, and instances and references are resolved during JIT. Given that there are 42 instances of `module.exports=p5` in the bundled lib, how is each instance resolved properly? Is each instance unique, with functionalities unavailable in preceding exports or do they all refer to the same class for lack of a better word?

Moreover given the `import` syntax in ES6, how does this export/require paradigm change, if it does?

Apologies in advance if these questions seem trivial or show a lack of knowledge in JS. I come from different programming languages and JS seems like wild west to me!

Edit: I'm unable to appropriately label my issue. I assume it should be considered a "discussion".

### PR DESCRIPTION
**Pull request by wuyudi**
Resolves #3758

make up for https://github.com/processing/p5.js/pull/3874

 Changes:

use es6-style class for some classes.

 Screenshots of the change:

#### PR Checklist

- [x] `npm run lint` passes
- [x] [Inline documentation] is included / updated
- [x] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Comment by wuyudi** [comment]
p5.Renderer.js and p5.Renderer2D.js seem have some confusing errors, so I didn't port them.

```js
p5.Renderer = class extends p5.Element {
  constructor(elt, pInst, isMainCanvas){
    super(elt, pInst);
    this.canvas = elt;
    this._pixelsState = pInst;
    if (isMainCanvas) {
      this._isMainCanvas = true;
      // for pixel method sharing with pimage
      this._pInst._setProperty('_curElement', this);
      this._pInst._setProperty('canvas', this.canvas);
      this._pInst._setProperty('width', this.width);
      this._pInst._setProperty('height', this.height);
    } else {
    // hide if offscreen buffer by default
      this.canvas.style.display = 'none';
      this._styles = []; // non-main elt styles stored in p5.Renderer
    }

    this._textSize = 12;
    this._textLeading = 15;
    this._textFont = 'sans-serif';
    this._textStyle = constants.NORMAL;
    this._textAscent = null;
    this._textDescent = null;
    this._textAlign = constants.LEFT;
    this._textBaseline = constants.BASELINE;
    this._textWrap = constants.WORD;

    this._rectMode = constants.CORNER;
    this._ellipseMode = constants.CENTER;
    this._curveTightness = 0;
    this._imageMode = constants.CORNER;

    this._tint = null;
    this._doStroke = true;
    this._doFill = true;
    this._strokeSet = false;
    this._fillSet = false;
    this._leadingSet = false;
  }
};
```

will throw a lot of errors.

---

```js
p5.Renderer2D = class extends p5.Renderer {
  constructor(elt, pInst, isMainCanvas){
    super(elt, pInst, isMainCanvas);
    this.drawingContext = this.canvas.getContext('2d');
    this._pInst._setProperty('drawingContext', this.drawingContext);
    return this;
  }
};
```

will give 

```
  1782 passing (20s)
  10 pending
  1 failing
  1) Global Error Handling
       identifies errors happenning internally:

      AssertionError: expected 2 to equal 1
      + expected - actual

      -2
      +1
      
      at assert.strictEqual (http://localhost:9001/node_modules/chai/chai.js:2329:32)
      at http://localhost:9001/test/unit/core/error_helpers.js:564:14
```

**Comment by limzykenneth** [comment]
@wuyudi I'm getting a test error when running locally

```
1) loading images
       animated gifs animate correctly:
     AssertionError: expected 0 to equal 1
      at http://localhost:9001/test/unit/image/loading.js:138:14
```

I'll see if I can find out what it is. The reason CI is passing but not locally might be related to the very old version of nodejs being used in CI. I'll be doing some CI update today as well.

**Comment by limzykenneth** [comment]
Just test things out more thoroughly, the test fail I'm seeing seems to be coming from and fixed in the main branch. I'll merge this then. @wuyudi Feel free to look into working on converting p5.Renderer as well with @davepagurek if you wish. Thanks!

**Comment by wuyudi** [comment]
ok, since GSoC is coming, so I made a proposal on the processing formula. https://discourse.processing.org/t/gsoc-2023-join-the-processing-foundation-as-a-summer-of-code-contributor/40986/92, hoping I can work on this with @davepagurek

**Pull request merged**
