### PR TITLE
Multidimensional Support for dist()

### PR DESCRIPTION
**Pull request by max0410**
Dist() function now returns the euclidean distance of the inputs, allowing the function to calculate any dimensional distance.

### CODE REVIEW

**Comment by lmccart** [comment]
looks great, thanks!

**Comment by lmccart** [comment]
I'm sorry, I had to roll back these changes because it didn't pass the unit tests. Can you please try running `grunt` and confirming all the tests are successful, then create a new PR? Thanks! More info about grunt [here](https://github.com/processing/p5.js/wiki/development).

**Comment by max0410** [comment]
Will do!

**Comment by Smilebags** [comment]
Not sure if this was in response to my question at #1707 or not, but seems to be addressing the same feature request. I just thought I would notify you that I've created a repo to be used as an addon, as suggested by @limzykenneth. https://github.com/Smilebags/p5.dimensions.js

The code doesn't seem as clean as yours, @max0410, so if you wanted to implement more efficient code in my repo I'd be more than willing to merge it. It might help the unit test failures here, since I'm not changing any p5 core functions.

P.S. is creating a new repo the right way to create an addon for p5?? I'm new to all of this.

**Comment by max0410** [comment]
Sure, I'd love to implement it into your repo! Though I would still have to edit the unit tests, because the old unit tests are configured to the "Math.hypot()" function. The only problem is that my code can't pass the overflowing and under flowing tests, though I don't believe they are that important. What do you think about the under and over flowing tests before I make a Pull Request for your repo?

**Comment by max0410** [comment]
@Smilebags I created the pull request, I shortened both the distance function, and the vector object initiator.

**Comment by Smilebags** [comment]
Yeah, that's one of the reasons I decided to create an addon rather than pushing to p5.

Thanks for the PR, I will have a look now.

**Pull request merged**
