### PR TITLE
Volunteering for stewards

### PR DESCRIPTION
**Pull request by outofambit**
Added myself to the stewards list in the readme and included a couple areas I'm familiar with! 💟

### CODE REVIEW

**Review by montoyamoraga — APPROVED** [review]
i approve and celebrate this :)

**Comment by limzykenneth** [comment]
Awesome, shall we formalized the list of areas that stewards can (erm...) steward? Ideally I'm thinking of having it match the issue template so it's clear who to contact if someone filing the issue wants to attract the attention of a steward.

**Comment by outofambit** [comment]
> I'm thinking of having it match the issue template so it's clear who to contact if someone filing the issue wants to attract the attention of a steward.

ohh that's a really good idea 😅 i hadn't thought of that. i can revise this to match our issue template categories!

**Comment by outofambit** [comment]
ok i updated it but there were some areas i wanted to mention that aren't on the issue template. @limzykenneth do you think i should add build process, localization tools, unit testing, and friendly errors to the issue templates too?

**Review by montoyamoraga — APPROVED** [review]
great!

**Comment by limzykenneth** [comment]
@outofambit Yeah, those should be added as well. For the website I'm wondering should it be listed here or separately on the website's repo?

**Comment by lmccart** [comment]
@limzykenneth I think here makes sense, and then we can add a note/link in the readme from p5.js-website to this info.

**Comment by limzykenneth** [comment]
I may change the format up a bit so it's more organized, will file a PR when done.

**Pull request merged**
