### PR TITLE
bug in angleBetween() #3973

### PR DESCRIPTION
**Pull request by CrypticGuy**
Hi, 
I've added the changes as discussed in the issue section. I have added a boolean parameter to the function `angleBetween()` for vectors. When set to true absolute value of the angle between them is returned and when set to false the angle between is returned keeping in consideration the sign in a 2D plane.

### CODE REVIEW

**Comment by 0x69** [comment]
Nice. Should I close issue #3973 now or should I wait merging branch into main or something ?

**Comment by stalgiag** [comment]
Thanks @CrypticGuy !  I realized that the next release is a minor release so it is okay to break backwards compatibility on a function like this. Especially if the fix is simple as with this case (using `abs()`. With that in mind, I think the added parameter might not be necessary. Would you mind removing it and just keeping the logic for evaluating the sign of the return value?

**Comment by CrypticGuy** [comment]
> Thanks @CrypticGuy ! I realized that the next release is a minor release so it is okay to break backwards compatibility on a function like this. Especially if the fix is simple as with this case (using `abs()`. With that in mind, I think the added parameter might not be necessary. Would you mind removing it and just keeping the logic for evaluating the sign of the return value?

Hi @stalgiag 
So, just to confirm, you want me to remove the extra boolean parameter and return the values with the sign. So, if anyone wants to use the function and need the absolute value they can wrap it in `abs()` on their own?

**Comment by stalgiag** [comment]
Hi @CrypticGuy yes that is correct! Thank you!

**Comment by CrypticGuy** [comment]
Hi @stalgiag , 
Sorry for the late response. If I remove the functionality won't it affect the existing test? Should I override them with new expected values or should I modify them with a wrapper of abs() around them?

**Comment by CrypticGuy** [comment]
Hi @stalgiag , 
I have modified the test cases as the build was failing otherwise. 
Currently I have wrapped `angleBetween()` `call in Math.abs()`

**Comment by stalgiag** [comment]
Hi @CrypticGuy this is good for some of the unit tests, but maybe just to make sure that the full -PI to PI range is working, you could replace one or two of the tests with a test that has a value that results in a value between 0 and -PI. Does that make sense? This helps us to test the full new functionality.

**Comment by CrypticGuy** [comment]
Hi @stalgiag , 
I have modified and added a couple of unit test to check the value between the new range. 
I have added test explicitly for value of 0 and PI.

**Comment by stalgiag** [comment]
@all-contributors can you add @CrypticGuy for code and tests?

**Pull request merged**
