### PR TITLE
Update .all-contributorsrc

### PR DESCRIPTION
**Pull request by Andyloris**
Resolves #[Add issue number here]

 Changes:

 Screenshots of the change:

#### PR Checklist

- [ ] `npm run lint` passes
- [ ] [Inline documentation] is included / updated
- [ ] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Comment by montoyamoraga** [comment]
hi @Andyloris could you please mention your contribution? we don't edit these files manually, we use a bot, i can help after you tell us your contribution, best!

**Comment by gregsadetsky** [comment]
@montoyamoraga hey, sorry to hijack this, but I was just wondering: I submitted PR #4829 which was just merged. Will the bot pick up that PR, or does something else need to happen for the contributors file to be updated? Thank you!

P.S. We were on the same Zoom call today, ha. Small world :-)

**Comment by montoyamoraga** [comment]
hi @gregsadetsky i went to your PR and added you as a contributor with the all contributors bot :)

**Comment by gregsadetsky** [comment]
@montoyamoraga thank you so much!!

**Comment by montoyamoraga** [comment]
hi @Andyloris i will close this PR for now, thanks!

**Pull request closed without merging**
