### PR TITLE
Fix: Texture mode problem in manual test examples

### PR DESCRIPTION
**Pull request by shakeabi**
Fixes: #3503

### CODE REVIEW

**Comment by Spongman** [comment]
can you remove the formatting changes?

**Comment by stalgiag** [comment]
Yes as @Spongman indicated, this repo uses single quotes. The linter forces it in the source and it is good to stay consistent. Also, just as a general rule, PR's should change one thing (solve one problem, implement one feature, etc) at a time if possible. Otherwise this is good!

**Comment by Spongman** [comment]
running `npm run lint:fix` should fix it.

**Comment by stalgiag** [comment]
Also just want to link this to #105 because this would've been a good opportunity to point to a style guide.

**Comment by shakeabi** [comment]
Sorry, One of my extensions formatted 'em on save. It's fixed now :)

**Comment by stalgiag** [comment]
Thanks @shakeabi !

**Pull request merged**
