### PR TITLE
Friendly Error Messages

### PR DESCRIPTION
**Pull request by crhallberg**
Helpful error messages with friendly language and colorful theming.

Hackpad: https://p5jscon.hackpad.com/Error-Reporting-6UAUU37d6j9

errrors

These will only appear when using p5.js, not p5.min.js (although this feature isn't done yet).

Discussion:
 - [ ] Colors of messages (magenta [angry?] vs cyan [colorblind bad] vs navy [branding?]
 - [ ] Errors that would require more particular explanation

Todo:
 - [ ] Cross Domain error
 - [ ] Remove from minified (replace with noop functions)

Sorry for the early commits, my workflow was broken.

### CODE REVIEW

**Comment by crhallberg** [comment]
COLORS! The magenta is a bit angry in this context, so here is a color palette I generated based on it.

color

Colors | Hex Code | Dark Hex
---|---|---
p5.js Magenta | #ED225D | #B40033
Cyan | #1CC581 | #008851
Orange |  #FF6625 | #C83C00
Green | #79EB22 | #4DB200

Here's how it looks with the most common type of color blindness.

blind1

If someone better at color wants to refine this, do rescue us from auto-color tools.

**Comment by lmccart** [comment]
awesome. is it possible to use the p5 blue color somehow?
#2D7BB6

**Comment by kadamwhite** [comment]
Cool idea! We should just be sure to run this through the [Spectrum](https://chrome.google.com/webstore/detail/spectrum/ofclemegkcmilinpcimpjkfhjfgmhieb?hl=en) colorblindness extension or similar, so that we don't unintentionally exclude any p5 users

**Comment by workergnome** [comment]
Well, thank you. :blush:

**Comment by crhallberg** [comment]
Lauren: I added that blue to the comments where the colors are. If you'd prefer it over any of the dark colors, let me know.

**Comment by crhallberg** [comment]
@kadamwhite I checked all the colors with Spectrum ((test image)[http://crhallberg.com/p5/interactivity/testcolors.PNG]) and I switched to the following four:

#2D7BB6 // p5.js blue (replacing auto cyan)
#EE9900 // p5.js orange (replacing auto orange)
#4DB200 // auto dark green (same)
#B40033 // p5.js darkened magenta (fallback, same)

These are displayed with white text on top, very readable and high contrast.

**Comment by kadamwhite** [comment]
:100: :smiley:

**Pull request merged**
