### PR TITLE
Feature implementation: specularLight

### PR DESCRIPTION
**Pull request by sanketsingh24**
Implemented specularLight()

This function separates the diffuse and specular quantities of `pointLight()` and `directionalLight()`. Defaults to (255,255,255) so that this does not become a breaking change.

See manual tests `/webgl/lights/specularLight/` and `/webgl/material/specular_ambient/`.

Work done- 
- [x] Implemented `uDirectionalSpecularColors` and `uPointLightSpecularColors` uniform in both shaders
- [x] Implemented `specularLight()` in /src/webgl/light.js
- [x] Added a manual-test-example in `/webgl/lights/specularLight/`
- [x] Unit tests
- [x] Documentation
- [x] Example

To do-

@aferriss

### CODE REVIEW

**Comment by Spongman** [comment]
shouldn't this be called `specularMaterial()` ?

the name `specularLight()` seems to fit in the with the naming scheme for defining lights (eg, `pointLight`, `directionalLight`) whereas this is defining a matrial property.

**Comment by sanketsingh24** [comment]
This method intends to distinguish the specular and diffuse quantities from the `pointLight` and other lighting methods. It affects the lights directly so I thought it would be better to name it `specularLight`, although it is not a light, but then `ambientlight` is too. I am open to suggestions though, and If a better name comes to my mind, i will post about it.

**Comment by stalgiag** [comment]
Hi @sanketsingh24 and @aferriss just a heads up that the transition to ES6 is happening this week. See this [post for a brief overview.](https://github.com/processing/p5.js/issues/3758#issuecomment-508964727)

**Comment by sanketsingh24** [comment]
## specularLight(color)
What this method does is differentiates the specular and diffuse components from the pre-existing lighting methods, which improves the customizability of the sketch. The default value is `(255,255,255)`, which is used when this method is not called at all in the sketch, which prevents this feature to become a breaking change. It affects only the methods which are created after it in the sketch. The method is per-light, so it doesn't add up

Artists will be able to emulate something like this now-
specularLight_sketch
Code-
```js
function setup() {
  createCanvas(windowWidth, windowHeight, WEBGL);
  setAttributes('perPixelLighting', true);
  noStroke();
}

function draw() {
  background(0);

  shininess(10);
  ambientLight(50);
  specularLight(250, 0, 0);
  pointLight(255, 0, 0, 0, -100, 100);
  specularLight(0, 250, 0);
  pointLight(0, 255, 0, 0, 100, 100);
  specularMaterial(255);
  sphere(80);
}
```

Whereas, this was the previous behavior-
https://editor.p5js.org/sanketsingh24/sketches/Y7mzOuSR_

I think it is very close in behaviour to Processing's `lightSpecular`, and probably behaves in the same way.

**Comment by aferriss** [comment]
@stalgiag Thanks for the heads up re: ES6 changes! @sanketsingh24 and I spoke about this and feel comfortable making the changes needed to resolve any merge conflicts. 

I also wanted to chime in with my understanding of the `specularMaterial()` and `specularLight()` functions and how they differ. 

*Specular Materials*
A specular material is used to set the diffuse color of a geometry's material, and tells the renderer that this material should reflect specular highlights. Currently in p5, all specular highlights are 100% white, regardless of light or material color. 

The color parameters passed to `specularMaterial()` work in tandem with the colors passed to `pointLight()`. Here's a few different scenarios: 

A green point light and a red specular material, the only thing that you will see is the white specular highlight.

**Comment by aferriss** [comment]
@stalgiag @Spongman Just wanted to check in to see if you all had any feedback on this PR. It would be great to get this merged since most of the rest of our GSOC work is tied together with this function. 

@sanketsingh24 And I decided that renaming to `specularColor` made more sense than `specularLight`, but I think we're both still open to other alternatives. 

I feel good about the state of this but thought I would check in to see if anyone else had thoughts.

**Comment by aferriss** [comment]
Thanks for the vote of confidence @stalgiag ! I'm going to merge but if anyone has further suggestions re: naming or clarification of this function down the road please feel free to reach out.

**Pull request merged**
