### PR TITLE
fix p5.Color type

### PR DESCRIPTION
**Pull request by asukaminato0721**
addresses https://github.com/p5-types/p5.ts/issues/111

 Changes:

fix `p5.Color`'s type to match typescript.

 Screenshots of the change:

#### PR Checklist

- [x] `npm run lint` passes
- [x] [Inline documentation] is included / updated
- [x] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Comment by limzykenneth** [comment]
This change does not seem to render correctly in the reference and we'll need to change that before merging this:

Screenshot 2023-08-27 at 17 53 46

**Comment by limzykenneth** [comment]
@asukaminato0721 It still looks the same as the screenshot above. You can preview how it render with `npm run dev`.

**Comment by Qianqianye** [comment]
Hi @asukaminato0721 @limzykenneth , just following up on this PR. Any thoughts on why it's not rendered properly?

**Comment by asukaminato0721** [comment]
> Hi @asukaminato0721 @limzykenneth , just following up on this PR. Any thoughts on why it's not rendered properly?

I need yui-doc to generator two type signature for Color's constructor, but https://yui.github.io/yuidoc/syntax/index.html#constructor

> A [@class](https://yui.github.io/yuidoc/syntax/index.html#class) tag should be paired with either a [@constructor](https://yui.github.io/yuidoc/syntax/index.html#constructor) tag or a [@static](https://yui.github.io/yuidoc/syntax/index.html#static) tag.

**Comment by limzykenneth** [comment]
@asukaminato0721 You might be interested in having a look at #6777. We will be looking into generating typescript definition from the documentation eventually.

**Pull request closed without merging**
