### PR TITLE
[p5.js KO] Update image path in contributing_to_the_p5.js_reference.md

### PR DESCRIPTION
**Pull request by wooknick**
Changes:

Update image path in contributing_to_the_p5.js_reference.md

#### PR Checklist

- [ ] `npm run lint` passes
- [ ] [Inline documentation] is included / updated
- [ ] [Unit tests] are included / updated

### CODE REVIEW

**Comment by wooknick** [comment]
@yinhwa @designerSejinOH 

image path 수정했습니다!

**Review by designerSejinOH — APPROVED** [review]
@wooknick 넵 경로 변경 확인했습니다! 빠른 조치 감사드립니다..!

**Comment by designerSejinOH** [comment]
@Qianqianye @limzykenneth We've fixed the 'image path issue' mentioned before and request a PR merge! 
@wooknick Thanks for the quick correction 😭

**Comment by Qianqianye** [comment]
Thanks @wooknick @designerSejinOH @yinhwa!

**Pull request merged**
