### PR TITLE
Edit docs for environment

### PR DESCRIPTION
**Pull request by nickmcintyre**
Addresses #6483 

Changes:
I edited the inline docs for the rest of the functions in the "Environment" group to bring them more in line with the style guide.

@dkessner, @MsQCompSci, @davepagurek, @limzykenneth, @Qianqianye, @ChihYungChang, @teragramgius, @tuminzee, @Zarkv, @robin-haxx, @Gaurav-1306 I'd love to incorporate any feedback you may have! Here's a [staging version](https://computiful.dev/sod-environment/reference/#group-Environment) of the edits in this pull request.

#### PR Checklist

- [x] `npm run lint` passes
- [x] [Inline documentation] is included / updated

### CODE REVIEW

**Comment by MsQCompSci** [comment]
Some helpful things for newer users:
- All code examples clearly show where code should be written (within draw, or setup , etc)
- Comments in all code examples that describes what specific lines of code do
- Differentiating examples for the same function via comments (how are they different)

**Comment by nickmcintyre** [comment]
Great suggestions @MsQCompSci, I added `setup()`, `draw()`, and plenty of comments.

@Qianqianye @limzykenneth @davepagurek if these changes look good to you, please go ahead and merge them.

**Comment by nickmcintyre** [comment]
Good catches and suggestions @davepagurek – just incorporated them.

**Review by davepagurek — APPROVED** [review]
The changes look good, thanks!

**Pull request merged**
