### PR TITLE
FES: Add detection for trailing undefined arguments

### LINKED ISSUE #4571: FES: validateParameters does not detect trailing undefined arguments
#### Most appropriate sub-area of p5.js?

- [x] Other (Friendly Errors)

As mentioned in #4558

Consider the sketch
```js
let r, g, b;

r = 40;
b = 10;
function setup() {
  createCanvas(400, 400);
  color(r, g, b);
}
```
As expected we get a validation message
```
 p5.js says: color() was expecting Number for parameter #1 (zero-based index), 
received an empty variable instead. If not intentional, this is often a problem with scope: 
[https://p5js.org/examples/data-variable-scope.html] at about:srcdoc:60:3. [http://p5js.org/reference/#p5/color] 
````

But for the following, no validation message is generated
```js
let r, g, b;

r = 40;
g = 10; // now b would be undefined
function setup() {
  createCanvas(400, 400);
  color(r, g, b);
}
```

### PR DESCRIPTION
**Pull request by akshay-99**
Resolves #4571 

 Changes:

1. Make the FES detect trailing undefined arguments
Consider the following few examples
```js
let r, g, b;
function setup() {
  let r = 50;
  color(r, g, b);
}
```
Here g and b are undefined. But earlier as color with only one argument was still a valid overload, the FES did not log a message. But as it is passed 3 arguments, it is likely that them being undefined is unintentional and so a message should be displayed.

Now it shows:
`🌸 p5.js says: color() was expecting Number for parameter #1 (zero-based index), received an empty variable instead`

`🌸 p5.js says: color() was expecting Number for parameter #2 (zero-based index), received an empty variable instead
`

Similarly:
```js
function setup() {
  let a = document.getElementById('nonexistant');
  select('hgg', a);
}
```
would not have logged an error before this, as the undefined argument is trailing and select(string) is a valid overload. A message here is important to let the user know that `a` is empty ( i.e `notexistant` was not found )

Now it shows:
`🌸 p5.js says: select() was expecting String|p5.Element|HTMLElement for parameter #1 (zero-based index), received an empty variable instead.`

Also for
```js
let r;
circle(10, 10, r);
```
Earlier we used to get 
`🌸 p5.js says: circle() was expecting at least 3 arguments, but received only 2`

Now it correctly shows:
`🌸 p5.js says: circle() was expecting Number for parameter #2 (zero-based index), received an empty variable instead.`

2. Pass the error type to the ValidationError constructor so that it could be accessed in tests
3. Add tests for the edge cases in #2740 
4. Add tests for detection of trailing undefined arguments

#### PR Checklist

- [x] `npm run lint` passes
- [ ] [Inline documentation] is included / updated
- [x] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/master/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/master/contributor_docs#unit-tests

### CODE REVIEW

**Comment by stalgiag** [comment]
Hm - tests passed on this PR before but [after merge](https://github.com/processing/p5.js/runs/751034057?check_suite_focus=true) we are failing on the `selectAll()` documentation. I am looking into it.

**Comment by akshay-99** [comment]
@stalgiag It seems it's because the example was updated again in #4602 after this PR was created.  There needs to be a condition to check if `c` exists before [line 105](https://github.com/processing/p5.js/blame/master/src/dom/dom.js#L105) here and also to see if `b` exists before [line 101](https://github.com/processing/p5.js/blame/master/src/dom/dom.js#L101)

**Comment by akshay-99** [comment]
> Ah yes, now I am remembering that the examples for save, selectAll and loadModels are broken with these changes.

The ones for `save` and `loadModel` are no longer broken as there it was a validation message due to an internal call to a library function from another library function which was suppressed in #4590. The example for selectAll was also fixed in #4580  but it was overwritten in #4602. I am making a PR to fix it.

**Comment by akshay-99** [comment]
Whoops looks like @lmccart already fixed it. Thanks! :smile:

**Comment by lmccart** [comment]
oh sorry I missed this thread!

**Pull request merged**
