### PR TITLE
Add Examples for PrintWriter methods.

### PR DESCRIPTION
**Pull request by a-y-u-s-h**
Author : Ayush Sharma (a-y-u-s-h)

Hi, it's my first contribution! I added examples for PrintWriter class methods in IO module.
Formatter in my text editor automatically converts single quotes to double quotes. I'm not sure if that could somehow be a problem. Let me know if it looks alright!

### CODE REVIEW

**Comment by a-y-u-s-h** [comment]
I'm not sure what's going on. Someone help me understand this please!

**Comment by Spongman** [comment]
you should run `npm install` in your working directory to make sure the git precommit hooks are installed. then run `npm run precommit` to run those tests. `npm run lint:fix` will attempt to fix those automatically if it can.

it might be worth either rebasing your changes to remove the quotes changes, or cherry-pick/stash your final changes into a new PR.

**Comment by a-y-u-s-h** [comment]
Yeah, I realise now that I better learn cleaner git tricks first before doing anything further, like a feature-branch workflow and rebasing / stashing. I don't know these things right now.

**Comment by Spongman** [comment]
ok, it looks like it's happy about the library code itself, it's now complaining about the formatting of the examples. unfortunately we can't auto-format the example code yet. so you'll have to fix those up manually. `npm run precommit` should show you what's left to fix.

i'm still curious as to why your precommit hooks aren't running though...

**Comment by a-y-u-s-h** [comment]
Oops, I think I know now why. Two days ago when I ran `npm install` it got stuck at : 
```bash
PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /home/a-y-u-s-h/Desktop/Code/Github/web/tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...
  [=======================================-] 99%
Received 22866K total.
Extracting tar contents (via spawned process)

```

This screen remained as it as for entire night and was there when I woke up. So, I quit. After my classes, I came back and tried another pull request forgetting that I didn't do `npm install` properly. Sorry!

**Comment by a-y-u-s-h** [comment]
It still is getting stuck, is there any workaround? I'm using `Ubuntu 17.04`

**Pull request closed without merging**
