### PR TITLE
Create lichlyter_gsoc_2023.md

### PR DESCRIPTION
**Pull request by katlich112358**
Adding my GSOC wrap-up.

### CODE REVIEW

**Comment by limzykenneth** [comment]
Thanks @katlich112358, let us know if you are ready for this to be merged.

**Comment by Qianqianye** [comment]
Thanks @katlich112358 . Could you please also update the [README file](https://github.com/processing/p5.js/blob/main/contributor_docs/project_wrapups/README.md) to include a link to your report?

**Comment by katlich112358** [comment]
@limzykenneth yep, it's ready to be merged. Thanks!

**Comment by katlich112358** [comment]
Apologies for the wait, here's a separate patch that adds this .md to the README: https://github.com/processing/p5.js/pull/6458

**Comment by Qianqianye** [comment]
Thanks @katlich112358!

**Pull request merged**
