### PR TITLE
Add example for httpGet

### PR DESCRIPTION
**Pull request by rbwendt**
### Changes

* Add an example for the `httpGet` method.

### CODE REVIEW

**Comment by lmccart** [comment]
thanks!!

**Comment by limzykenneth** [comment]
@lmccart This may not work as expected. `preload` will not wait for `httpGet`, because it is based entirely on callbacks and not return anything, and thus may exit earlier than the response coming back.

**Comment by rbwendt** [comment]
@limzykenneth That's why draw waits for `earthquakes` to be present. Is that not sufficient?

**Comment by limzykenneth** [comment]
@rbwendt ah, right. I see, I missed that part. In that case it is fine. Thanks!

**Comment by lmccart** [comment]
@rbwendt I wonder if it could be confusing that this is in preload. generally we say to only place loadX() methods there, since these are the only ones that preload waits for. could we make a small edit to just rename what is currently preload to setup?

**Pull request merged**
