### PR TITLE
Continue translation into Chinese

### PR DESCRIPTION
**Pull request by SketchySketch**
Resolves #[Add issue number here]

 Changes:

 Screenshots of the change:

#### PR Checklist

- [ ] `npm run lint` passes
- [ ] [Inline documentation] is included / updated
- [ ] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/master/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/master/contributor_docs#unit-tests
--!>

### CODE REVIEW

**Comment by SketchySketch** [comment]
@all-contributors please add @SketchySketch for translating documents

**Comment by SketchySketch** [comment]
Finally! Done!

**Comment by limzykenneth** [comment]
Thanks, I'll review this in the weekend.

**Comment by limzykenneth** [comment]
@SketchySketch Would you mind if I make some changes on my side then merging this?

**Comment by SketchySketch** [comment]
Sure you can.
(Sorry my poor English...)

**Comment by limzykenneth** [comment]
All done, thanks @SketchySketch!

**Pull request merged**
