### PR TITLE
Translation of the contribution guidelines to arabic

### LINKED ISSUE #6001: Translation of contributor_docs readme into Arabic
@MostafaEwis Do ahead with the translation. Thanks!

_Originally posted by @limzykenneth in https://github.com/processing/p5.js/issues/4137#issuecomment-1410142607_

### PR DESCRIPTION
**Pull request by MostafaEwis**
Resolves #6001 

 Changes:

I created the Arabic translation of the contributer docs README.md

#### PR Checklist

- [x] `npm run lint` passes
- [ ] [Inline documentation] is included / updated
- [ ] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Comment by Qianqianye** [comment]
Thank you @MostafaEwis for working on it. I am inviting some p5.js contributors who worked p5.js Arabic translation before to review this pull request.
@sherifsallam and @nabilhassein from issue [#1199](https://github.com/processing/p5.js-website/issues/1199)
@AladdinX @Sillenaj from issue [#5831](https://github.com/processing/p5.js/issues/5831)

Please feel free to leave your comments here. Thanks!

**Comment by MostafaEwis** [comment]
Ok cool

**Comment by nabilhassein** [comment]
This looks great to me, thank you so much @MostafaEwis for your work on this! I'm sure it will help many more people to be able to participate in this community 🙂 

I do have some suggestions, which I pushed up to a new fork on my own account for ease of viewing. If you agree with them, I'd also be happy to push my commit directly to your branch if you add me as a contributor there, or follow whatever other workflow makes sense. Here's the file as it looks after my edits: https://github.com/nabilhassein/p5.js/blob/translation-of-the-contribution-guidelines-to-Arabic/contributor_docs/ar/README.md

The main idea behind my changes is to make the language more gender-neutral by avoiding addressing the reader with second-person masculine verb conjugations. As much as possible, I rephrased to use the "verbal noun" (مصدر) as consistent with the United Nations guidelines for gender-inclusive language, particularly section 3.9 "استعمال تراكيب غير مباشرة تليها مصادر عوضا عن تصريف الأفعال": https://www.un.org/ar/gender-inclusive-language/guidelines.shtml

There were some cases where it seemed too awkward to do so; there, I used the second-person plural pronoun as a compromise, although that still doesn't fully avoid gender appearing given the way Arabic grammar works. Similarly, I think there are other places where my work could be further improved on -- for example, I struggled to come up with fully gender-neutral names in accordance with section 3.1 of the same UN document above ("استخدام أسماء محايدة جنسانيا") for nouns like "contributors" (مساهمين), "stewards" (المتعهدين), and "maintainers" (المشرفين). However, I think these are relatively minor issues compared to using masculine forms of address.

Thanks again for your work, hope to see this out in the world soon!

**Comment by MostafaEwis** [comment]
@nabilhassein Hi Nabil, thanks for your review and effort on improving the translation, I will be adding you as a contributor by tomorrow and we shall further discuss how to improve this and make it more gender neutral as it's really tricky to do so in Arabic

**Comment by Qianqianye** [comment]
Thanks @MostafaEwis and @nabilhassein. Please leave a comment here when the updated translation is reviewed  and ready to be merged.

**Comment by nabilhassein** [comment]
Hi all and particularly @Qianqianye, just confirming on this thread that I reviewed this updated commit: https://github.com/MostafaEwis/p5.js/commit/0beddcfca0b7323069426f2e1e79c5f94b55ea81#commitcomment-103160578

@MostafaEwis has incorporated and/or further improved on all of my above suggestions -- I think the latest edited version looks great and is ready to be merged!

**Comment by Qianqianye** [comment]
@all-contributors please add @MostafaEwis for translation

**Comment by Qianqianye** [comment]
@all-contributors please add @nabilhassein for translation

**Comment by Qianqianye** [comment]
Thank you @MostafaEwis and @nabilhassein for working on it. The [Arabic translation](https://p5js.org/contributor-docs/#/ar/) is live on the contributor doc web page now. 🎉
If you are interested in continuing getting involved with Arabic translation for p5.js, please feel free to reply to this p5.js [Translation Steward open call](https://github.com/processing/p5.js-website/issues/1220). Thanks!

**Comment by nabilhassein** [comment]
Thank you @Qianqianye! I'm not sure if I can take on the responsibility of being a steward in the immediate future, but hopefully when my time becomes a bit more free around June, if not sooner 🙂 


One note after looking at the live page at https://p5js.org/contributor-docs/#/ar/: unlike on github which seems to automatically detect the right to left direction of Arabic and display punctuation in the correct location in the rendered markdown I reviewed, I noticed that the punctuation is not in the correct visual location at the above link. I think it should be a quick fix of adding <div dir="rtl"> to the top of the markdown file and the opposite for the code block around lines 5-7. (I think this is similar to a comment I made last year on #1199, though I didn't follow up -- reminder to myself!) Unfortunately I'm traveling without a laptop right now so I can't code up and commit the fix myself at the moment, but I can in a week's time if no one has a chance to beat me to it!

**Comment by MostafaEwis** [comment]
Hi @nabilhassein and @Qianqianye, I think that I would like to work further on the Arabic translation for the Contributor docs, and I will try to commit a fix for the text direction by the end of the day if @nabilhassein agrees. 
I want to know how the workflow should be like. Should I pull request every file I translate? Should every file be in a different branch or all in one?

**Comment by Qianqianye** [comment]
Hey @MostafaEwis, you can read more about the workflow in [contributor_guidelines](https://github.com/processing/p5.js/blob/main/contributor_docs/contributor_guidelines.md) and [i18n_contribution](https://github.com/processing/p5.js-website/blob/main/contributor_docs/i18n_contribution.md). Please feel free to tag me and @limzykenneth if you have any questions about p5.js translation.

**Comment by MostafaEwis** [comment]
Hi @Qianqianye, GSOC has opened for proposals. Can I do the Arabic translation as a GSOC contributor? I mean, is this a valid idea as I didn't see adding new translations in the p5.js project list.

**Comment by MostafaEwis** [comment]
Hi @Qianqianye again, should I focus now on the contributor docs, the FES or other parts. What has higher priority now?

**Comment by Qianqianye** [comment]
@MostafaEwis To add on what @limzykenneth said, another reason that we are not including p5.js translation project on the GSoc project list this year is that we'd like to review our translation process and potentially plan an updated workflow. If you are interested in working on p5.js projects for GSoC this year, I will highly recommend you to check out the [projects](https://github.com/processing/processing/wiki/Project-List#-p5js) labeled as 'High Priority'.

**Comment by MostafaEwis** [comment]
@Qianqianye I would like to submit a proposal for working on the image area issues
Do you have a proposal template or should I create a one with the guidelines of GSoC?

**Pull request merged**
