### PR TITLE
Translate contributer_doc/README into Chinese

### PR DESCRIPTION
**Pull request by SketchySketch**
The translation is **not yet completed! Please don’t merge!**

Resolves #[Add issue number here]

 Changes:

Add contributor_docs/zh/README.md

 Screenshots of the change:

#### PR Checklist

- [ ] `npm run lint` passes
- [ ] [Inline documentation] is included / updated
- [ ] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/master/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/master/contributor_docs#unit-tests

### CODE REVIEW

**Comment by SketchySketch** [comment]
Sorry but I may be slow to translate, so _**please don’t merge before I confirmed!**_

**Comment by limzykenneth** [comment]
No worres, I'll wait until you are ready for this PR to be reviewed. 

You can also set the PR to be a draft then a maintainer won't be able to merge it until you mark it ready for review. Don't worry if you can't figure out how to do it though. 

Thanks!

**Comment by SketchySketch** [comment]
I'm so sorry! I can't help you in translating now, Can you merge this first and I will update later?
#### SORRY!

**Comment by limzykenneth** [comment]
@SketchySketch No need to apologize. I would like to make some adjustments to the translations but if you are currently not available to make some changes here, would you mind that I make the changes directly on your PR here? Thanks for all your effort thus far!

**Comment by SketchySketch** [comment]
That is alright.

**Pull request merged**
