### PR TITLE
setAttributes example fix

### LINKED ISSUE #2250: smooth() not working in WebGL
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [x] WebGL
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: v0.5.14
- Web browser and version: Chrome 61.0.3163.100
- Operating System: Windows 10 Home 64x
- Steps to reproduce this:

With the following code:

function setup () {
    createCanvas(800, 600, WEBGL)
}

function draw () {
    smooth()
}

I get: Uncaught TypeError: this._renderer.smooth is not a function

It seems that smooth() is not implemented with WebGL. Is this deliberate or is it a bug?

### PR DESCRIPTION
**Pull request by mlarghydracept**
closes #2250 

Fixes example documentation for `setAttributes()` so that it appears in the reference. This function allows for users to change the GL renderer's attributes, including but not limited to antialiasing.

### CODE REVIEW

**Comment by Zalastax** [comment]
Can you do a rebase and force push so that we only get the interesting commit? E.g. by checkout processing/master, cherry-pick 17091b5, push --force?

**Comment by Zalastax** [comment]
Oh, now it's merged already, and reverting would just make it worse. For the future I think merging PR's with noise (excuse my terminology) should be avoided.

**Comment by mlarghydracept** [comment]
Oops yeah noted! I didn't realize all of those commits made it into this branch. I will avoid it in the future.

**Comment by lmccart** [comment]
sorry I should've been more careful in my review!

**Pull request merged**
