### PR TITLE
Update links to point to tutorial page

### PR DESCRIPTION
**Pull request by muffinista**
Addresses processing/p5.js-website#527

 Changes:

The link to the page about creating accessible labels is broken and this seems like the proper one. 

 Screenshots of the change:

#### PR Checklist

- [x] `npm run lint` passes
- [x] [Inline documentation] is included / updated
- [x] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Review by perminder-17 — COMMENTED** [review]
Thank you for taking on this task. When you run grunt yui:dev, it should start the reference website with the updated code and examples. However, I'm still encountering a broken link when I try to run it. Could you please verify the correct path?

Additionally, I'm unsure if we have the tutorial page included in the p5.js repository. If it’s missing, we might need to use absolute URLs, such as:

```
<a href="https://p5js.org/tutorials/writing-accessible-canvas-descriptions/">Writing accessible canvas descriptions</a>
```

**Comment by davepagurek** [comment]
I think the absolute path technically will work once it gets merged and then parsed in the website repo, but I think as @perminder-17 suggests, an absolute path probably is the way to go here so that it's easier to test.

**Comment by muffinista** [comment]
Thanks very much for the feedback! I've switched this to an absolute link, and I properly built/tested locally, and I believe everything is working as expected.

**Review by perminder-17 — APPROVED** [review]
I am really sorry for the delay in the review. LGTM, thanks for your work and your patience.

**Review by davepagurek — APPROVED** [review]

**Comment by ulgens** [comment]
Sorry to bump an old PR but,

> an absolute path probably is the way to go here so that it's easier to test.

Would we consider reverting this? I do understand the testing being easier, but it looks like the change is blocking the testing for local development / alternative remote deployments because they no longer point to the same domain.

**Pull request merged**
