### PR TITLE
Update random.js

### PR DESCRIPTION
**Pull request by archtaurus**
w cannot be 0

Resolves #[Add issue number here]

 Changes:

 Screenshots of the change:

#### PR Checklist

- [ ] `npm run lint` passes
- [ ] [Inline documentation] is included / updated
- [ ] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Comment by archtaurus** [comment]
@all-contributors please add @archtaurus  for Update random.js #4951

**Comment by archtaurus** [comment]
@all-contributors please add @archtaurus for Code

**Comment by archtaurus** [comment]
@all-contributors please add @archtaurus for review

**Comment by limzykenneth** [comment]
Hi @archtaurus, we usually require an issue to be opened for discussions before any PR is filed. Can you do so for this change?

Also can you explain the change a bit more? I don't get why `w` cannot be 0 given that for `w` to be zero `x1` and `x2` should both be zero, both being generated from and RNG getting a number between -1 and 1 which can be 0. The final value of `w` also should not be 0 when the `while` loop exits, as there is a divide by `w` later in the code. It is rare for `w` to actually be 0 but it's not impossible so we need to take care of that possibility.

**Comment by archtaurus** [comment]
Hi, Kenneth


Post an issue at https://github.com/processing/p5.js/issues/4954



I think there is a division by zero bug in src/math/random.js

```js random.js
&nbsp;&nbsp;&nbsp; do {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; x1 = this.random(2) - 1;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; x2 = this.random(2) - 1;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; w = x1 * x1 + x2 * x2;
&nbsp;&nbsp;&nbsp; } while (w &gt;= 1);
&nbsp;&nbsp;&nbsp; w = Math.sqrt(-2 * Math.log(w) / w);
&nbsp;&nbsp;&nbsp; y1 = x1 * w;
&nbsp;&nbsp;&nbsp; y2 = x2 * w;
```
When x1 and x2 is 0, w is zero, the `-2 * Math.log(0) / 0` is&nbsp; Infinity, then `Math.sqrt(-2 * Math.log(0) / 0)` is NaN.
then y1 and y2 is NaN...




------------------&nbsp;Original&nbsp;------------------

**Comment by limzykenneth** [comment]
Thanks @archtaurus

**Pull request merged**
