### PR TITLE
Docs: rendering.js

### PR DESCRIPTION
**Pull request by Zearin**
**Changes:**

Edited `rendering.js` for:

- markup
- linking to other parts of the documentation
- formatting
- capitalization
- punctuation
- clarity

#### PR Checklist
- [x] `npm run lint` passes
- [x] [Inline documentation] is included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Comment by limzykenneth** [comment]
Hi @Zearin, is there a relevant open issue about the changes being made here?

**Comment by Zearin** [comment]
> Hi @Zearin, is there a relevant open issue about the changes being made here?

It’s a mix.  

Much of it includes adding links to other parts of the documentation whenever another class or method is mentioned.  This is pretty universally considered a helpful thing.  Specifically, however, the [inline documentation](https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md#specify-element-type-and-description) guidance says:

> When possible, link to other files when mentioning other function or variable names.

Much of it is small-time grammar and phrasing stuff. Most people tend to brush this off as insignificant, but I personally believe it has an under-recognized impact on the perception of any reference document.

The biggest modification is probably the way I marked up the blend modes.  I made several changes here (apart from linkifying each blend mode constant).  

The biggest such change is marking up the blend modes as a description list.  This markup structure is ideal for cases like this, because there’s a bunch of items with 1:1 ratio of _«term»_:_«description»_.  Let me know if there’s an issue with the way it looks.  (It would be a trivial effort to sprinkle a little CSS in and get it to look however you wish!)

I moved the “(2D)” and “(3D)” items from the end of the description to the end of the blend mode.  When someone is working on a sketch, they should be able to know whether a blend mode applies to their project before reading to the end of the description.  Putting these labels by the terms makes it easy for someone to identify whether it will be of any use to them.

In general, I love how p5js makes a real effort to be friendly to beginners and artistic-minded people.  If you build the docs from the changes in this Pull Request, it’s my hope that you’ll find the end result a little bit friendlier and easier to grok than before.  

If this works for you, I’m happy to replicate the work on other parts of the reference docs.

If not, please let me know what I can do to make it acceptable.  I’ll gladly accomodate!

Thank you. 🙏🏽

**Comment by limzykenneth** [comment]
We usually require a Github issue to be open and discussed before a PR can be filed (except for very small change like typos). That's what I mean by relevant open issue.

As this PR has a mix of both corrections and more editorial changes, I'd prefer they be separated out and the editorial ones be discussed in an issue beforehand.

**Comment by Zearin** [comment]
Okay, I’ll try to rework this.

**Pull request closed without merging**
