### PR TITLE
Add p5.Camera docs

### LINKED ISSUE #5056: Add documentation for p5.Camera properties
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Feature enhancement details:
Want the code to give info about the camera position. Like `camera.x`, `camera.y` and `camera.z` which will really make camera object useful.

### PR DESCRIPTION
**Pull request by Aloneduckling**
Resolves #5056

 Changes:

Added info about p5.Camera object properties(`eyeX,Y,Z  centerX,Y,Z  upX,Y,Z`)

 Screenshots of the change:

image

image

#### PR Checklist

- [x] `npm run lint` passes
- [x] [Inline documentation] is included / updated
- [ ] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Comment by Aloneduckling** [comment]
This PR resolves the issue #5056

**Comment by Aloneduckling** [comment]
@stalgiag, I have made the changes. 
I want to mention that I used orbitControl in eyeX, Y, Z examples because I found that orbitControl changes eyeX, Y, Z and would be fit for use here. I used lookAt() in centerX, Y, Z examples reason being the same as above and I have not changed anything in upX, Y, Z because I was not able to find a method that manipulates these properties directly. 

image


image

**Comment by stalgiag** [comment]
Great! Thank you.

@all-contributors please add @Aloneduckling for documentation

**Comment by Aloneduckling** [comment]
@stalgiag, Sorry to disturb you again, I just wanted to know that how much time does it take for the online reference manual to get updated. I was asking because I have created this [PR](https://github.com/processing/p5.js/pull/4979) and the website doesn't seem to be updated. [This]( https://p5js.org/reference/#/p5/createButton) is the page for reference.

**Comment by ffd8** [comment]
@Aloneduckling @stalgiag – just hit a hiccup while loading the latest `data.json` refs into P5LIVE.. went searching and found out – the documentation examples for both `centerY` and `centerZ` are missing their `</code></div>` tag at the end... 

The effects can be see on website refs: [centerY](https://p5js.org/reference/#/p5.Camera/centerY) + [centerZ](https://p5js.org/reference/#/p5.Camera/centerZ)

**Comment by Aloneduckling** [comment]
@ffd8, my bad, thank you for pointing this mistake. Reverting this PR might create problems for other people contributing to this repo so I will open a new issue and fix this. Again thank you @ffd8 for pointing this out.

**Pull request merged**
