### PR TITLE
Overlap of code and canvas in the p5 website.

### PR DESCRIPTION
**Pull request by nakul-shahdadpuri**
Resolves [#815](https://github.com/processing/p5.js-website/issues/815)

 Changes:
Edited httppost() section in 
**src/io/files.js**
1. Changed canvas size to 100x100
2. Simplified the example by removing colouring and circle drawing sections. 

 Screenshots of the change:

Screenshot from 2020-08-22 15-11-44

#### PR Checklist

- [x] `npm run lint` passes
- [x] [Inline documentation] is included / updated
- [x] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Comment by nakul-shahdadpuri** [comment]
My pleasure.
@all-contributors please add @nakul-shahdadpuri  for code

**Comment by montoyamoraga** [comment]
@all-contributors please add @nakul-shahdadpuri for code

**Comment by montoyamoraga** [comment]
there was a conflict on the PR, i opened a new one and now everything's good :)

**Comment by nakul-shahdadpuri** [comment]
Thanks a lot :).

**Pull request merged**
