### PR TITLE
Adding a bunch of funtions in push() reference documentation

### PR DESCRIPTION
**Pull request by imrishabh18**
@limzykenneth I hope it is correct now.

### CODE REVIEW

**Comment by limzykenneth** [comment]
Yes, seems to be ok now. Are you still having problem with previewing the docs from the local repo?

**Comment by imrishabh18** [comment]
No, i figured it out now.

**Comment by imrishabh18** [comment]
Should i add the other functions now ?

**Comment by limzykenneth** [comment]
Let's hold off on that and let others review this first

**Comment by lmccart** [comment]
looks great thanks @imrishabh18. are there more to add to this list still?

**Comment by imrishabh18** [comment]
@lmccart Yes there are few more.

**Comment by lmccart** [comment]
@imrishabh18 ok I'll merge this and you can feel free to open another PR with the additional functions if you'd like. thanks!

**Pull request merged**
