### PR TITLE
Updated documentation, and display error message when json is invalid

### PR DESCRIPTION
**Pull request by Jared-Sprague**
Issue: https://github.com/processing/p5.js/issues/966
Issue: https://github.com/processing/p5.js/issues/870

### CODE REVIEW

**Comment by lmccart** [comment]
Thanks @Jared-Sprague. However, I don't know if we should publicize the case of using both preload and a callback together as I think it adds confusion for beginners. I think we could keep the examples as is, just remove the line that says that it won't work with callbacks in preload.

**Comment by Jared-Sprague** [comment]
@lmccart ok no problem! I'll change the examples back

**Comment by Jared-Sprague** [comment]
@lmccart ok done.

**Comment by Jared-Sprague** [comment]
@lmccart also added fix for https://github.com/processing/p5.js/issues/870

**Comment by lmccart** [comment]
thanks!!

**Pull request merged**
