### PR TITLE
Fix for touchStarted triggers twice among other issues with touchStarted/mousePressed on mobile

### LINKED ISSUE #6739: touchStarted triggers twice among other issues with touchStarted/mousePressed on mobile
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [X] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.9.0

### Web browser and version

120.0.6099.210

### Operating System

Android

### Steps:
1. Have touchStarted() or mousePressed() on mobile

### Snippet:
Here's a sketch demonstrating it:
https://editor.p5js.org/PotatoBoy/sketches/1F9s-k_5D

On touchscreen:
- mousePressed and touchStarted both trigger if they're both present (same for mousePressed)
- If either is without the other it triggers twice
- touchStarted doesn'tt get called when the mouse is pressed like described in the documentation

Note: This looks like nearly the same issue with #6737. We might have to check if this sort of issue applies to any other event listeners. For now, I'll list these 2 as separate issues and pull requests since I already created the first pair.

### PR DESCRIPTION
**Pull request by RandomGamingDev**
Resolves #6739
Note: This looks like nearly the same issue with https://github.com/processing/p5.js/issues/6737. We might have to check if this sort of issue applies to any other event listeners. For now, I'll list these 2 as separate issues and pull requests since I already created the first pair.

 Changes:

Adds an instance variable called touchstart to p5 and changed p5.prototype._ontouchstart & p5.prototype._onmousedown to function as documented.

 Screenshots of the change:

On touchscreen
- mousePressed and touchStarted no longer both trigger if they're both present (same for mousePressed)
- If either is without the other it doesn't triggers twice anymore
- touchStarted now gets called when the mouse is pressed like described in the documentation

#### PR Checklist

- [x] `npm run lint` passes
- [x] [Inline documentation] is included / updated
- [x] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Comment by davepagurek** [comment]
I also mentioned in #6738, but a comment explaining the flag would help. Other than that I think this approach makes sense.

I notice there was a branch for Safari that is now removed. I assume modern Safari doesn't need it any more, but do you know what version that started in?

Also tagging events stewards, who are probably more familiar than I am with the control flow of these events: @limzykenneth, @richardegil, @angelabelle, @littlejacinthe, @TanviKumar, @tuminzee

**Comment by RandomGamingDev** [comment]
> I notice there was a branch for Safari that is now removed. I assume modern Safari doesn't need it any more, but do you know what version that started in?

The Safari branch wasn't functioning properly in the first place, since it breaks the the behavior described before where it's supposed to call `touchStarted()` if there isn't a `mousePressed()` on not just Safari. Also, since Safari fails to call the touch events, it'll just do what the original code looked like it was supposed to do, which was use the `mousedown` event which prioritizes `mousePressed()` and then calls `touchStarted()` if it can't find the prior. <br/>
If we want to introduce something that fixes Safari only calling the mouse event handlers and not the touch screen ones on certain versions, we'll have to introduce something else to try and detect whether or not it's touchscreen. <br/>
For now, I think we should just merge the pull request and check whether or not we should try doing that in another issue and/or PR.

Safari Issue: https://bugs.webkit.org/show_bug.cgi?id=105406

**Comment by RandomGamingDev** [comment]
> I also mentioned in https://github.com/processing/p5.js/pull/6738, but a comment explaining the flag would help. Other than that I think this approach makes sense.

I've added the comment

**Comment by Garima3110** [comment]
Hello everyone, I just want to add that I did the tests for this on Safari, and it all looks good. I also tried it out on Chrome on my Android phone, and Safari on my iPhone behaved the same way. So, it seems like things are working fine on both browsers.

**Review by davepagurek — APPROVED** [review]
Thanks everyone for helping check that this works as expected!

**Pull request merged**
