### PR TITLE
Add fes message

### LINKED ISSUE #5152: Friendly error message not displayed
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:
When a user overwrites p5.js's inbuilt function displays a non-friendly error message. 
img

This can be easily converted to a friendly error message by passing message to `p5._friendlyError()` method.
- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

```
function createCanvas(){
    console.log(`hello`);
}
function setup() {
  createCanvas(400, 400);
}

function draw() {
  background(220);
}
```
We can replace createCanvas with any of the inbuilt p5.js function.
PS: I would like to wok on this

### PR DESCRIPTION
**Pull request by Aloneduckling**
Resolves #5152

 Changes:

 Screenshots of the change:

image
Here the 1st message is the new friendly error message, the second was the original message.
#### PR Checklist

- [x] `npm run lint` passes
- [ ] [Inline documentation] is included / updated
- [x] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Comment by Aloneduckling** [comment]
I wanted to confirm something before merging ,

**Comment by Aloneduckling** [comment]
Reason for closing this: https://github.com/processing/p5.js/issues/5152#issuecomment-817300090

**Comment by outofambit** [comment]
hey @Aloneduckling, this is looking good! i think the only thing left to do is update the unit tests (that's why the checks failed). Would you like to re-open this PR and fix those? The tests that need to be updated are these:

1. https://github.com/processing/p5.js/blob/374acfb44588bfd565c54d61264df197d798d121/test/unit/core/main.js#L131-L136
2. https://github.com/processing/p5.js/blob/374acfb44588bfd565c54d61264df197d798d121/test/unit/core/main.js#L147-L152

i think an approach that uses `sinon` would work. you can refer to this example for what that looks like:

https://github.com/processing/p5.js/blob/374acfb44588bfd565c54d61264df197d798d121/test/unit/io/loadImage.js#L5-L20

**Comment by Aloneduckling** [comment]
@outofambit, Yeah I will update the unit tests.

**Comment by outofambit** [comment]
> @outofambit, Yeah I will update the unit tests.

Awesome, thank you!

> I had a question, FES's `validateParameters()` function requires parameterData.json([here](https://github.com/processing/p5.js/blob/043c0a7bba71295feda73397af13e23a3f914abe/src/core/friendly_errors/validate_params.js#L16)) how does it work if the file is not present in the repository.

@Aloneduckling I'm pretty sure its because this file is generated during the build process (which runs before tests are run). We don't commit it to the repo because its generated from the inline docs in our code, it's not something we edit directly.

**Comment by Aloneduckling** [comment]
@outofambit, I have done the changes please have a look.

**Review by outofambit — APPROVED** [review]
this looks awesome, thank you @Aloneduckling!

**Pull request merged**
