### PR TITLE
FES: Split error_helpers.js 

### PR DESCRIPTION
**Pull request by akshay-99**
Addresses #4583

 Changes:

The file `error_helpers.js` was growing too large, so as discussed in #4583, I have split it into 3 files inside a new folder `core/friendly_errors`

- validate_params.js
- file_errors.js
- fes_core.js

I also had to change the imports in other files to reflect this.

The blame history for the files is still retained as seen here:
- [validate_params.js](https://github.com/akshay-99/p5.js/blame/master/src/core/friendly_errors/validate_params.js)
- [file_errors.js](https://github.com/akshay-99/p5.js/blame/master/src/core/friendly_errors/file_errors.js)
- [fes_core.js](https://github.com/akshay-99/p5.js/blame/master/src/core/friendly_errors/fes_core.js)

I am not sure if this could be bundled alongside the fix for #4583 or whether this fits better as an independent PR. Until that is decided, I am marking this as draft.

#### PR Checklist

- [x] `npm run lint` passes
- [ ] [Inline documentation] is included / updated
- [ ] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/master/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/master/contributor_docs#unit-tests

### CODE REVIEW

**Comment by akshay-99** [comment]
I have pushed the check to prevent validation for internal calls in the latest commit. So for the sketch mentioned in #4583, earlier we would get validation messages for both `saveJSON` and `saveStrings`. Now the one for `saveStrings` will not be displayed.

I decided to use [stacktrace.js](https://www.npmjs.com/package/stacktrace-js) as the regex [here](https://github.com/processing/p5.js/blob/7449231c082681ae69e794e93a63e1615239a991/src/core/error_helpers.js#L767) is very chrome-specific. The regex aims to extract the location in the sketch where the error occurred but it doesn't work on other browsers.
So on chrome, it gives:
`🌸 p5.js says: random() was expecting Number for parameter #0 (zero-based index), received string instead at http://localhost:8100/sketch.js:4:5. (http://p5js.org/reference/#p5/random)`
But on Firefox, I see:
`🌸 p5.js says: random() was expecting Number for parameter #0 (zero-based index), received string instead. (http://p5js.org/reference/#p5/random)`

But importing stacktrace.js directly increased the size of the final p5 library by 200 KB so I instead opted to just borrow the part that we need and put that in with its license and copyright. This increases the size of the final library by around 20 KB.

The test for `p5.Image.blend` initially failed because from [here](https://github.com/processing/p5.js/blob/7449231c082681ae69e794e93a63e1615239a991/test/unit/image/pixels.js#L158)  the call actually goes to `p5.Image.prototype.blend` [here](https://github.com/processing/p5.js/blob/7449231c082681ae69e794e93a63e1615239a991/src/image/p5.Image.js#L783) which then calls `p5.prototype.blend`. The former does not have parameter validation but the latter does. The validation message due to the internal call from `p5.Image.prototype.blend` to `p5.prototype.blend` would be suppressed by this PR and so I had to add validation for `p5.Image.prototype.blend` as well.

**Comment by akshay-99** [comment]
Also, I don't really understand the need for importing `error_helpers.js` in files such as `src/color/creating_reading.js`, `src/core/shape/2d_primitives.js`, `src/core/shape/curves.js`, etc. I thought that it would be required in files which use FES functionality. But some files which also use the FES, notably `src/math/random.js` , `src/dom/dom.js`, `src/image/image.js` don't import it.

I tried commenting out these imports and all the tests still pass and the FES still seems to be working correctly. The functions such as `_validateParameters` get assigned to the p5 object, so shouldn't it be available regardless of the import ( as long as the FES files are imported in `app.js`) ?

**Comment by akshay-99** [comment]
Hi @stalgiag I think I have almost solved #4571 as well. But I have to wait for this to be merged before creating the PR for that otherwise it's tests would fail

**Comment by stalgiag** [comment]
Looking good! Will review today @akshay-99.

**Comment by akshay-99** [comment]
Thanks @stalgiag. I will proceed with #4571 now

**Pull request merged**
