### PR TITLE
Adding ellipsoid

### PR DESCRIPTION
**Pull request by hkirat**
Adding a new ellipsoid geometry.
https://en.wikipedia.org/wiki/Ellipsoid

### CODE REVIEW

**Comment by indefinit** [comment]
This is a nice addition to primitives.  Do you mind adding to the inline doc a note about detail number. Numbers above 150 can potentially crash your browser.  This is related to a recent discussion on detail re: sphere primitive.

**Comment by hkirat** [comment]
By inline doc do you mean the description above the code?

**Comment by indefinit** [comment]
Yes.

**Comment by hkirat** [comment]
done.

**Comment by lmccart** [comment]
thanks @hkirat. @indefinit if it all looks good to you go ahead and merge!

**Pull request merged**
