### PR TITLE
Improved_friendlyError to handle namespaced error method names

### LINKED ISSUE #4398: p5._friendlyError() can't provide reference link for methods like p5.Vector.add
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (Friendly Error System)

#### Feature enhancement details:
The current `p5._friendlyError(message, method)` call appends `method` string in front of https://p5js.org/reference/#p5/ URL to link to reference site for that method, but this way it can't link to URLs like https://p5js.org/reference/#/p5.Vector/add . So I suggest checking before appending if it has `'p5.'` string in start or not and append it accordingly.

Screenshot from 2020-03-21 01-04-43

### PR DESCRIPTION
**Pull request by ykabusalah**
Resolves #4398

### CODE REVIEW

**Comment by lmccart** [comment]
@akshay-99 I know you've been working on FES stuff. I went to merge this one but realized the contents of this file had changed significantly and didn't want to mess anything up. this code patch looks good though. would you be up for taking a look and seeing if there's a way to integrate this into your work?

**Comment by akshay-99** [comment]
Hi @lmccart . The contents of `error_helpers.js` were broken up into `validate_params.js`, `file_errors.js` and `fes_core.js`. This particular change would fit in `fes_core.js` after [line 128](https://github.com/processing/p5.js/blob/b3a905936d95e52157dbb80ef053b31ad8eae5b5/src/core/friendly_errors/fes_core.js#L128). 

I can't think of any easier way to merge this right now other than simply moving the code to its new place in the merge commit, but I am not sure if that will still retain the line credits for @ykabusalah if someone else is the one merging in this case. But I think they can be added as a [co-author](https://help.github.com/en/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors#creating-co-authored-commits-on-the-command-line) for the merge to retain the line credits.

Github won't show me what lines are conflicting but after pulling the changes and trying to merge this, it seems git thinks that the conflict is in `validate_params.js`. This is because of the fact that `validate_params.js` retains more lines from `error_helpers.js` than the other two files.

**Comment by lmccart** [comment]
Ah yes, I meant rather than trying to merge directly, is it possible to incorporate the logic here to make the fix in what you have written already? @ykabusalah won't have line credit directly, but hopefully will feel ok that the contribution is merged and helping resolve the issue.
alternatively, @ykabusalah if you'd like to open a new PR working off of what's in the repo now, please let us know. I apologize for not getting to merge this earlier!

**Comment by limzykenneth** [comment]
We could resolve the merge conflict manually offline and push the merged branch back to master and it should retain the existing commit history here.

**Comment by akshay-99** [comment]
@limzykenneth  Yes that's what I was saying but the merge commit would involve moving a significant portion of the PR's code to the new place. And that would mean those lines which were moved would be attributed to whoever authored the merge commit. I was wrong about the co-author part, there's no need for that. We could just use `git commit --author="name <email>"` when committing the merge, to make sure those lines which are moved still get attributed to @ykabusalah

**Comment by lmccart** [comment]
I think that sounds fine. it's not such a large change. I would prioritize getting it cleanly merged in over worrying too much about line attribution

**Comment by akshay-99** [comment]
So should I go ahead with merging this offline? I won't be able to push to the master here directly so I would have to make another PR containing the merge commit

**Comment by lmccart** [comment]
yes please :) thank you!

**Pull request closed without merging**
