### PR TITLE
[FES] Replace throw error with FES

### PR DESCRIPTION
**Pull request by chechenxu**
Resolves part of #5649 

 Changes:

Replace some throw error with friendly error system message.

#### PR Checklist

- [x] `npm run lint` passes
- [ ] [Inline documentation] is included / updated (Not Applicable)
- [ ] [Unit tests] are included / updated (Not Applicable)

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Comment by limzykenneth** [comment]
The original issue only recommended replacing `console.warn` and `console.error` with FES, functions throwing errors should not usually have the throwing behaviour entirely replaced with FES messages because it will change the overall behaviour of the code. When throwing an error in JS it will halt current execution where as simply logging a message (including with the FES), code execution can continue which in the case where it should have halted may cause undefined behaviour.

**Comment by chechenxu** [comment]
@limzykenneth Thanks for your feedback. Will update this PR!

**Comment by limzykenneth** [comment]
I'm ok with this but @davepagurek you may want to have a look just in case since it only changes messages in WebGL side of things. Maybe the messages can be rephrased in some cases as well but we can possibly do this in another PR. Do merge if it looks good to you @davepagurek.

**Review by davepagurek — APPROVED** [review]
This looks good to me!

**Comment by davepagurek** [comment]
@all-contributors please all @chechenxu for code

**Comment by davepagurek** [comment]
https://github.com/all-contributors please add @chechenxu for code

**Comment by davepagurek** [comment]
@all-contributors please add @chechenxu for code

**Comment by chechenxu** [comment]
@davepagurek @limzykenneth Thank you!

**Pull request merged**
