### PR TITLE
Added round corner property for rect() in WebGL mode

### LINKED ISSUE #5001: Rectangle does not show corner radius in WEBGL mode
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: latest at editor.p5js.org website
- Web browser and version: Chrome 87.0.4280.141 (Official Build) (64-bit) (cohort: Stable)
- Operating System: Windows
- Steps to reproduce this:

Paste this code into the editor at https://editor.p5js.org/ and remove the WEBGL parameter and see the difference. The rectangle should have curved corners. The rectangles position is not relevant to this bug.

```
function setup() {
  // Create the canvas
  createCanvas(720, 400, WEBGL);
  background(200);

  // Set colors
  fill(204, 101, 192, 127);
  stroke(127, 63, 120);

  // A rectangle
  rect(0, 120, 120, 40, 40, 1, 5, 1);
  
}

```

### PR DESCRIPTION
**Pull request by ShenpaiSharma**
Addresses #5001

 Changes:

Finally decided to follow what processing does to round the corner of rect(). Still, here we use the retained-mode for drawing a rectangle if the user does not provide args for rounding the rectangle and use Immediate mode to round the rectangle corner if the user provides args for rounding corners.
As mentioned by @aferriss [comment](https://github.com/processing/p5.js/issues/5001#issuecomment-1019020743) also, using vertex and quadraticVertex() to draw rounded corners has a few issues like:
- Larger strokeWeight shows some artifacts.
image

-  texturing doesn't work while using vertex and quadraticVertex().

That's why followed retained-mode until any user deliberately wanted to use the rounded rectangle behavior.

Screenshots of the change:

Code:
```
function setup() {
 // Create the canvas
 createCanvas(720, 400, WEBGL);
 background(200);
 
 // Set colors
 fill(204, 101, 192, 127);
 stroke(127, 63, 120);
 
 // A rectangle
 rect(-100, -100, 200, 80, 40, 1, 5, 1);
}

```

Before:
image

After:
image

#### PR Checklist

- [x] `npm run lint` passes
- [x] [Inline documentation] is included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Comment by davepagurek** [comment]
Hi, thanks for taking this on! How do you feel about manually creating more vertices with `sin` and `cos` to do the corner arcs rather than using `quadraticVertex`? Some benefits of this would be:
- We can support adding texture coordinates (they don't currently work with curves, see https://github.com/processing/p5.js/issues/5722) so that we don't break the use of `texture()` with this shape
- We can get better approximations of a circular arc for larger curves

Downsides/complications that I can see:
- It's more work
- We'd have to decide how many vertices to break the corners down into

**Comment by davepagurek** [comment]
I created an issue to discuss the stroke issues you mentioned: https://github.com/processing/p5.js/issues/5790

**Comment by ShenpaiSharma** [comment]
Thanks, @davepagurek, for your insights, obviously that's a much better idea to implement the round edges using `sin` and `cos`, but looking at the complications, we actually thought of following this mid path and also processing follows the same implementation i.e., using vertex and quadraticVertex().
Also, it may reduce enough confusion for users trying to work with rect().

**Comment by davepagurek** [comment]
That makes sense. Just for clarification, do you think there's a benefit of sticking with `quadraticVertex` vs using `sin`/`cos`? Thinking ahead, I can write a follow-up PR to add support for texture coordinates in rounded `rect` calls, but I'd probably do that by more easily by switching to `sin`/`cos` -- fixing #5722 in general is a bigger project, so I'd have to do the bezier math manually in the mean time, which is doable but I'm much less confident in my abilities to do that than to do some trigonometry 🙂 The structure you set up will be useful regardless (thanks!) but I want to make sure I wouldn't be missing something when doing so.

Also, if we're leaving texture coordinate support to another PR, do you mind changing your PR description to `Addresses #5001` instread of `Resolves` so it keeps the issue open until then?

**Comment by ShenpaiSharma** [comment]
Yes, I think using `sin` and `cos` will be much more preferable here, but once #5772 will be fixed, this solution will work fine too. Also, this will solve the problem faced by users working with rounded `rect()`. As users working with rounded `rect` now have to draw that with `bezierVertex` or `quadraticVertex`, and thus facing the same problem in passing the texture coordinates.

**Comment by ShenpaiSharma** [comment]
> Also, if we're leaving texture coordinate support to another PR, do you mind changing your PR description to `Addresses #5001` instread of `Resolves` so it keeps the issue open until then?

Thanks @davepagurek , Yeah, that makes more sense, will do that for ASAP

**Comment by davepagurek** [comment]
Great, thanks! After I finish work for the day I'll run the code just to double check everything and then merge this in.

**Review by davepagurek — APPROVED** [review]

**Comment by Qianqianye** [comment]
Thanks @ShenpaiSharma and @davepagurek!

**Pull request merged**
