### PR TITLE
fixes examples

### PR DESCRIPTION
**Pull request by futuremarc**
Canvas isn't wrapped in a p5.element so examples broke.

### CODE REVIEW

**Comment by lmccart** [comment]
I think canvas should be a p5.element. If this is not the case I believe that's a bug. I can take a look later this week.

**Comment by lmccart** [comment]
It'd be great to add these examples, but would you mind changing this PR around so it includes the other ones that were removed in this patch as well?

**Comment by lmccart** [comment]
hmm looks like it is indeed working as a p5.Element:

```
function setup() {
  var c = createCanvas(windowWidth, windowHeight);
  console.log(c instanceof p5.Element); // prints true
}
```

this also seems to work fine:
```
function setup() {
  var c = createCanvas(windowWidth, windowHeight);
  c.position(100, 100);
}
```

however, this one doesn't:
```
function setup() {
  var c = createCanvas(windowWidth, windowHeight);
  c.translate(100, 100);
}
```

maybe I'm misunderstanding what the problem is here, or what's supposed to be happening?

**Comment by futuremarc** [comment]
Let me look into this

**Comment by futuremarc** [comment]
It seems the p5.Renderer2D has its own versions of `rotate()` and `translate()` which don't inherit from p5.Element. These methods apply themselves something like `this.drawingContext.translate(x, y);` and they don't seem to be making any effect, at least in the way you'd expect them to.

**Comment by lmccart** [comment]
aha I see. hmm I wonder what to do then. do we need different naming? or just these revised examples as you have them? or maybe examples using elements that aren't the canvas? pinging @shiffman as well..

**Comment by shiffman** [comment]
Oh, strange.  This is what I'm seeing:

1: works fine!
```javascript
function setup() {
  var canvas = createCanvas(100, 100);
  canvas.id('test');
}
```

2: works, but needs `p5.dom.js`

```javascript
function setup() {
  var canvas = createCanvas(100, 100);
  canvas.position(200, 200);
}
```

3: Throws no error with or without p5.dom.js but doesn't function properly

```javascript
function setup() {
  var canvas = createCanvas(100, 100);
  canvas.translate(200, 200);
}
```

Sorry to be behind, but based on the above are you saying that a p5 canvas is not a `p5.element` but has  many of the methods like `position()`, `style()`, etc.  so it behaves like one?  And `translate()` doesn't throw an error b/c it's somehow executing a transformation **inside** the canvas?

Oh, look at this, it is!

```javascript
var canvas;

function setup() {
  canvas = createCanvas(600, 400);
}

function draw() {
  background(0);
  canvas.translate(50,50);
  fill(255);
  ellipse(0,0,20,20);  // ellipse appears at 50,50!
} 
```

The behavior that I would expect is that the canvas object itself is a `p5.element` and that `canvas.translate()` would apply a DOM transformation rather than an internal transformation on the canvas itself.

What do you think?

**Comment by lmccart** [comment]
sorry to snooze on this for a while. I'm still a little concerned about this sort of unintuitive syntax here. 

I wonder if we should consider changing the names `.rotate()` and `.translate()` so they don't clash with canvas drawing functions. especially once p5.dom is merged into core, it seems it could be hard to communicate the distinction in the reference.

would it make more sense to make a method like `transform()` and and pass in `ROTATE` or `TRANSLATE` and the args? I know this syntax is less straightforward but could it resolve the confusion?

or more generally, do we need some way to distinguish dom level methods from canvas level ones, in syntax or reference or otherwise?

cc @shiffman

**Comment by shiffman** [comment]
I think in an ideal world the name would be the same i.e. `translate()` or `rotate()` called on their own would apply to the canvas itself, but `element.translate()` or `element.rotate()` would apply to the DOM element.  I guess the issue here is that while the concepts are similar they behave differently . . and thus the confusion?    Or is it really just that we don't know what to do with `canvas.translate()` -- is it translating the canvas DOM element or applying a drawing translation?
 
I think the `transform()` idea is a good one, although the addition of `ROTATE` or `TRANSLATE` is a little awkward.  This is probably more confusing, but I'm trying to think if we can use arguments to our advantage, i.e.

```javascript
element.transform(x, y);  // translates only
element.transform(x, y, angle);  // translates and rotates
element.transform(angle);  // rotates only
```

better or worse?

**Comment by lmccart** [comment]
The difficulty is that this isn't techhnically possible without significant restructuring. Right now createGraphics returns a new canvas object and you can make calls like this:

```
var g = createGraphics(100,100);
g.line(0,0,100,100);
g.rotate(PI);
```

Essentially createCanvas and createGraphics return the same type of object under the hood. So when .rotate() or .translate() is called on an object returned from one of these methods, it is bound to the existing canvas method in the API, thus obscuring new DOM methods.

**Comment by lmccart** [comment]
So it is both a technical issue and a sort of confusing syntax / conceptual issue. I think the argument checking idea for transform is interesting, would love to hear how others feel about that.

Alternatively, should the names be more explicit? translateElement, rotateElement? Doesn't feel quite right...

**Comment by futuremarc** [comment]
This is a tough issue. Unfortunately I like @lmccart 's solution of just changing the name because adding a third arg to specify translate and rotate feels a bit weird in practice.

@shiffman the problem is that rotate can either take 1,2 or 3 args and translate takes 2 or 3 args since they can apply 3d transforms.

**Comment by lmccart** [comment]
if we do go with the other name option. maybe a better naming is `styleTransform()` and `styleRotate()` since transform and rotate are properties of the style property on the element? That is, rotating a div with pure JS would look like `document.getElementById("myDIV").style.transform = "rotate(7deg)";`

**Comment by futuremarc** [comment]
I like `styleTranslate()` and `styleRotate()`! I feel like it might also help for learning purposes of what is actually happening.

**Comment by brysonian** [comment]
would it make sense to toss it totally in a namespace like the native api? e.g. `element.style.translate()` Though that starts to get confusing with things like position i guess. Even so, is it confusing that `styleRotate` affects the CSS and so does `position` even though `position` isn't prefixed with style?

**Pull request merged**
