### PR TITLE
refined the number of samples used in diffused and specular textures

### LINKED ISSUE #6586: Refining the number of samples used when creating diffuse and specular textures.
### Increasing Access

The goal is to find an optimal configuration that ensures smooth execution on various devices while maintaining an acceptable level of visual fidelity. This optimization process is essential for enhancing the overall performance of the feature as ideated by @davepagurek in issue #6531

### Most appropriate sub-area of p5.js?

- [X] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### Feature enhancement details

Refine into the number of samples used when creating diffuse/specular textures. It may still look OK if we use fewer samples but apply dithering to the sample locations, which is [a strategy we use in our blur shader.](https://github.com/processing/p5.js/issues/6397)

### PR DESCRIPTION
**Pull request by sudhanshuv1**
Resolves #6586

 Changes:

1. Changed the value of `sampleDelta` from 0.025 to 0.100 in [src/webgl/shaders/imageLightDiffused.frag](https://github.com/processing/p5.js/blob/main/src/webgl/shaders/imageLightDiffused.frag).
2. Added dithering to the sample vector `sampleVec` in [src/webgl/shaders/imageLightSpecular.frag](https://github.com/processing/p5.js/blob/main/src/webgl/shaders/imageLightSpecular.frag).
3. Changed the value of `SAMPLE_COUNT` from 1024 to 16, and the definition of `vanDerCorput` in [src/webgl/shaders/imageLightSpecular.frag](https://github.com/processing/p5.js/blob/main/src/webgl/shaders/imageLightSpecular.frag).

#### PR Checklist

- [x] `npm run lint` passes
- [ ] [Inline documentation] is included / updated
- [ ] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Comment by davepagurek** [comment]
Sorry for the delay, and thanks for taking this task on! This is a great start.

I'm just playing around with it now, and it looks there are some speckles appearing in the diffused light:


<table>
<tr>
<td>

image

</td>
<td>

image

</td>
</tr>

<tr>
<th>This PR</th><th>1.9.0</th>
</tr>
</table>

Live: https://editor.p5js.org/davepagurek/sketches/YHiYxeM7B


I played around a bit and I think this is happening because of the addition of the random offset here:
```glsl
vec3 sampleVec = tangentSample.x * right + tangentSample.y * up + tangentSample.z * normal + randomOffset;
```

The problem is that when we add a random offset to just the normal direction here, we end up with a vector that does not have length of 1, which breaks some later calculations. I tried out this change, which instead adds the random offset to `theta` and `phi`:

```diff
        const float sampleDelta = 0.100;
        float nrSamples = 0.0;

-  for(float phi = 0.0; phi < 2.0 * PI; phi += sampleDelta)
+  float randomOffset = random(gl_FragCoord.xy) * sampleDelta;
+       for(float rawPhi = 0.0; rawPhi < 2.0 * PI; rawPhi += sampleDelta)
        {
-    for(float theta = 0.0; theta < ( 0.5 ) * PI; theta += sampleDelta)
+    float phi = rawPhi + randomOffset;
+    for(float rawTheta = 0.0; rawTheta < ( 0.5 ) * PI; rawTheta += sampleDelta)
     {
+      float theta = rawTheta + randomOffset;
       // spherical to cartesian (in tangent space) // tangent space to world // add each sample result to irradiance
       float x = sin(theta) * cos(phi);
       float y = sin(theta) * sin(phi);
       float z = cos(theta);
       vec3 tangentSample = vec3( x, y, z);

-      float randomOffset = mix(-0.1, 0.1, random(gl_FragCoord.xy));
-      vec3 sampleVec = tangentSample.x * right + tangentSample.y * up + tangentSample.z * normal + randomOffset;
+      vec3 sampleVec = tangentSample.x * right + tangentSample.y * up + tangentSample.z * normal;
         irradiance += (texture2D(environmentMap, nTOE(sampleVec)).xyz) * cos(theta) * sin(theta);
       nrSamples++;
     }
```

This seems to look good again while using the same number of samples, so maybe we can try using that method of adding a random offset?

image


I also noticed that the specular light still ends up looking a tad sharp even at low shininess (20 in this example):
<table>
<tr>
<td>


image


</td>
<td>

image

</td>
</tr>
<tr>
<th>This PR</th><th>1.9.0</th>
</tr>
</table>

Maybe we can try using more samples for the higher roughness levels? That probably involves using a higher loop limit, and then `break`ing out of the loop earlier for lower-roughness levels.

**Comment by sudhanshuv1** [comment]
Thanks for testing out these changes! To reduce sharpness in specular texture I tried using higher loop limit for `SAMPLE_COUNT = 400` . For lower roughness levels, I used this code to `break` out of the loop earlier:

```
  for (int i = 0; i < SAMPLE_COUNT; ++i)
  {
    float FLOAT_SAMPLE_COUNT = float(SAMPLE_COUNT);
    // break out at lower roughness levels
    if(FLOAT_SAMPLE_COUNT == pow(2.0,(roughness+0.1)*20.0))           
    {
      break;
    }
    vec2 Xi = HammersleyNoBitOps(i, SAMPLE_COUNT);
    vec3 H = ImportanceSampleGGX(Xi, N, roughness);
    vec3 L = normalize(2.0 * dot(V, H) * H - V);

    float NdotL = max(dot(N, L), 0.0);
    if (NdotL > 0.0)
    {
      prefilteredColor += texture2D(environmentMap, nTOE(L)).xyz * NdotL;
      totalWeight += NdotL;
    }
  }
  prefilteredColor = prefilteredColor / totalWeight;

  gl_FragColor = vec4(prefilteredColor, 1.0);
}
```
It breaks out at `SAMPLE_COUNT = 4` for `roughness = 0.0`, at `SAMPLE_COUNT = 16` for `roughness = 0.1`, and so on. The sharpness in the specular light was not noticeable:

|--------|--------|
|
1point9point0
 |

|
|1.9.0|After  making changes: `SAMPLE_COUNT = 400` and breaking out of the loop at lower roughness levels|

Using `SAMPLE_COUNT = 400` reduces the sharpness in specular light, but there is a catch - it does increase the execution time by 0.5 seconds as compared to the previous value of `SAMPLE_COUNT = 16`. I made a commit with the changes you recommended, updated `SAMPLE_COUNT` value to 400, and used a `break` in the loop for lower roughness levels. Please feel free to test this and suggest any further improvements.

**Comment by davepagurek** [comment]
I guess the reason why the randomness + dithering doesn't work as well for these specular textures is because they get progressively smaller and smaller, so single pixels become larger and larger relative to the whole texture. 

Anyway, the quality in your image looks good! We can see if we can squeeze a bit more performance out of it by maybe storing `pow(2.0,(roughness+0.1)*20.0)` in a variable outside the for loop to avoid recalculating it inside the loop. We probably also need to round it? Otherwise we might not have `FLOAT_SAMPLE_COUNT` ever reach *exactly* the number in question.

**Comment by sudhanshuv1** [comment]
Thanks for checking my previous code. Actually there was a bug in that commit, I had compared the value of `pow(2.0,(roughness+0.1)*20.0)` with `SAMPLE_COUNT` - `SAMPLE_COUNT` which has a fixed value, i.e., 400, so the loop runs 400 for iterations everytime instead of `break`ing out at expected values of `pow(2.0,(roughness+0.1)*20.0)` . I should have instead compared `pow(2.0,(roughness+0.1)*20.0)` with `i` - the current iteration of the loop.

Here is the corrected version of the code - :

```
void main(){
  const int SAMPLE_COUNT = 400; // 4096
  int lowRoughnessLimit = int(pow(2.0,(roughness+0.1)*20.0));
  float totalWeight = 0.0;
  vec3 prefilteredColor = vec3(0.0);
  float phi = vTexCoord.x * 2.0 * PI;
  float theta = vTexCoord.y * PI;
  float x = sin(theta) * cos(phi);
  float y = sin(theta) * sin(phi);
  float z = cos(theta);
  vec3 N = vec3(x,y,z);
  vec3 V = N;
  for (int i = 0; i < SAMPLE_COUNT; ++i)
  { // break at smaller sample numbers for low roughness levels
    if(i == lowRoughnessLimit)
    {
      break;
    }
    vec2 Xi = HammersleyNoBitOps(i, SAMPLE_COUNT);
    vec3 H = ImportanceSampleGGX(Xi, N, roughness);
    vec3 L = normalize(2.0 * dot(V, H) * H - V);

    float NdotL = max(dot(N, L), 0.0);
    if (NdotL > 0.0)
    {
      prefilteredColor += texture2D(environmentMap, nTOE(L)).xyz * NdotL;
      totalWeight += NdotL;
    }
  }
  prefilteredColor = prefilteredColor / totalWeight;

  gl_FragColor = vec4(prefilteredColor, 1.0);
}
```

I casted `pow(2.0,(roughness+0.1)*20.0)` into an `int` and then compared it with `i`. The loop breaks at different values of `lowRoughnessLimit` for different values of `roughness`:

| `roughness` | `lowRoughnessLimit` |
|--------|--------|
| 0.0 | 4 |
| 0.1 | 16 |
| 0.2 | 64 |
| 0.3 | 256 | 

The specular light was somewhat sharper than `1.9.0` but the difference is not noticable:

| 1.9.0 | This PR(latest commit) |
|--------|--------|
|  | afterMakingChanges|
| `1.9.0` | `SAMPLE_COUNT = 400` and breaking out at low roughness levels |

I again compared the execution time of `imageLight` using this code with the code I used in my first commit and with the one in `1.9.0` :

| Version | Execution time |
|--------|--------|
| 1.9.0 | 1674 |
| First commit in this PR (Using `SAMPLE_COUNT`=16 ) | 467 |
| Latest commit using the present code (Using `SAMPLE_COUNT` = 400 | 406 |

Increasing the value of `SAMPLE_COUNT` from 16 to 400 didn't increase the execution time so the gain is still the same. Hopefully the rectified code looks better!

**Comment by davepagurek** [comment]
Awesome, that's looking good, and it's great to hear that the performance ended up better than expected too! I'll play around with it a bit more tonight just to double check everything. Nice work!

**Review by davepagurek — APPROVED** [review]
Sorry for the delay, I finally got a chance to pull and take a look, everything looks great!

Thanks for your time iterating on this!

**Comment by sudhanshuv1** [comment]
@all-contributors please add @sudhanshuv1 for code

**Pull request merged**
