### PR TITLE
Set gl.BLEND in texture to allow transparent pngs && added line to webgl primitives

### PR DESCRIPTION
**Pull request by sixhat**
This deals with issue https://github.com/processing/p5.js/issues/1878 where users need to set pngs with transparency as textures. Until now the hack would be to call `fill` with a non-opaque color before calling `texture` or to manually enable the gl.BLEND mode with 

```javascript
gl = this._renderer.GL;
gl.enable(gl.BLEND);
gl.blendFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA);
```

This solution activates gl.Blend when a texture call is made.

### CODE REVIEW

**Comment by sixhat** [comment]
The latest commit also adds `line` to the webgl primitives as explained in https://github.com/processing/p5.js/issues/1638

**Comment by l3ehfar** [comment]
> ```js
> gl = this._renderer.GL;
> gl.enable(gl.BLEND);
> gl.blendFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA);
> ```

hi i can't figure out where should i put this? would you give me an example with code? should I put it in my setup function?

**Comment by stalgiag** [comment]
This isn't necessary anymore. Transparent pngs work out of the box now. [Here is an example.](https://editor.p5js.org/stalgiag/sketches/eTcSSKLWd)

**Comment by birkb85** [comment]
> This isn't necessary anymore. Transparent pngs work out of the box now. [Here is an example.](https://editor.p5js.org/stalgiag/sketches/eTcSSKLWd)

Hi.

I tested out the example and found that it does not behave as I expected..

If I modify the code to display two clouds, one rotating and the other one staying still.
The transparency only applies for the cloud to be transparent with the background, not the other cloud.
Sorry if my sentence above does not make enough sense, please try out this code:

```
let tex;

function preload() {
  tex = loadImage('cloud.png');
}

function setup() {
  createCanvas(400, 400, WEBGL);
  noStroke();
}

function draw() {
  background(0,200,0);
  
  push();
  texture(tex);
  rotateY(frameCount * 0.02);
  rect(-width/2, -height/2 + 40, 400, 400);
  pop();
  
  push();
  texture(tex);
  rect(-width/2, -height/2 - 40, 400, 400);
  pop();
}
```

Is this the intended behavior?
Then the transparency is really not much use, or what??

I have also attached an image demonstrating the problem.
See that the transparence does not apply between the two clouds, it only works for the background.
[Screenshot 2020-10-09 110828
](url)

**Pull request merged**
