### PR TITLE
Improve construction of cylinder and cone primitives and geometry validation

### LINKED ISSUE #2594: p5.Geometry._getFaceNormal generates many warnings in console via p5.Vector.mult
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Other (specify if possible)

#### Which platform were you using when you encountered this?

- [ ] Mobile/Tablet (touch devices)
- [x] Desktop/Laptop
- [ ] Others (specify if possible)

#### Details about the bug: 

- p5.js version: 
- Web browser and version: Chrome
- Operating System: macOS Sierra
- Steps to reproduce this:

Run example in manual-test-samples/webgl/geometry. It produces hundreds of errors saying,

`p5.Vector.prototype.mult: n is undefined or not a finite number`

which seems to trace up to trying to take the angle between two vectors `[0, 0, 0]` and a divide-by-zero NaN in p5.Geometry._getFaceNormal. happens for `cylinder` and `cone` on initialization, doesn't repeat again after first frame. other shapes in this example are fine.

### PR DESCRIPTION
**Pull request by tau-**
This resolves the issue of spurious warnings in p5.Geometry._getFaceNormal as described in #2594. Closes #2594

### CODE REVIEW

**Comment by Spongman** [comment]
while this does avoid the division by zero, i think it might be worth taking a look to see why these degenerate faces are being created in the first place, and possibly preventing that. i think the issue is that some of the faces are created with two identical vertices (maybe different vertices in the same 3d location, or just duplicate vertex indices). it might be worth putting a check in the geometry function to help track this down...

**Comment by tau-** [comment]
I agree, I will take a look at tracking down the degenerate faces. A sensible warning during geometry creation would be helpful. Worth keeping this check in or should the function rely on the correctness of the passed parameters?

**Comment by Spongman** [comment]
i think since this is an internal library method it would probably be more useful to see the error rather than to hide it, since this error is really just a symptom of another error in the caller. also, adding a zero-length normal merely pushes the error down into the glsl shader's lighting code and onto the graphics card which doesn't have any mechanism for reporting such errors.

**Comment by Spongman** [comment]
the reason this only occurs the 1st time through the draw loop is that the geometry is cached and the `computeNormals()` call is not repeated. if you were to resize the cone/cylinder every frame you would see this error each `draw()`.

**Comment by tau-** [comment]
Yes, each time a new cone or cylinder is added through `cone()` or `cylinder()` or their geometry is adjusted a new vertex set is computed with `_truncatedCone()` and this repeats many vertices in the array. This looks to be so that the code for creating the faces as a triple of vertex indices can be simplified. I am looking at removing that issue from `_truncatedCone()` and adding a descriptive error, either in `computeNormals()` or when a geometry is added to the buffer in `_renderer.createBuffers()`.

**Comment by tau-** [comment]
While the geometry issues are fixed, there is some adjustments needed to the vertexNormals.

**Comment by tau-** [comment]
Vertex and face normals are fixed now.

**Comment by Spongman** [comment]
this all looks good to me. i was wondering if it might make sense to do the drawScaledBuffers thing in this PR in order to simplify things even futher?

similar to some of the other primitives, the idea is to just create a single version of each geometry with unit sides/radius and just have the vertex shader scale everything appropriately. sometimes things get much simpler if all the lengths/angles are constant. just an idea...

**Comment by tau-** [comment]
Currently `drawScaledBuffers` is used for the cylinder but not the cone. Does that function handle the normals on the side of the cone correctly? Maybe things could be simplified for cones as well, which would give some speed ups if there happen to be a large number of distinct cone geometries in the scene. I will do some testing and maybe make a little "forest" sketch to test the performance gains of the drawScaledBuffer approach.

Also, I am considering moving the error to a warning with a more detailed message. Since the rendering is still successful in the cases where zero normals were generated, providing a helpful message may be enough instead of killing the sketch.

**Comment by Spongman** [comment]
yes, i believe the normals are handled correctly during the stretch for the geometries that do it currently. as for the cone, i'm not 100% certain, but i _think_ it should work. the trees will tell ;-)

**Comment by tau-** [comment]
The normals are correct, but no performance improvements in the quick test I ran. Regardless I think it is a nice simplification.

**Comment by kjhollen** [comment]
Cool, yes, I'll merge this once the geometry ID is updated! Thanks!

**Comment by tau-** [comment]
Totally right! I will remove the unneeded values from the cone geometry ID.

**Comment by kjhollen** [comment]
thanks! 🎆 & welcome!

**Pull request merged**
