### PR TITLE
add unregisterMethod function

### PR DESCRIPTION
**Pull request by capGoblin**
Addresses #[6422]

 Changes:

adds a `unregisterMethod` function to remove all instances of method m for the given event name.

@davepagurek as you addressed in #6422. i know this is completely unfinished waiting for your feedback.

#### PR Checklist

- [x] `npm run lint` passes
- [x] [Inline documentation] is included / updated
- [ ] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Comment by capGoblin** [comment]
anything else left other than unit tests?

**Comment by davepagurek** [comment]
Are you interested in also adding the new methods mentioned in #6422? It doesn't have to be in the same PR, but if you're interested, adding hooks that run before/after preload and setup would fully complete the feature requests in that issue.

**Comment by capGoblin** [comment]
cool! I would definitely love to work on adding those hooks in another PR. You can merge this PR if it looks good!

**Comment by davepagurek** [comment]
Sounds good! One last thing before merging, we should probably update the section in https://github.com/processing/p5.js/blob/main/contributor_docs/creating_libraries.md about registerMethod to mention the new API to unregister.

**Comment by capGoblin** [comment]
need any other changes to this .md file?

**Review by davepagurek — APPROVED** [review]
Looks good, thanks for keeping those changes!

**Pull request merged**
