### PR TITLE
Recreate first test tweet with alt formatting

### PR DESCRIPTION
**Pull request by stalgiag**
Continuing to troubleshoot tweet poll formatting.

cc @gr2m

Related to #4281

### CODE REVIEW

**Comment by stalgiag** [comment]
Screen Shot 2020-02-09 at 12 31 07 PM

yay!

**Comment by gr2m** [comment]
Beautiful 🎉 

<a href="https://twitter.com/p5xjs/status/1226605574638444545">image</a>

**Comment by stalgiag** [comment]
Note that I am still getting the error notification for one of the actions on merge.

Screen Shot 2020-02-09 at 12 38 08 PM

**Comment by gr2m** [comment]
Thanks @stalgiag, I'll be looking into this one

**Comment by gr2m** [comment]
Could you give me a link to where you see the error? I can't find it

**Comment by stalgiag** [comment]
I actually realize now that this error is being generated by a fork but I am receiving emails about it directly from Github after merging for whatever reason.

[Here is a link](https://github.com/Mattlk13/p5.js/actions/runs/36682356)

**Comment by gr2m** [comment]
could it be because of [this PR](https://github.com/Mattlk13/p5.js/pull/92) by https://github.com/apps/pull?

**Comment by gr2m** [comment]
Could you add this secret to your repository to add more debugging info to the logs of the failing action in your repo? https://github.com/actions/toolkit/blob/master/docs/action-debugging.md#how-to-access-step-debug-logs

Something is wrong with my check here: https://github.com/gr2m/twitter-together/blob/ce34c2516a2e3cb0325eebdbc82b0e514f47932b/lib/pull-request/create-check-run.js#L14 I'd like to better understand what. I think if you enable the logging, I can see the full event payload

**Comment by stalgiag** [comment]
Hi sorry just getting back to the computer. I added the `ACTIONS_RUNNER_DEBUG` secret to the repo. And yes good find with that pr and the Pull app, definitely seem related.

**Pull request merged**
