### PR TITLE
minify glsl files during release build

### LINKED ISSUE #3114: webgl: add .glsl minification to the build
i think, for release builds, it would be nice to minify the .glsl files.

### PR DESCRIPTION
**Pull request by Spongman**
this PR minifies the imported glsl files during the release (p5.min.js) build.

closes #3114

re: https://github.com/processing/p5.js/pull/3110#discussion_r207706332

### CODE REVIEW

**Comment by Zalastax** [comment]
Since this is an update to the build process I want to mention that if we follow through with #2503 we will need to adapt this code to fit.
We could just plug in the [rollup-plugin-glsl](https://github.com/vwochnik/rollup-plugin-glsl) but it seems like this code does some optimizations that are smarter than that. Perhaps we (I?) should consider turning the applicable code of this PR into a rollup plugin (again, if we decide to use rollup).

**Comment by lmccart** [comment]
https://github.com/processing/p5.js/issues/3114#issuecomment-420883245

**Comment by lmccart** [comment]
@spongman can we discuss over email? please drop me a line at hello@p5js.org and I will follow up. thanks!

**Comment by Zalastax** [comment]
It will be a lot easier to evaluate when we have a timeline, goals, and milestones. I think this is an important inclusion but I want the build system to be overhauled soon which would get a new way of achieving the same thing. Can we at least make sure this is included in that project?

**Comment by Spongman** [comment]
> when we have a timeline, goals, and milestones
ah fantasitc, are these going to be decided online somewhere?

**Comment by Zalastax** [comment]
Yes, [eventually](https://github.com/processing/p5.js/issues/2503#issuecomment-417892848).

**Comment by lmccart** [comment]
hey y'all i'm working as hard as i can here, i don't think this tone is cool. please be considerate, thanks.

**Comment by Zalastax** [comment]
Sorry if you regarded my comments as rude, I was just being terse. If you have any feedback please email me so I can adapt in the future.

**Comment by Spongman** [comment]
no offense taken on my part. would love to help.

**Pull request closed without merging**
