### PR TITLE
#565 fixing save when only one arg (string)

### PR DESCRIPTION
**Pull request by shiffman**
Quick change re: @therewasaguy's comment, thanks!

### CODE REVIEW

**Comment by shiffman** [comment]
I made this change in the browser and didn't run grunt so hopefully ok.

**Comment by shiffman** [comment]
Apologies for the error will fix this pull request.

**Comment by therewasaguy** [comment]
Looks like this was just an issue of a comment line passing the character limit. I fixed this in a PR that also fixes https://github.com/processing/p5.js/issues/567

**Comment by lmccart** [comment]
thanks!

**Comment by shiffman** [comment]
Thanks!!

**Pull request merged**
