### PR TITLE
More examples

### PR DESCRIPTION
**Pull request by Spongman**
i added a few new examples.

i had to add a check to skip during testing when webgl isn't supported.

### CODE REVIEW

**Comment by kjhollen** [comment]
ahhh I changed my notifications for the project and am just seeing this now. I'll try to review over the weekend! thank you for these.

**Comment by lmccart** [comment]
@kjhollen I reviewed this and all looks good, hope its ok I merged

**Comment by lmccart** [comment]
thanks @Spongman these are great!

**Comment by kjhollen** [comment]
yes thank you! 🎊

**Pull request merged**
