### PR TITLE
Fixed Tables saving to CSV improperly.

### PR DESCRIPTION
**Pull request by stevengreens10**
Resolves issue #1919 

Output from issue changes from:

id,
species,
name
0,
Pistachio,
Badger
1,
Canis Lupus,
Wolf

to: 

id,species,name
0,Pistachio,Badger
1,Canis Lupus,Wolf

I changed the function to pWriter.write() because pWriter.print() automatically creates a new line. Changing pWriter.print() so it doesn't do this would cause many other bugs since everything is written using the print() function.

### CODE REVIEW

**Comment by lmccart** [comment]
awesome!

**Comment by jps800** [comment]
I am facing exactly the same problem with savetable in csv format but
do not understand what solution has been found for this issue

Pls advise,

thanks

**Comment by jps800** [comment]
Is there anybody here to help me?

**Comment by limzykenneth** [comment]
@jps800 are you using the latest version of p5.js? If so can you share the csv you are using? Thanks.

**Comment by jps800** [comment]
I finally downloaded the latest release of p5.js and everything is fine now

Thks for your advise !

**Pull request merged**
