### PR TITLE
added Code of Conduct Contributing.md file

### PR DESCRIPTION
**Pull request by mayaman26**

### CODE REVIEW

**Comment by lmccart** [comment]
:+1:

**Comment by tchoi8** [comment]
cool.

**Comment by lmccart** [comment]
yeah! the way @mayaman26 has added it, if you make a new issue or submit a pr, it will automatically link you to this document, check it out: https://github.com/processing/p5.js/issues/new

**Comment by shiffman** [comment]
This is fantastic.

**Pull request merged**
