### PR TITLE
updated loadTable.  Tests currently fail.

### PR DESCRIPTION
**Pull request by workergnome**
This version fixes some outstanding issues with loadTable, but the tests need revised.  @kevinb7 is working on the test component.  We should consolidate before pulling.

### CODE REVIEW

**Comment by kevinb7** [comment]
I will pull your branch and see what I can do.  I have a sneaky suspicion that reqwest doesn't support ```type: 'csv'```.  I can't find it mentioned anywhere on https://github.com/ded/reqwest.

**Comment by workergnome** [comment]
It doesn't, but that means that it falls through, but still doesn't try to detect based on http response type. 



—
David Newbury
(773) 547-2272
david.newbury@gmail.com

**Comment by kevinb7** [comment]
I see... I have an old version of reqwest for some reason.  In the old version it defaulted to 'js' instead of falling through and not doing any kind of processing.  I'll update my reqwest and we should be good to go.  I need to eat first though.  If I don't get it done tonight it will be done early tomorrow morning.

**Comment by kevinb7** [comment]
https://github.com/workergnome/p5.js/pull/1 should fix the tests.

**Comment by workergnome** [comment]
That works like a charm.  Thanks, @kevinb7!  @lmccart, how and where is the best place to document how this works?

**Comment by lmccart** [comment]
thanks you two, this is awesome!
@workergnome I think it could go under this section: https://github.com/processing/p5.js/wiki/Development#testing

if it feels like that section is getting too big, we could break it out into it's own page and link to it from the dev doc.

**Pull request merged**
