### PR TITLE
Fixes webGL text() rendering on android 

### PR DESCRIPTION
**Pull request by aferriss**
Addresses the bugs in https://github.com/processing/p5.js/issues/3760

I think something is still wrong in way that attributes are created and set for text in webGL mode because this fix is more of a hack than a proper solution. Essentially what I'm doing is rebuilding the uv's right before they are bound to the shader. Previously, something was causing gl to lose track of the texcoord buffer, which would cause the drawElements error. 

I also moved some of the variables in the font shader out of the global scope and updated the functions that used them to match. 

I left the derivatives in place since they don't seem to be affecting my phone but I feel that it's worth thinking about changing in the future given the spotty support on mobile hardware.

### CODE REVIEW

**Comment by Spongman** [comment]
I don’t think there’s an easy way to remove the derivatives. Those values are not constant unless the glyph is parallel to the screen.

**Comment by aferriss** [comment]
@Spongman Agreed, but perhaps there's another anti-aliasing solution that doesn't require derivatives? Maybe it's not worth worrying about until someone reports an issue.

**Comment by Spongman** [comment]
yeah, i did check the support before using it: https://webglstats.com/webgl/extension/OES_standard_derivatives

**Comment by Spongman** [comment]
i think it would be better to separate different sets of changes into different PRs. this PR seems to contain two unrelated changes:
1) the shader variable renaming. is there a reason for this change, or is it just a style change?
2) uv rebinding. can you provide a repro case for this issue?

**Comment by aferriss** [comment]
@Spongman 

They're related in the sense that they are both intended to make font rendering more bulletproof on Android devices.

The variables in the shader aren't renamed, just moved out of the global scope of the shader. I've noticed that on some Android devices, placing non-const variables in the global scope can cause the shader to fail to compile. I think it's safer to just move them to the main function and pass them in to any shader that needs them.

For the other change with rebinding uvs, you can try running the simple text example (the star wars one) on am Android and you'll see it throw an error at draw elements. If you follow the error you'll find that webGL complains that the texture coordinate buffer has been enabled but not bound. 

There's probably a better fix for this, since as I mentioned above we shouldn't need to rebind them, but I couldn't determine what was causing my device to lose track of the buffer hence the explicit rebinding.

**Comment by Spongman** [comment]
can you try, in the original code, asserting `g.uvBuffer && gl.isBuffer(g.uvBuffer)` ? before the `this._bindBuffer` calls?

**Comment by Spongman** [comment]
are you able to determine if this is caused by the buffer having not been initialized yet, or if the buffer was initialized but has since been lost for some reason?

**Comment by aferriss** [comment]
@Spongman Didn't have a chance to look at this again until now. I believe that the uv buffer does indeed get initialized in createBuffers, but as you suggest, get's lost somewhere between the creation there and when it gets bound in the text renderer. `g.uvBuffer` is undefined on my android when the renderer tries to bind it, which is what causes the rendering to fail.

**Comment by Spongman** [comment]
ok, i think i understand what the problem is, and this is going to require a bigger fix than just the text stuff, it affects all retained-mode rendering.

the issue is that when creating a retained-mode geometry (any geometry, not just the glyph quad), it's checking the _current_ fill and stroke shaders for which buffers to create and which attributes to enable.

https://github.com/processing/p5.js/blob/6640d149348dea0a1b3df61f0cf8442222403a9f/src/webgl/p5.RendererGL.Retained.js#L171-L172

this means that if you choose a shader that doesn't have a particular attribute, then create a (cached) geometry, that geometry won't have a buffer created for it that corresponds to that attribute. then, if you switch the current shader to one that _does_ have that attribute, it will fail to render because that buffer won't have been created.

i have a branch (https://github.com/processing/p5.js/issues/3620) with some code that removes the shader stuff from the geometry code and delays the buffer creation & attribute binding until just before rendering. i will attempt to rebase that onto master. it might be useful to know if that fixes this buffer issue.

**Comment by Spongman** [comment]
any chance you can try this pen: https://codepen.io/Spongman/pen/QBjQoJ on your android devices?

it's using a build of p5 from my [render-buffers](https://github.com/Spongman/p5.js/tree/render-buffers) branch, compiled p5.js is [here](https://ci.appveyor.com/api/buildjobs/ao7fmg3h5fua0y93/artifacts/lib%2Fp5.js).

**Comment by aferriss** [comment]
@Spongman Your branch and the text example works on my device!

**Comment by stalgiag** [comment]
@Spongman works on my device as well!

@aferriss if you don't mind I think it might make sense to review and possibly merge #3769 first since it seems to address an underlying problem that would fix the uv buffer issue. Afterwards we can make a decision about moving the shader variables out of the global scope. How does that sound?

**Comment by aferriss** [comment]
@stalgiag That sounds like a plan. This PR was only resolving a side effect of a larger problem so if https://github.com/processing/p5.js/pull/3769 fixes that then I'm more than happy to close this.

**Comment by Spongman** [comment]
i do still think it's important to track down the `break;` issues you were seeing, though. for example, the font shader relies on being able to break out of a loop up to 250 bezier strokes in each axis. for most glyphs it's significantly less than that, but more intricate script fonts can approach that. i don't see a significant performance drop on my desktop GPU when forcing it to loop through all iterations, but on different hardware  doing so may cause a noticeable performance loss even on simple fonts.

**Comment by aferriss** [comment]
@Spongman I think the `break` issue was not a problem in the font rendering shader. I tried it on an iOS device and it rendered fine. 

Only the lighting shaders were causing problems when using break. My guess is that it's something related to the non-uniform control flow that I mentioned in https://github.com/processing/p5.js/pull/3755#issuecomment-496104370 but I haven't had time to go take another look. I think that instance, we're only looping 8 times so the performance hit should be relatively negligible.

**Pull request closed without merging**
