### PR TITLE
Converted to ES6 utils/sample-linter.js

### PR DESCRIPTION
**Pull request by abhinavsagar**

### CODE REVIEW

**Comment by abhinavsagar** [comment]
I guess the CI errors are unrelated.

**Comment by outofambit** [comment]
hey @abhinavsagar it looks like the CI errors are related to the changes here but i'm not sure how yet. i suspect there's a problem with using `import`/`export` in scripts that are used by Grunt. i can investigate what it would take to get Grunt to accept that syntax and can probably have it working in a few days. i'll keep you updated!

**Comment by abhinavsagar** [comment]
Yeah, thanks for the help.

**Comment by outofambit** [comment]
hey @abhinavsagar if you merge `master` into this branch, i think this should be good to go!

**Comment by abhinavsagar** [comment]
Closing/reopening

**Comment by abhinavsagar** [comment]
@outofambit Ping.

**Comment by sanketsingh24** [comment]
@abhinavsagar @outofambit I think this broke precommit hook. I keep getting this message-

```bash
❯ Running tasks for src/**/*.js
   ✔ eslint
   ✖ node ./utils/sample-linter.js
     →     at internal/main/run_main_module.js:17:11
✖ node ./utils/sample-linter.js found some errors. Please fix them and try committing again.

/home/sanketsingh24/Documents/sanket1/project1/p5/p5.js/utils/sample-linter.js:2
import eslint from 'eslint';
           ^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:718:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11


husky > pre-commit hook failed 
``` 
I don't know the root of this problem and maybe it is limited to my machine, Before this change, it was working fine.

**Comment by outofambit** [comment]
no worries @sanketsingh24! i've seen that same error a couple other times and haven't been able to track it down yet. how did you fix it?

**Comment by sanketsingh24** [comment]
I think all I did in between was to restart my system, didn't change anything in the code base

**Pull request merged**
