### PR TITLE
Remove uResolution uniform

### LINKED ISSUE #1621: Inconsistencies between Processing and p5 clipping plane parameters
As I mentioned in #1615, p5 WebGL's camera clipping planes (ie, the "near" and "far" parameters to `perspective()` and `ortho()`) don't quite work as expected. See my test case below. Basically, it draws three spheres at different depths, and if you explicitly set the clipping planes through one of the commented-out camera function calls, only the middle sphere is contained within the renderable area and the other two disappear. This works in Processing, but currently fails in p5.

(I've got a PR in the works that addresses this, but I thought I'd go ahead and clearly document the issue here for posterity.)

Processing test case:
```processing
size(200, 100, P3D);

noStroke();
fill(255);

float fov = PI/3.0;
float cameraZ = (height/2.0) / tan(fov/2.0);

//Uncomment either of these lines and only the middle sphere should be visible
//perspective(fov, float(width)/float(height), cameraZ - 20, cameraZ + 20);
//ortho(-width/2, width/2, -height/2, height/2, cameraZ - 20, cameraZ + 20);

translate(width / 2, height / 2, 0);

sphere(20);

pushMatrix();
translate(-40, 0, 40);
sphere(20);
popMatrix();

pushMatrix();
translate(40, 0, -40);
sphere(20);
popMatrix();
```

p5.js translation:
```javascript
function setup() {
  createCanvas(200, 100, WEBGL);

  var fov = PI/3.0;
  var cameraZ = (height/2.0) / tan(fov/2.0);

  //Uncomment either of these lines and only the middle sphere should be visible
  //perspective(fov, float(width)/float(height), cameraZ - 20, cameraZ + 20);
  //ortho(-width/2, width/2, -height/2, height/2, cameraZ - 20, cameraZ + 20);
}

function draw() {
  background(128);
  
  sphere(20);

  push();
  translate(-40, 0, 40);
  sphere(20);
  pop();
  
  push();
  translate(40, 0, -40);
  sphere(20);
  pop();
}
```

### PR DESCRIPTION
**Pull request by mindofmatthew**
The WebGL renderer and shaders apply a constant scaling factor called "resolution" to (almost) all position values. I can't quite tell what issues this was meant to resolve (most likely, they've been fixed in other ways as well), and in the interest of simplifying our shaders, I think we'd be better off removing it entirely.

This change does affect two existing pieces of API behavior, both of which I consider to be bugs. This PR fixes #1621 outright and slightly improves #1622, though there's still work to be done to fully address that issue.

@indefinit, let me know if you can think of any side-effects to this change that I may have missed. Thanks!

### CODE REVIEW

**Comment by indefinit** [comment]
Originally the resolution uniform was meant to handle canvas resolution (width/height).  Most of the time I've seen resolution uniforms inside the pixel shader because of per/pixel operations on textures / calculation of the fragCoord.  However I do agree that it's not really necessary inside of these vert shaders.

**Comment by mindofmatthew** [comment]
I definitely agree that we need a canvas width/height uniform for the reasons you mentioned, but the currently implementation of "uResolution" doesn't really seem to be that (for one thing, it's currently set to a constant value of 1000). My thinking here was to remove that old implementation to clear the way for adding in a new resolution uniform, and I can go ahead and add that in now.

One API question then: the closest thing in Processing is a uniform called "viewport" that's a vec4 with the values (0, 0, <width>, <height>). I'm not sure why it's a vec4—it seems to be mostly used by the wireframe shader. Do we want to implement that, or would it make more sense to implement a separate vec2 "resolution" uniform?

**Comment by indefinit** [comment]
@mindofmatthew I think a vec2 is sufficient but just in case I'm pinging @codeanticode for his weigh-in on vec2 vs. vec4 for viewport res uniform.

**Comment by codeanticode** [comment]
I agree, using a vec2 would make more sense. I don't see any place in the Processing code where a viewport with x and y different from zero could be used, so makes me think if we should replace it by resolution as well.

**Comment by codeanticode** [comment]
went ahead and added a resolution uniform to PShader. Viewport is still supported, but won't be set if cannot be found in the shader code. Use of resolution in pixel shaders is widespread enough for this to be included.

**Comment by mindofmatthew** [comment]
@indefinit As it turns out, I've already added a "resolution" uniform defined as vec2(width, height) to the shader branch (and then decided to go back and sort out the older "uResolution"). It sounds like that uniform is everything we'll want—and that will get added with the rest of the custom shader functionality.

Anything else that needs to happen in this PR before it can be merged?

**Pull request merged**
