### PR TITLE
Add YUIDoc for constants

### PR DESCRIPTION
**Pull request by Zalastax**
These constants are referenced in other documentation.
They therefore need to be documented to generate TypeScript types.

Is there a reason for some constants (not named _CONSTANT) not to have YUIDoc?

### CODE REVIEW

**Comment by kjhollen** [comment]
I was testing this out today and think the changes show up in two places:

1) in the search results on the reference page (click search API and see autocomplete dropdown, which seems ok for constants within the core for p5, but the dom constants do not link to which functions they are associated with)
2) for the DOM lib, AUDIO and VIDEO also show up in the list of p5.dom functions, but should probably be removed (run `grunt yui:dev` and click on the p5.dom link at top of page to see)

**Comment by kjhollen** [comment]
Yeah! Let's make another group on the p5.dom page for the constants.

**Comment by Zalastax** [comment]
Does this look fine?
These changes seemed like the most reasonable to add support for a Constants group.

**Comment by kjhollen** [comment]
yeah! awesome! built this and everything looks great.

**Pull request merged**
