### PR TITLE
adds select() and selectAll() to dom

### PR DESCRIPTION
**Pull request by futuremarc**
instead of `getElement()` and `getElements()`

### CODE REVIEW

**Comment by shiffman** [comment]
This looks great.  I guess my one question is whether we should use this to wrap `document. getElementById()`, etc. as in your pull request or if we should instead use `querySelector()` and `querySelectorAll()` behind the scenes?

https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector
https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll

Obviously for the end user the result should be the same but is there any benefit in terms of efficiency / maintenance?  

@brysonian and @lmccart any thoughts?

**Comment by shiffman** [comment]
Also, noting this pull request relates to discussion in #760.

**Comment by futuremarc** [comment]
From what I've read, `querySelector` and `querySelectorAll` may be up to 5 times slower than it's counterparts

**Comment by kadamwhite** [comment]
There's definitely a performance implication to using more complex selectors—this is why jQuery (technically Sizzle) will inspect the provided selector to try to [select the fastest possible operation](https://github.com/jquery/sizzle/blob/master/dist/sizzle.js#L219-L242)

A related video on the theory behind jQuery's performance: http://wordpress.tv/2011/09/19/john-resig-jquery-performance-and-new-features/ (One of the better conference talks I've seen, to boot.)

I admit I have some concerns about the direction we're going here, because these problems are non-trivial and I feel like we're taking an awkward middle road between not providing DOM functionality or providing limited (e.g. purely ID-based) querying, and trying to be jQuery. Would it make sense to conceptually limit our work here in favor of providing a basic toolset (which this PR does), and then coming up with a set of instructions for how to integrate with jQuery or Sizzle if you need to do more complex work? I've not been involved in the conversations around how we scope the DOM functionality so I may be missing prior threads of the conversation, so that opinion is volunteered without prior context. :)

**Comment by sepans** [comment]
Haven't run it but something like <code>p5.selectAll('#header .menu-item')</code> seems to returns null. The [regex](https://github.com/jquery/sizzle/blob/master/dist/sizzle.js#L135) in sizzle code @kadamwhite pointed to should fix that.

**Pull request merged**
