### PR TITLE
Merge from processing/master

### PR DESCRIPTION
**Pull request by AkashGutha**
Update from original repo

### CODE REVIEW

**Comment by AkashGutha** [comment]
how do i update my repo to latest commits from github site .. 
previously it was showing 12 commits behind procssing:master
now it is showing 1 commit ahead processing:master 
how do i solve this problem and align my repo with processing:master

**Comment by lmccart** [comment]
in terminal, from within your repo folder, you can type:
`git pull https://github.com/processing/p5.js.git master` and it should pull in the newest changes from processing master branch.

here is more info:
https://help.github.com/articles/syncing-a-fork/

**Comment by AkashGutha** [comment]
how to do it from the github site??

**Comment by lmccart** [comment]
there's no way to do it from the github site I don't think, except to delete your fork completely and fork it again.

**Comment by AkashGutha** [comment]
yea .. i just figured that out .. and did it .. thanks :)  ..
btw .. i'm new here .. need some help in adding a new library to addons ..
how do i get confirmation on adding the library?

**Comment by lmccart** [comment]
hi @AkashGutha, if you have created a new library for p5.js, you can email hello@p5js.org and I'll review and post on the website. if you are asking how to include an addon library, there are instructions on the bottom of the libraries page.

in general, the github issues are just for code bugs and feature development. if you have general programming or usage questions, a good place to post them is in the forum under p5.js: https://forum.processing.org/two/

**Comment by AkashGutha** [comment]
I'm writing a general Lsystem for p5 . can i add it to the addon libraries ?

**Pull request closed without merging**
