### PR TITLE
improved parameter validation

### LINKED ISSUE #1329: Use IS_MINIFIED to disable friendly debugger in minified builds
Currently, the friendly debugger is disabled by overwriting all relevant private p5 methods (basically `_validateParameters` and `_friendlyFileLoadError`) in the footer of the minified build (done via the gruntfile configuration for `uglify`).

However, a disadvantage of this is that the _code_ for the friendly debugger is still present in minified builds--it's just overwritten at run-time to be a no-op.

In #1318, I introduced a new uglifyJS-based global defined only in minified builds called `IS_MINIFIED`. If we use this variable anywhere in p5's source code like so:

``` js
if (typeof(IS_MINIFIED) === 'undefined') {
  // We're in an unminified build, do friendly debugging logic etc. here
} else {
  // We're in a minified build, probably just do nothing.
}
```

then uglifyJS will realize that the conditional evaluates to a constant and will _remove_ the first branch when it generates the minified build. This is called "dead code removal" and it's nice because it means the minified build will really be as small as possible.

More background on how this works is explained here: https://github.com/processing/p5.js/pull/1318#issuecomment-202450591

### PR DESCRIPTION
**Pull request by Spongman**
this PR improves the parameter validation a little:
- it now handles array types (eg. Number[]) and checks the types of the array's elements.
- it checks object types (eg. p5.Color)
- it checks Constant values (eg. HSB|RGB, etc...)
- it checks Integer values are integral. (and updated doc comments where appropriate)
- it pre-calculates more of the work needed to do the validation, and caches the `lookupParamDoc` results. performance is significantly improved in debug.
- validation has been added to more p5 methods.
- the validation code & data.json is excluded from IS_MINIFIED builds, reducing the un-deflated size from 1,100KB to 389KB.

fixes #1329, #785

### CODE REVIEW

**Comment by Spongman** [comment]
it looks like everything changed in error_helpers.js but that because I had to split apart the parameter validation (which is conditional on IS_MINIFIED) and the top-level warning stuff (which is not). also, jslint is fussy about the ordering of functions inside `{}` blocks (but not elsewhere, for some reason).

**Comment by meiamsome** [comment]
This looks like good improvements. It may be worth cherry picking 68de25a and 464c2f5 from #2177 into this PR & then that PR can be rebased onto this.

**Comment by Spongman** [comment]
ok, this does the right thing with the argument count error. i fixed up some docs to accomodate.

i also added the location of the error in the message, which you can click on to navigate in chrome's devtools .

**Comment by meiamsome** [comment]
Ah, that's good that 2bb7aa removed the need for that extra parameter to `createCanvas`! It's a shame that Travis has your account blacklisted and won't run the tests on this PR - perhaps you can give them a shout to un-blacklist you?

**Comment by Spongman** [comment]
travis? blacklisted? i have no idea what that is.

**Comment by meiamsome** [comment]
It's the thing that's supposed to automatically run tests on PRs to check they run fine.

Your PRs are marked as "abuse detected" here: https://travis-ci.org/processing/p5.js/requests
I'm not sure why, though, https://github.com/travis-ci/travis-ci/issues/6942 says you should just email them to get it cleared up!

Eitherway, I'm just confirming this passes tests and afaics is ready for merge!

**Comment by Spongman** [comment]
I don't know what I have to do to get the abuse thing cleared. I have tried emailing them, filing an issue and contacting one of the devs directly, but all I'm getting is static. It seems like their process for handling false positives is broken. Oh well...

**Comment by Spongman** [comment]
i'm sorry if I messed up the merge, it seems like i have a love/hate relationship with git: it just loves to hate me.

**Comment by lmccart** [comment]
this is great, sorry it took so long to merge

**Pull request merged**
