### PR TITLE
[p5.js KO]Update contributor_guidelines.md

### PR DESCRIPTION
**Pull request by yunyoungJang**
Changes: change image path

#### PR Checklist

- [ ] `npm run lint` passes
- [ ] [Inline documentation] is included / updated
- [ ] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Comment by yunyoungJang** [comment]
@designerSejinOH @yinhwa PR 올렸습니다! 🙌

**Review by designerSejinOH — APPROVED** [review]
@yunyoungJang 확인했습니다!! 빠른 수정 감사드립니다 ☺️
승인하고 머지 요청드릴게요! @yinhwa

**Comment by designerSejinOH** [comment]
@Qianqianye @limzykenneth We've fixed the 'image path issue' mentioned before and request a PR merge ☺️

**Comment by Qianqianye** [comment]
Thanks!

**Pull request merged**
