### PR TITLE
Changed em tags (asterisks) to multiplication symbols

### PR DESCRIPTION
**Pull request by Acha0203**
Changes:
Changed em tags to multiplication symbols in src/core/transform.js

before:
@param  {Array} arr an array of numbers - should be 6 or 16 length (2\*3 or 4\*4 matrix values)

after:
@param  {Array} arr an array of numbers - should be 6 or 16 length (2×3 or 4×4 matrix values)
 
#### PR Checklist

- [x ] `npm run lint` passes
- [x ] [Inline documentation] is included / updated
- [x ] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Comment by inaridarkfox4231** [comment]
Thank you for noticing mistake!
That's right, but there are other mistakes.

エックスとばつ

```js
 /**
 * @param  {Number} a numbers which define the 2×3 or 4x4 matrix to be multiplied
 */
```
As you can see from this, the multiplication symbol "×" and the alphabet "x" are mixed. So I think you should fix this as well. 
I think the multiplication symbol is more appropriate.

**Comment by Acha0203** [comment]
I have changed the characters of x to multiplication symbols. Thank you!

**Comment by Acha0203** [comment]
I have entered the command you said and committed the results. If you have any problems or questions, please let me know. Thank you!

**Comment by limzykenneth** [comment]
Looks good. Thanks!

**Pull request merged**
