### PR TITLE
Modified the image() function(#3966)

### PR DESCRIPTION
**Pull request by singhvisha**
Modified the image() function so that image don't get affected by material/lighting condition in WEBGL mode(#3966)

### CODE REVIEW

**Comment by singhvisha** [comment]
hi @stalgiag ,sorry for the delay.my college exams were going on.
Can you please review it?

**Comment by stalgiag** [comment]
Hi @singhvisha it might be better to do this in the [p5.RendererGL.prototype.image](https://github.com/processing/p5.js/blob/master/src/webgl/3d_primitives.js#L1698) rather than doing that check for 3D. This will help with organization. Also you may be able to call [`noLights()` ](https://github.com/processing/p5.js/blob/master/src/webgl/light.js#L869)instead to avoid rewriting code.

**Comment by singhvisha** [comment]
Hi @stalgiag ,Can you please review it?

**Comment by stalgiag** [comment]
Hi @singhvisha. Close! But you call `noLights()` after the drawing is complete. This won't have the affect of changing the material/lighting conditions of the image, instead it will just turn off all lights before continued drawing.

It is important to test your changes to ensure they work whenever you edit the source code. I often use the empty manual test example to do this. In this instance a sketch like this should reveal whether your changes are working.

```js
let img;

function preload() {
  img = loadImage('../webgl/assets/cat.jpg')
}

function setup() {
  createCanvas(500, 500, WEBGL);
}

function draw() {
  background(0);
  pointLight(200, 200, 200, 0, 0, 0);
  translate(-200, 0, 0);
  box(100);
  image(img, 150, -50, 100, 100);
  translate(400, 0, 0);
  box(100);
}
```
Note that example only works from `test/manual-test-examples/empty-test/sketch.js`. The above example should have an unlit image with the inside edges of the two boxes lit by the point light.

**Comment by singhvisha** [comment]
hi @stalgiag,
I have run the example locally this time for the changes that I have made in the source code.It seems to working for what you have suggested above.Could you please review the code?

**Comment by singhvisha** [comment]
@stalgiag 
Could you please review the above changes?

**Comment by stalgiag** [comment]
Hi @singhvisha 

Looks good! Good catch on the fact that `noLights()` doesn't set `rendererGL._enableLighting = false;`. That should always be set to false when disabling the lights. It might be a good idea to move that line into the `noLights()` function to ensure that state is always managed correctly.

**Comment by singhvisha** [comment]
hi @stalgiag 
I have added enablingLighting property in light.js.Could you please review?

**Pull request merged**
