### PR TITLE
convert to string in text function

### PR DESCRIPTION
**Pull request by limikael**
Hi!

This is somewhat related to https://github.com/processing/p5.js/issues/514.

I modified the `text` function so it tries to convert anything it gets to a string, before it was only numbers. Don't know if there was a particular reason why it should only convert numbers, but there was none I could think of...

Anyway, one of the reasons why it is useful with arrays is if we want to read a color and display it, like:

```js
var color=get(x,y);
text(color,10,10);
``` 

Actually, this is something that worked before the fix to https://github.com/processing/p5.js/issues/514, but I can't say why it worked really. But anyways, I found it useful.

I also added a test in the examples folder. I mainly added this as a test to see if it worked. Maybe it is more bloat of that folder than something useful, in that case I can remove the test again...

### CODE REVIEW

**Comment by lmccart** [comment]
this is great, thanks! I think your idea to leave the example out to conserve space makes sense. I'm going to close this pr just to keep track of things, but will you reopen once you've removed the example and I'll merge it in?

**Comment by limikael** [comment]
Ok fixed it now...

Doesn't seem like I have the ability to reopen though... :(

Do you want me to create a new pull request?

**Comment by lmccart** [comment]
ah yes go ahead and open a new one and I can merge it in. thanks!

**Comment by limikael** [comment]
Ok it is here:

https://github.com/processing/p5.js/pull/558

**Pull request closed without merging**
