### PR TITLE
Updated dev docs for ES6

### PR DESCRIPTION
**Pull request by hsab**
Updated the developer documents to reflect the recent changes associated with ES6

### CODE REVIEW

**Comment by hsab** [comment]
@lmccart how does this look? I was about to merge but wanted to make sure all is ok before doing so.

**Comment by stalgiag** [comment]
⚡️  ⚡️  ⚡️ 
@hsab unrelated but this might be a good time to add yourself to the [contributors list](https://github.com/processing/p5.js/issues/2309)
⚡️  ⚡️  ⚡️

**Comment by hsab** [comment]
@stalgiag thanks for the reminder. I didn't run the generate cli, but added myself to the list.

**Comment by lmccart** [comment]
@hsab looks great, merging now. thanks!

**Pull request merged**
