### PR TITLE
Fixes wrong triangle stroke

### LINKED ISSUE #3065: Wrong stroke rendering with beginShape and large strokeWeight
#### Nature of issue?

- [x] Found a bug

#### Most appropriate sub-area of p5.js?

- [x] Core/Environment/Rendering

#### Which platform were you using when you encountered this?

- [x] Desktop/Laptop

#### Details about the bug: 

- p5.js version: http://alpha.editor.p5js.org/carmolim/sketches/HyfkoNCzX
- Web browser and version: Chrome  67.0.3396.99
- Operating System: MacOS 10.13.5 (17F77)
- Steps to reproduce this:
http://alpha.editor.p5js.org/carmolim/sketches/HyfkoNCzX
```
function setup() {
  
  createCanvas(400, 400);
  background(0);
  
  noFill();
  stroke(255);
  strokeWeight(10);
  
  scale(3);
  
  beginShape(TRIANGLES);
    vertex(30, 75);
    vertex(50, 20);
    vertex(80, 75);
	endShape();
}

function draw() {
}
```

Bug

### PR DESCRIPTION
**Pull request by AdilRabbani**
Fixes wrong triangle stroke with beginShape(). Closes #3065

### CODE REVIEW

**Comment by mlarghydracept** [comment]
@AdilRabbani maybe I am missing something but I am unable to recreate the bug that you are addressing with this PR. When I run the code from #3065 on a build from processing/master, I get expected results.

screenshot 36

**Comment by AdilRabbani** [comment]
This is strange, I'm getting the same result as shown in the bug from the master build...

bug.

I went through a canvas example first and then opened this PR. Can you run this canvas example as well?

```
   <canvas id="canvas"></canvas>
  <script>
    var canvas = document.getElementById('canvas');
  if (canvas.getContext){
    var ctx = canvas.getContext('2d');
		
    ctx.lineWidth = 10;

    ctx.beginPath();
    ctx.moveTo(75,50);
    ctx.lineTo(100,75);
    ctx.lineTo(100,25);
    ctx.closePath();
    ctx.stroke();
  }
  </script>
```

One thing you may notice is that we need 1 moveTo and 2 lineTo methods to draw a triangle. The closePath method at the end actually closes the triangle for us.

**Comment by mlarghydracept** [comment]
Okay actually that was just my mistake. I built from your PR and then used watch:quick to compare to master not realizing that my test sketch referenced the minified version of the library and watch:quick doesn't update the min file. Sorry about the confusion!

I see now what you mean. The only question I still have is whether it makes sense to merge into webgl-gsoc-18 for a small fix to the 2D renderer. I understand that it helps separate out the work that you are doing but for something small that isn't related to GL it might make sense to merge directly into master. What do you think @kjhollen ?

**Comment by kjhollen** [comment]
Either way works for me! Adil, maybe you can keep a list of your bug fixes like this that get merged directly into master? Then it will be easier for you to find & document them as part of the GSOC documentation / end of summer write-up.

**Comment by AdilRabbani** [comment]
Yes. I'll keep track of all the bug fixes. 😊 So should I submit another pull request to master or this could be merged?...

**Comment by kjhollen** [comment]
Yeah, go ahead and change the branch to master :)

**Comment by AdilRabbani** [comment]
Okay....This also merges all updates to the webgl-gsoc-2018 branch. I think I should open another pull request which only adds the bug fix? @kjhollen

**Comment by kjhollen** [comment]
Yes please, can you make a new PR with just the bug fix? thanks!

**Pull request closed without merging**
