### PR TITLE
Negative dimensions will mirror rect() again

### LINKED ISSUE #7353: rect() : inputting negative values for width and height doesn't yield a flipped rectangle anymore...absolute values of width and height are considered
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [X] Other (specify if possible)

### p5.js version

v1.11.1

### Web browser and version

129.0.6668.112

### Operating system

ChromeOS

### Steps:
1. use the rect() function with negative values passed in for width and height

### Snippet:

```js

rect(100,100,40,40)
rect(100,100,-40,-40) // gives the same rectangle
```

### PR DESCRIPTION
**Pull request by martinleopold**
Resolves #7353

 Changes:

Fix a regression with negative values for width and/or height on rect(), ellipse(), and arc()

 Screenshots of the change: 

N/A

#### PR Checklist

- [x] `npm run lint` passes
- [x] [Inline documentation] is included / updated
- [x] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Comment by martinleopold** [comment]
This resolves the immediate issue by adjusting the position of the shape when using negative dimensions.
I'm wondering if we need to look into what happens with textured shapes. In this case the texture should actually be flipped i.e. properly mirrored, I guess?

**Review by perminder-17 — CHANGES_REQUESTED** [review]
Thank you so much for your hard work on this! I truly appreciate the effort you've put in. There is one potential issue I wanted to mention regarding texture image handling. While you’ve done a great job adjusting the positioning in CORNERS, CORNER, etc., it seems that the image itself isn’t being flipped when necessary—only the position is being shifted. Adding a flip where needed could enhance the solution. Please let us know if there’s any way we can assist in exploring or addressing this aspect.


### Expected:
image

### Your's:
image

**Comment by martinleopold** [comment]
@perminder-17 Thanks for pointing that out, will look into it.

**Comment by martinleopold** [comment]
I think my latest commit should restore the original behavior. This means that rect() will mirror, while ellipse() and arc() will NOT.

**Pull request merged**
