### PR TITLE
Add example for OrbitControl() : WebGL

### PR DESCRIPTION
**Pull request by a-y-u-s-h**

### CODE REVIEW

**Comment by kjhollen** [comment]
great @a-y-u-s-h! can you add an alt-text description for this?

**Comment by lmccart** [comment]
ooh we should add this info to the wiki page:
https://github.com/processing/p5.js/wiki/Inline-documentation

**Comment by lmccart** [comment]
ok i did. @a-y-u-s-h check out the section under "adding alt-text"

**Comment by kjhollen** [comment]
thanks @lmccart!

**Comment by a-y-u-s-h** [comment]
Thanks! @lmccart @kjhollen 

I just noticed that I forgot to put some tags : 

`<div> <code> </div> </code>`

I don't know how it didn't show any error. I'll send another PR after fixing them both.

**Comment by lmccart** [comment]
thanks!

**Pull request merged**
