### PR TITLE
p5.Element.position now really absolute

### PR DESCRIPTION
**Pull request by molleindustria**
addressing:
https://github.com/processing/p5.js/issues/694

### CODE REVIEW

**Comment by lmccart** [comment]
I had to reverse this one because it seemed to break cases where there was no parent element. For example:

```javascript
function setup() {

  // create canvas
  createCanvas(710, 400);
  greeting = createElement('h2', 'what is your name?');
  greeting.position(20, 5);

  textAlign(CENTER)
  textSize(50);
}
```

**Comment by kadamwhite** [comment]
What about something like this (untested):
```js
var $self = $(this.elt);
var $parent = $self.parent();
var offset = $parent.length ? $parent.offset() : $self.offset();
```

**Comment by molleindustria** [comment]
The example works with this check, but honestly I'm not familiar with the architecture

if(this.parentNode != null)
      {
      var offset = $(this.elt).parent().offset();
      this.elt.style.left = (x-offset.left)+'px';
      this.elt.style.top = (y-offset.top)+'px';
      }
    else
      {
      this.elt.style.left = x+'px';
      this.elt.style.top = y+'px';
      }

This is the example I'm using

function setup() {
  // create canvas
  createCanvas(710, 400);
  
  var myCanvas = createCanvas(600, 400);

  //in the index <div id='myContainer' style="margin-left:100px;"></div>
  myCanvas.parent('myContainer');
  myCanvas.position(0,0);
  
  greeting = createElement('h2', 'what is your name?');
  greeting.position(200, 5);
  
  background(200,0,0);
  textAlign(CENTER)
  textSize(50);
}

**Comment by molleindustria** [comment]
Adam's code looks better but gives the same problem. 
Apparently any call to $(this.elt) in absence of a parent throws an error :person_frowning:

**Comment by molleindustria** [comment]
Actually I didn't consider that element.position is a method of many other things beyond canvas, and I can imagine people wanting to position dom elements in relation to the canvas coordinates. 

Maybe we can leave .position() as it is/was and add a .winPosition() (or something like that) to set the absolute position from the windows 0,0. That would be consistent with the other window-related methods.

**Pull request merged**
