### PR TITLE
Adds immediate and retained drawing modes in webgl. adds more webgl examples.

### PR DESCRIPTION
**Pull request by indefinit**
Immediate and retained drawing modes to support beginShape() and endShape() as well as 3d primitives.  xyz drawing origin now defaults to center of screen instead of top left.  If you want to go back to the Processing / OF style 3D origin, it's as easy as calling the function: 

```
originMode('TOP_LEFT');
```

### CODE REVIEW

**Comment by lmccart** [comment]
cool. just wondering about the origin move. is this a break from processing? completely trust your decision, but wondering if you could elaborate a bit on the thinking here just so we have that documented in the thread?

**Comment by indefinit** [comment]
Sure!  I meant to send a full RFC (which is still definitely encouraged so if you or others objects to these changes or think it can be done more intuitively, please let us know).

The motivation behind originMode() is to reduce confusion around coordinates when drawing in 3D, something that never really felt that intuitive in Processing.  In a way this is an attempt to correct that feeling, but also we give users a fallback (```originMode('TOP_LEFT')```) if they are used to the Processing style.

An example:  If you want to draw a box in Processing (P3D), you could write ``` box(40); ``` where 40 is the dimension value for width,height, and depth.  Not only is it often a surprise to new users when their box appears in the top left corner, but it also breaks convention from other drawing methods in P2D mode.  For example, ``` rect(x,y,width,height)``` provides both dimensions and coordinates.  I think it's really nice and succinct that box has a limited number of parameters in its signature, so I'd prefer not to go crazy and break that convention.  However, if we keep ```box(width,height,depth)``` but were to move our 0,0,0 origin to the center of our canvas, we aren't necessarily changing the coordinate system- rather we're changing where our eye aligns to the origin, without immediately introducing other concepts like view frustum, fov, clipping plane, etc.

Another inspiration for the change:  looking at some common 3D modeling applications like Blender, Maya, Rhino, and C4D- all start with the camera pointing at a centered origin.  Perhaps many users will have some fluency in these software applications and the change will feel like a smooth transition into coding in 3D.  

It would be awesome if people use the webgl renderer for both 2D and 3D drawing, in which the former case would be pretty annoying if our origin were centered.  That's why I think it's important to have an override like 'TOP_LEFT', to give users more flexibility.  However, my assumption is that the majority of users will go to webgl mode for 3d first, and 2d drawing second.  If that is the case, then having a centered xyz origin should make a better user experience in 3D, along with a consistent fallback in 2D or 3D if preferred.  

What do you think?

**Comment by shiffman** [comment]
First, all of this work is amazing, so excited to see so much progress with the webgl renderer.  I always felt this issue was solved (for me) with having `translate(width/2, height/2)` as the first line in `draw()` for just about every 3D example.   I guess perhaps your point is if that is in every example, why don't we just make the center the default?   I don't have a good answer to that and maybe it is time for such a break.  I wish there was another approach besides adding another "mode" function to the API?   I worry that the code behaving differently just with the change of renderer will be confusing and searching for `originMode()` might not be obvious?  A common workflow I do see is writing a sketch and then flipping to a different renderer to see if it runs faster.  But I do think that I might not be able to see past what I am so used to and hesitate to offer this resistance.  (Related question: do we need a 'web_gl_2d'?)

**Comment by lmccart** [comment]
@indefinit this all makes sense to me, though I hear @shiffman's concerns. I'd suggest we make this intuitive for whatever the most common use case of the renderer is. My intuition is that this aligns with the scenario you've described above. 

One question, would `translate(-width/2, -height/2)` work the same as `originMode(TOP_LEFT)`? I might prefer this for the reasons @shiffman mentions of having to learn another mode and command.

I think we should be sure to document it really well. We could add a note to the `createCanvas()` function about this (maybe this is already in there, I haven't looked).

**Comment by indefinit** [comment]
@lmccart yes, technically running translate(-width/2,-height/2) will do the same thing as originMode('TOP_LEFT').  I hear ya on not having to learn another mode or command, I was worried that always defaulting to centered drawing without a command to undo that functionality would be awkward.  

But @shiffman , you make a good point about "modes" , maybe calling it a mode is too heavy handed.  I feel like the fewer modes we have the better for brevity and clarity.  Personally I feel webgl is great because it refers to the renderer which is agnostic of 3d or 2d behavior.

**Comment by shiffman** [comment]
I feel good about extra levels of documentation for this change and using `translate(-width/2, -height/2);` when necessary.   @indefinit I am 100% on board with `'webgl'` not being about 2d or 3d.  The reason we have `P2D` and `P3D` in Processing is that they actually behave differently (higher quality for 2D) but it sounds like there is not an analogous scenario here for webgl.

**Comment by karenpeng** [comment]
Ah, didn't see this conversation until now. Here're a few explanations I want to add to @indefinit 's , and also some thoughts about the discussion.<br/>

In 3d, there's the concept of <b>camera</b>, it determines how you see the world. Even though the origin of the world is set to be the top left corner, it does not necessarily put the shape in the exact top left corner because of the camera.
But if the origin is in the center, the shape will always appear in the center, this won't cause any confusions to users. Hence I think center is better for anyone who begins with 3d, also it's a convention of 3d softwares as @indefinit mentioned.<br/>

Then why does ```LEFT_TOP``` come up? Before jumping in, it's necessary to explain how shapes work. And @shiffman, it's different drawing 3d and 2d primitives in webGL in p5 now:<br/>


 * On one hand, we have 3d primitives. </br>
Like```box```,```sphere```,```cone```,```cylinder```, etc. The way they are being drawn, it's that we take the arguments to generate a buffer <b>ONCE</b>, then use this buffer again and again in the draw loop.
This benefits us with a better performance. For instance, the performance sketch inside the example folder, 1,000 sphere works as 50 FPS (on my laptop). Without doing this it's almost impossible to achieve.
But this means we can't change the shape of the geometry on the fly. That's not the case for below: </br>

 * On the other, we have 2d primitives in 3d space as well.</br>
Like ```triangle```, ```line```, ```quad```, also ```beginShape``` and ```endShape```. It's a convention from Processing. It's ok to change the vertex position on the fly. 
Yes you could tell that the buffer is being recreated every frame. It benefits us the flexibility to draw shapes yet worsens the performance. But since these shapes have much lesser vertices than 3d primitives, it's not that bad.

Ok now, why```LEFT_TOP```? 
Besides the Processing convention, it's also because 2d primitives takes position as arguments. In a center origin world, one has to write```line(-100, 0, 0, 100, 0, 0)``` in order to make it center align, which is something new that Processing users need to adapt to. That's why we want to put back the origin.</br>

I agree with @shiffman 's concern and @lmccart  & @indefinit 's suggestion, ```translate(-width/2, -height/2)``` is more appropriate here, we have to documented it well. I'll go back and change the code.

**Comment by lmccart** [comment]
Thanks @karenpeng and @indefinit for the thorough explanation. I think this all makes sense!

**Comment by karenpeng** [comment]
* a side-note:</br>
The changing shapes on the fly idea we are using for 2d primitives in 3d (so-called 'immediate mode') is <b>deprecated</b> in openGL 3.0 mainly because its performance is not optimal.

Actually the ```beginShape```,```endShape``` is fake, webGL doesn't have ```Begin/End primitive specification```, and it's <b>deprecated</b> in openGL. 

See this [list](https://www.opengl.org/wiki/History_of_OpenGL#Deprecation_Model)  for deprecated model.<br/>

I keep it for now considering it's useful in some scenarios. But it's nice to be open up for discussion.

**Comment by karenpeng** [comment]
Hey,  just wanna double check, based on our general consensus. Is originMode() to be kept or removed?

**Comment by codeanticode** [comment]
Hi, first of all congratulations to @karenpeng and @indefinit for the great work with the webgl renderer!

On the immediate mode discussion, my view is that it is indeed useful and should be preserved. Immediate rendering has been part of Processing since its beginnings and address the need to draw geometry that does not fit a retained/scenegraph structure well, for example dynamic shapes that are generated on the fly and can potentially change in every frame (as it is the case with generative graphics). The advantage of the immediate mode is perhaps not so apparent when focusing on only on primitives (box, sphere, etc), but becomes more clear when you think of how beginShape()/endShape() works by letting you set arbitrary vertices at any moment.

While it is true that OpenGL deprecated the immediate API (glBegin/End), I don't think this has to be taken as a reason to remove the immediate mode in Processing. First of all, OpenGL is a low-level API meant to build higher-level APIs and applications with their own unique sets of priorities and needs. Secondly, the justifications behind the deprecation in OpenGL (mainly optimized use of graphics hardware, maybe a shift towards scenegraph-based game engines that benefit more from a retained mode API?) do not necessarily translate to the main usage scenarios of Processing (teaching, sketching, etc).

With regards to the originMode('TOP_LEFT') suggestion, my opinion would be not to add it, since it suffices to just use a translate(-width/2, -height/2) call when needed

**Comment by karenpeng** [comment]
Thanks @codeanticode 's insightful opinion, I do agree on p5/Processing's educational use case, it's good to keep such features. Yet I personally find ```beginShape```  ```endShape```is one of the hardest api in Processing, they have to be explained well.

@lmccart originMode is removed, and there're examples of with/without translating the origin, I think the code is good to go.

**Comment by karenpeng** [comment]
oh just a note @lmccart , a npm module 'brfs' is added to transform shader files.

**Comment by lmccart** [comment]
great!

**Pull request merged**
