### PR TITLE
Fix #4421

### LINKED ISSUE #4421: Animated Gif doesn't work inside a createGraphics()?
I’m trying to display animated gif within an image created with createImage() but it apparently doesn’t work with the great new gif update made for p5.js? Is this possible? Or am I forgetting something?

let img, gif;

function preload() {
  gif = loadImage('assets/test.gif');
}

function setup() {
  createCanvas(960, 540);
  img = createImage(320, 180);
}

function draw() {
  img.image(gif,0,0);
}

II have also noticed that you cannot get a mask of animated gif with the mask() function either, it is right?
https://p5js.org/reference/#/p5.Image/mask

#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [x] Image
- [x] IO
- [ ] Math
- [ ] Typography
- [x] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

### PR DESCRIPTION
**Pull request by DivyamAhuja**
Resolves #4421 

 Changes:

I went with the hacky way to fix this by checking if `this._pInst` is instance of `p5.Graphics`

Test Run:
https://editor.p5js.org/DivyamAhuja/sketches/2saib5V_V

#### PR Checklist

- [x] `npm run lint` passes
- [ ] [Inline documentation] is included / updated
- [ ] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/master/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/master/contributor_docs#unit-tests

### CODE REVIEW

**Comment by stalgiag** [comment]
Hi @DivyamAhuja thanks for jumping on a quick fix!

My instinct is to say that it might be better to make `deltaTime` a getter on `p5.Graphics`. Then we can reliably assume that it is correct everywhere in the codebase, preventing future problems like this one.

Adding something like this to [the p5.Graphics constructor](https://github.com/processing/p5.js/blob/master/src/core/p5.Graphics.js#L56) would make it correct everywhere:
```js
Object.defineProperty(this, 'deltaTime', {
    get: function() {
      return this._pInst.deltaTime;
    }
  });
```
There is maybe a better way to do it but this is what comes to me immediately.

**Comment by DivyamAhuja** [comment]
Yeah Nice idea @stalgiag . I totally forgot that we can just do this and was thinking more complex way of doing same. I will update PR right now,as this way seems more elegant

**Comment by stalgiag** [comment]
Thanks @DivyamAhuja!

@limzykenneth does this seem like an okay approach to keeping `deltaTime` correct on the `p5.Graphics` objects?

**Comment by limzykenneth** [comment]
Seems like a good idea. 👍

**Comment by stalgiag** [comment]
Thank you @DivyamAhuja for putting together the fix. And thanks for the confirmation @limzykenneth!

**Pull request merged**
