### PR TITLE
Adding missing </code></div> in the centerY and centerZ example code

### LINKED ISSUE #5203: centerY and centerZ examples missing </code></div> closing tags
@Aloneduckling @stalgiag – just hit a hiccup while loading the latest `data.json` refs into P5LIVE.. went searching and found out – the documentation examples for both `centerY` and `centerZ` are missing their `</code></div>` tag at the end... 

The effects can be seen on website refs: [centerY](https://p5js.org/reference/#/p5.Camera/centerY) + [centerZ](https://p5js.org/reference/#/p5.Camera/centerZ)

_Originally posted by @ffd8 in https://github.com/processing/p5.js/issues/5071#issuecomment-825874694_

### PR DESCRIPTION
**Pull request by Aloneduckling**
Resolves #5203

 Changes:

Added missing </code></div> in the centerY and centerZ example code.

Thanks to @ffd8 for pointing out the mistake in the code

 Screenshots of the change:

Before:
image

After: 
image

#### PR Checklist

- [x] `npm run lint` passes
- [x] [Inline documentation] is included / updated
- [ ] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Comment by limzykenneth** [comment]
Hi @Aloneduckling, I'm seeing changes in a couple files that are seemingly unrelated to the original issue. Can you explain what those changes are and if not necessary to address the original issue can they be removed from this PR? Thanks.

**Comment by Aloneduckling** [comment]
@limzykenneth thank you, I was confused about what was happening with my PR. I will create another PR instead to force pushing. There is a lot more I need to learn about git than I thought. Sorry for creating unnecessary problems 😓

**Comment by Aloneduckling** [comment]
Closing this PR because of problems.

**Comment by limzykenneth** [comment]
@Aloneduckling No worries, we've all done something like this before. :wink:

**Pull request closed without merging**
