### PR TITLE
Fix scaling issue when using Graphics on retina

### PR DESCRIPTION
**Pull request by BenjaminHabert**
Using `image(p5.Graphics)` on a screen with `pixelDensity()`
higher than 1 results in distorted results.

This commit fixes this issue by using the technique implemented
in [`_copyHelper()`](https://github.com/processing/p5.js/blob/master/src/core/p5.Renderer2D.js#L218). I am however not sure if this commit breaks anything
else as  the rendering tests are sparse and I am only discovering
the codebase.

I do not know how to add unit tests for this part of the code; I didn't write any.

Closes: #2077

### CODE REVIEW

**Comment by Spongman** [comment]
i wonder if this shouldn't be using the same pixelDensity state instead of relying on the size of the canvas element?

**Comment by BenjaminHabert** [comment]
doing something like this ?

```javascript
var s = 1;
if (img.hasOwnProperty('pixelDensity') {
  s = img.pixelDensity();
}
```

I have no strong opinion either way but I feel that the proposed way is more robust: someone might change the size of the `img.canvas` at some point ?

**Comment by Spongman** [comment]
Yeah that's what I was thinking. If the canvas changes size, are subsequent drawing operations also going to be scaled?

**Comment by BenjaminHabert** [comment]
Nicely spotted, there is indeed an issue with resizing!

However I am a bit confused in my tests. What would be the standard way of resizing a graphics object ? I find that `graph.resizeCanvas()` changes the buffer size but does not update the exposed properties `graph.width` and `graph.height` (related to #2064 ?). Furthermore if `graph.resizeCanvas()` is called inside a `draw()` loop this raises a stackOverflowErrror. 

It appears that the only consistent way of resizing a graphics is to do (outside of draw):

```javascript
graph.resizeCanvas(200, 200);
graph.width = 200;
graph.height = 200;
```

Am I missing something ?

**Comment by BenjaminHabert** [comment]
After further investigation here are my conclusions:

- resizing a graphics may indeed cause some problems
- both of the proposed implementations solve the problem (either scaling using `canvas.width / img.width` as in `p5.Render2D.copy()` or scaling using `pixelDensity()` as suggested above)
- what actually makes it work is to resize the canvas using the following (**in that order!** as `resizeCanvas()` triggers a redraw where the properties `width` and `height` will be used):


```javascript
graph.width = 200;
graph.height = 200;
graph.resizeCanvas(graph.width, graph.height);
```

- using `.size()` (from `p5.Element`) on the graphics seems to mess up everything: it scales the main canvas (see [these lines](https://github.com/processing/p5.js/blob/master/lib/addons/p5.dom.js#L1765) in `p5.dom.js`)


Here is what I suggest:

- keep proposed fix in the pull request (`canvas.width / img.width`) to be consistent with the implementation of `.copy()`
- decide on a way to improve the resizing of graphics. Here are some options:
  1. disable the function `resizeCanvas()` for a p5.Graphics (not sure how to distinguish it from the main canvas)
  2. fix it to make sure it updates the `width` and `height` properties
  3. improve `.size()` of `p5.Element` so that  1: the hidden graphics doesn't become visible as mentioned in #2064 and 2: it doesn't resize / rescale the main canvas. This probably needs to be another issue.

Thoughts ?

**Comment by Spongman** [comment]
ok this is great! another thing that might be worth considering (i'm not sure if it's an issue with/without your fix or if it's even possible to fix) is whether or not the post-resized width/height line up with what's returned from `loadPixels()` and whether or not `get(x,y)` with contiguous integer values uniquely addresses all the pixels in the image.

**Comment by Spongman** [comment]
another thing which is loosely related: i believe currently that a browser scaling factor of 101% results in a `pixelDensity` of 2. i think this is probably overkill and it may make sense to round the pixel density in a different way.

maybe something like `pow(2, round(log(scaling)/log(2)))` ?

**Comment by BenjaminHabert** [comment]
I will try to write tests that ensure that resizing and `load_pixels()` (and maybe `get()` ?) work properly for a createGraphics() object. 

I will disregard your second point though. As I am not touching `pixelDensity` at the moment I think this is out of scope

**Comment by BenjaminHabert** [comment]
I have implemented a test that reproduce the resizing problem we were talking about. I am not sure how to implement a fix though; I could use some help.

```javascript
// in core.rendering.js
p5.prototype.resizeCanvas = function(w, h, noRedraw) {
  p5._validateParameters('resizeCanvas', arguments);
  if (this._renderer) {
    // save canvas properties
    // ...

    this._renderer.resize(w, h);
    // The previous call does indeed update the size of the inner canvas 
    // and the width and height properties of the inner _renderer.
    // however those are not the actual properties exposed by the Graphics object.
    // the following would solve it but this is probably not the right place for it: 
    this.width = w;
    this.height = h;

    // reset canvas properties
   //  ...
  }
};
```

**Comment by BenjaminHabert** [comment]
By the way here are the sizes of the different object as expected by the tests I implemented, let me know if this is what is actually intended:

- Graphics has size w, h (*this is the only thing that doesn't work*)
- graphics.canvas has size (w * density), (h * density)
- graphics.canvas.style properties are "wpx", "hpx"
- number of pixels is w * density * h * density * 4

**Comment by limzykenneth** [comment]
`Fatal error: test.titlePath is not a function` is a grunt mocha problem, not sure if they pushed to npm yet, I had that issue last time as well. https://github.com/disqus/grunt-mocha/pull/7

**Comment by kjhollen** [comment]
hi @BenjaminHabert, checking in to see what the remaining work items are here. I've run the tests and they seem to be working great, thank you! it makes sense to me that both copy and this new version of image would use pixelDensity, as an additional change.

is the resizing issue that changing the size of the p5Graphics causes a conflict of pixel densities? can you elaborate, and was this fixed by your most recent commit—and if not, is there a code sample that reproduces the issue? I'm not sure I'm completely following on the part about resizing. Once I understand, i'll decide if we can merge this as-is or if we should make additional fixes first. thank you!!

**Comment by kjhollen** [comment]
on second thought, I went ahead and merged this as-is because it also alleviates #2838, which seems like good progress. thanks!! can you open a new issue for any remaining resizing issues?

**Pull request merged**
