### PR TITLE
Update calculation.js

### PR DESCRIPTION
**Pull request by akashraj9828**
Renamed variables in dist( ) function for easy understanding

### CODE REVIEW

**Comment by limzykenneth** [comment]
For me it seems more confusing because it is fitting a 2D four arguments signature with a six argument signature, then for 3D, everything kinda breaks down...

To better illustrate, with the original implementation, only two arguments are using the wrong name (in the 2D version), while with the updated one, four arguments are using the wrong name (in the 3D version).

**Comment by akashraj9828** [comment]
I thought that mostly everyone uses dist() to calculate 2D distances and not so often 3D so I made it readable for 2D, but your point is completely fair here more variables are using wrong name. But this doesn't affects/breaks the dist( )  function so I guess it's okay.

**Comment by lmccart** [comment]
I think the clearest way to do this is actually to remove the listed arguments altogether and then access them depending on case using the arguments array, for example:
```javascript
return hypot(arguments[1]-arguments[0], arguments[3]-arguments[2]);
```

**Comment by akashraj9828** [comment]
i did as u suggested @lmccart 
now you can merge

**Comment by lmccart** [comment]
thanks!

**Pull request merged**
