### PR TITLE
Added .gitattributes to Increase compatability with Window users and line endings

### LINKED ISSUE #6207: `npm test` command not working in Windows OS
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [X] Other (specify if possible)

### p5.js version

v1.6.0

### Web browser and version

Any

### Operating System

Windows 10

### Steps to reproduce this

The command `npm test` is failing while doing the project setup.

### Steps:
1. Create a fork of the p5js repository
2. Clone the fork in the local machine
3. Execute `npm ci` 
4. Execute `npm test`

### Error after executing the last command
image

```

### PR DESCRIPTION
**Pull request by SilasVM**
Resolves #6207 

 Changes:
Added a file, .gitattributes, which forces line endings to LF with default Windows settings which would typically change them to CRLF. I've tested this on my own device and everything worked smoothly(Screenshot below) It also worked on @snwarner22's device with one error due to a test taking too long to run on his device.

I saw that another Issue and PR were closed 6 years ago, #2484 , which also could have fixed the problem. I think it’s really a compatibility issue. This `.gitattributes` file would make the library more compatible with windows and overall easier for new contributors to use. I'd like to ask that the community reconsiders adding this file so future users don’t encounter this issue and potentially get deterred from working on p5.js. 

The windows portion of my team encountered this and found another fix: `git config --global core.autocrlf false`, but this would impact the user's whole device and might be difficult for others to discover. I'd also like to note I've run this 3 times on my device all with all tests passing.

I'd also like to mention that I'm working from the main branch as that was the best way to ensure the file was working properly. I understand it's best to work from a feature branch and hope this doesn't cause any issues.

# TESTING!
Testing has been requested and would be very helpful. If anyone on Windows is open to testing all you need to do is:

1.  Run the following  : `git config --global core.autocrlf true`, in your terminal to ensure default settings are in place. 
2. Run `git clone https://github.com/SilasVM/p5.js.git`
3. Enter your new clone using `cd p5.js`
4. In your new clone run `npm ci`
5. Next run `npm test` and let us know the results in the comments

 # Screenshots of the change:
gitattributes

Screenshot of `npm test` running successfully with default windows settings: `core.autocrlf true`:
Success

@snwarner22's  Screenshot of 'npm test' running with the exception of one timeout error:
skwarner22

Article where info was pulled from: 

https://dev.to/deadlybyte/please-add-gitattributes-to-your-git-repository-1jld#gitattributes-reset

File Authors

Co-authored-by: Karl R. Wurst <karl@w-sts.com>
Co-authored-by: Stoney Jackson <dr.stoney@gmail.com>
Co-authored-by: Silas Morgan <victorsmorgan@gmail.com>

Reviewers:
Sekani Warner <wsekani@gmail.com>

#### PR Checklist

- [X] `npm run lint` passes
- [X] [Inline documentation] is included / updated
- [X] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Comment by SilasVM** [comment]
I also wanted to add a bit more context to this PR.

@aditya-shrivastavv I saw you opened #5971 which is a problem also caused by line endings. If you could check out my contribution, I think it solves your problem. I also agree with your previous issue where you said this would really help new comers as the whole windows portion of my Research team experienced problems stemming from this

Also I saw that @limzykenneth closed your issue commenting that the line endings for p5.js are to remain LF. My change force converts line endings back to LF on windows without having to install the plugin that Aditya mentioned. I believe it checks the boxes for both of you. I did take note of the .editorconfig file you mentioned and I think this could be a more effective fix as it bypasses that plugin.  I think it hits the boxes for both of you, and would appreciate your input.

**Comment by limzykenneth** [comment]
@ AryanKoundal or anyone who came across the problem in the original issue, can you have a try to see if this solves the problem for you as well?

**Comment by SilasVM** [comment]
I saw that @AryanKoundal was meant to be mentioned. I'd appreciate if you could check this out too!

**Comment by thatguyseven** [comment]
I tested this and it seems to work on my device. 
Here's a screenshot of my results:
Successful_npm_test_with_lf

**Comment by AryanKoundal** [comment]
> I saw that @AryanKoundal was meant to be mentioned. I'd appreciate if you could check this out too!

Apologies for replying late, yes it is working now. 
I am a beginner, I had a question though, is was using vs code and it allows me to change the end-of-line sequence to CRLF or LF. But I could only change the eol after importing the repo and I was getting the errors related to eols.

DP you know why wasn't that feature working?

**Comment by davepagurek** [comment]
My guess is that the vscode setting only applies to new changes you make, whereas the git changes convert everything when you clone. That's just my guess though!

Thanks for testing @thatguyseven and @AryanKoundal! I'm going to merge this in so that you're all unblocked from developing on Windows.

**Pull request merged**
