### PR TITLE
nf() handling exponential numbers and roundingOff decimal part correctly

### PR DESCRIPTION
**Pull request by aditya-shrivastavv**
Resolves [ #5710,  #5959 ]

 Changes:
1. doNf( ) now uses `.toFixed` method.
2. numbers in **exponential** form are handled correctly.
3. previously the decimal part of the numbers were **truncated** but now they are roundedoff correctly by `.toFixed`, thus resolving the issue #5959 
4. returns a string

### To test the changes

1. `right` parameter not given:

```js
doNf(12345.187, 1);
doNf(12345.187, 5);
doNf(12345.187, 6)
doNf(12345.187, 10)
```

output:

```js
12345.187
12345.187
012345.187
0000012345.187
```

2. `right` ,`left` are given: 

```js
doNf(12345.187, 1, 1);
doNf(12345.187, 5, 2);
doNf(12345.187, 6, 4);
```

output:

```js
12345.2
12345.19
012345.1870
```

3. exponential number:

```js
  let smallNum = 1.0 / 700000000.0;
  console.log("A small number: " + smallNum);
  console.log("A confusingly-formatted small number: " + nf(smallNum,1,2));
  
  let bigNum = Math.pow(5.0, 123.456);
  console.log("A big number: " + bigNum); 
  console.log("A confusingly-formatted big number: " + nf(bigNum,1,2));
```

output: 

```js
a small number: 1.4285714285714286e-9
correctly-formatted small number: 0.00 // previously: 1.42 
a big number: 1.9590289562203644e+86
correctly-formatted big number: 1.9590289562203644e+86 // previously1.95 
```

#### PR Checklist

- [x] `npm run lint` passes
- [ ] [Inline documentation] is included / updated
- [x] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Comment by aditya-shrivastavv** [comment]
@limzykenneth please review this PR

**Comment by limzykenneth** [comment]
This still have a few edge cases for example:

```js
for (let i = 0; i < 10; i++) {
    const n = pow(10, -i);
    console.log(i, n, nf(n, 4, 2));
}

```
will print

```
0 1 0001.00
1 0.1 0000.10 
2 0.01 0000.01
3 0.001 0000.00 
4 0.0001 0000.00
5 0.00001 0000.00
6 0.000001 0000.00
7 1e-7 0.00
8 1e-8 0.00
9 1e-9 0.00
```

The last 3 of which are incorrect, mostly because it is still using `toString()` at the begining of the function which will continue to preserve scientific notation and give the incorrect count for before and after decimal points numbers.

Adding some unit tests for these cases would help making sure we don't get regression in the future as well.

**Comment by aditya-shrivastavv** [comment]
the requested changes were made successfully. I need some guidance with documentation and adding unit tests

**Comment by limzykenneth** [comment]
Hi, sorry I don't have time to review this at the moment and please wait for a week or two until I manage to get some extra time to look at this closely. However the main issue this implementation currently have is that the `convertToDecimal` function is not ideal (and possibly not necessary). It is a bit too complicated and might pose performance issue as well, especially when `toFixed()` probably is enough to solve much of the problems here. Whenever possible, avoid manual parsing data and regex.

**Comment by aditya-shrivastavv** [comment]
> `convertToDecimal` function is not ideal (and possibly not necessary). It is a bit too complicated and might pose performance issue as well, especially when `toFixed()` probably is enough to solve much of the problems here. Whenever possible, avoid manual parsing data and regex.

I have simplifed `doNf()`  with the use of `padStart`. in [previous commit](https://github.com/processing/p5.js/pull/5973/commits/5c9946e99232151653ebd983fb4e65f128531e48) when I used regex I had completely eliminated the use of `e` in the number, i.e. the previous version forcefully converts exponential number into the fully expanded form. but this time `doNf()` successfully do all the operations and formatting on the number and keeps the the format of exponential number.

we can keep the one that suits the best since both of the versions work differently.

**Comment by limzykenneth** [comment]
@aditya-shrivastavv If you don't mind I may make some edits to this while I review this before I merge.

**Comment by aditya-shrivastavv** [comment]
Sure go ahead ☺️

**Comment by limzykenneth** [comment]
Looks good. Thanks!

**Pull request merged**
