### PR TITLE
new method for creating p5.Vector from polar coordinates

### PR DESCRIPTION
**Pull request by iridule**
Hey,

I thought it would be incredible useful to have a method to create vectors from polar coordinates
to be built into the p5 library.
I have added the method into the vector src file.
let me know if this is something that is worth adding or not, perhaps it could be improved...

`let myVector = p5.Vector.fromPolar(100, PI);`

best

### CODE REVIEW

**Comment by Spongman** [comment]
;-) there is already a `p5.Vector.fromAngle` method that does this. nearly...

i added a PR (#2447) earlier that adds a `length` parameter to the `fromAngle` method.

**Comment by Spongman** [comment]
;-) there is already a `p5.Vector.fromAngle` method that does this. nearly...

i added a PR (#2447) earlier that adds a `length` parameter to the `fromAngle` method.

**Comment by austince** [comment]
#2449 I believe you meant!

**Comment by Spongman** [comment]
actually, #2446 ;-)

**Comment by iridule** [comment]
oh no I realised after posting :stuck_out_tongue: ! it would be useful to have the length feature implemented... thought this works really well anyway:

`p5.Vector.fromAngle(0).setMag(10)`

**Comment by lmccart** [comment]
thanks! this should be covered with the new length feather and fromAngle

**Pull request closed without merging**
