### PR TITLE
Begin shape() work only for 3 vertices #1071

### LINKED ISSUE #1071: WEBGL mode beginShape() - only works with 3 vertices

### PR DESCRIPTION
**Pull request by parsoyaarihant**
I want to resolve #1071. I modified the code such that the user can give any number or vertices. A new array is created(NewVerticeStack) such that it stores all the triangular combination of the vertices given as input (verticeStack). Then it renders all the possible triangles and give a convex shape. It can also be extended in 3D to create convex shaped objects. Please give your opinion regarding this :)

### CODE REVIEW

**Comment by joecridge** [comment]
There’s a lot going on between lines 95 and 113. Could you add some comments explaining the function flow?

A few really nitpicky comments:
- Could we replace “vertice” with “vertex” as the singular of “vertices” in function names, e.g. `vertexStack`?
- Is there any reason why `NewVerticeStack` is capitalised?
- Is the empty `else` clause necessary?

I haven't looked much into WEBGL so this is just me parsing through the code briefly.

**Comment by parsoyaarihant** [comment]
#### Idea
Initially all the vertices are stored in the array 'this.verticeStack', my idea is to store all the possible triangles that can be formed by the vertices. lets say, we have 4 vertices, the number of possible triangles that can be formed by 4 vertices is 4 (or 4C3). The combination of triangles are stored in NewVerticeStack.
##### I implemented this idea in the lines 95-113:
I fix two adjacent vertices at a time this.verticeStack[i] and this.verticeStack[i+3] (its i+3 because the values are stored as this.verticeStack[0]=x of vertex 'a', this.verticeStack[1]=y of vertex 'a', this.verticeStack[2]=z of vertex 'a', where 'a' is some vertex) then the third vertex of the triangle is this.veticeStack[j]. For a fixed i, this.veticeStack[j] will give the third vertex of the triangle. As j varies all the possible triangles are stored in NewVerticeStack for fixed i. And by varying 'i' we can get all the possible combination of triangles. 

1. vertexStack was already predefined in the code.

2. There is no significant reason that NewVerticeStack is capitalised.

3.The else clause is not necessary. I guess I forgot to delete that.

**Comment by indefinit** [comment]
Hi guys, sorry for the delay getting to this one.  I actually fixed this a little while ago in my branch, but haven't finished the commit because of some issues on the retained mode.  Have a look here.  I think so we don't duplicate our efforts I will PR this branch and wait to merge into the p5 master until the retained mode issues are resolved:
https://github.com/indefinit/p5.js/blob/geometry-refactor/src/3d/p5.Renderer3D.Immediate.js

Note I am working from my branch called "geometry-refactor"

**Comment by indefinit** [comment]
update:  to reduce duplication of efforts I've PRed my geometry-refactor branch to the main p5 repo under a webgl-geometry-refactor branch.  If it's ok, I'll go ahead and close this PR so that we can focus on the same branch.

**Comment by parsoyaarihant** [comment]
Alright, is ok with me :+1:

**Comment by lmccart** [comment]
hi @parsoyaarihant thanks for this! please feel free to chime in on the other branch and hopefully we can incorporate your work in the future.

**Pull request closed without merging**
