### PR TITLE
Added DEG_TO_RAD and RAD_TO_DEG to constants.js

### PR DESCRIPTION
**Pull request by jay-manday**
I added DEG_TO_RAD and DEG_TO_RAD to src/core/constants.js as requested by @golanlevin in #2047. 

@Spongman suggested changing these to DEGREE_TO_RADIAN and RADIAN_TO_DEGREE. I'm open to this and would make this a little more readable/accessible though a little verbose. What do you think @limzykenneth @lmccart?

### CODE REVIEW

**Comment by lmccart** [comment]
@jay-manday looks good, but it seems like this PR still has some of the code from the double clicked PR that was merged. will you pull the latest and rebase and push again?

**Comment by jay-manday** [comment]
Sure thing, still getting the hang of git ~_~ but hopefully this is ok!

**Comment by lmccart** [comment]
hm I was still seeing some duplicate code so I just cherry picked your changes and included them here: https://github.com/processing/p5.js/commit/9e0362e12d1283197a49be9b04a4a6faf967225e

thanks!

by the way, I think the command you need to run to align your repo is something like:
`git pull git@github.com:processing/p5.js.git master`

**Comment by jay-manday** [comment]
no problemo! Ty again for the help n_n

**Pull request closed without merging**
