### PR TITLE
Edit docs for image

### PR DESCRIPTION
**Pull request by nickmcintyre**
Addresses #6389

 Changes:
I edited the inline documentation for the `createImage()`, `saveCanvas()`, and `saveFrames()` functions to bring them more in line with the style guide.

@davepagurek @dkessner @MsQCompSci @limzykenneth @Qianqianye @stalgiag @cgusb @photon-niko @KleoP I'd love to incorporate any feedback you may have!

#### PR Checklist

- [x] `npm run lint` passes
- [x] [Inline documentation] is included / updated

### CODE REVIEW

**Comment by MsQCompSci** [comment]
Edits:
Just for `createImage()`
1. "pixels" link has a dot (.) before it
2. Paragraph edit (added the word "be"): Before accessing the pixels of an image, the data must be loaded with the [loadPixels()](https://p5js.org/reference/#/p5.Image/loadPixels) function. After the array data has been modified, the [updatePixels()](https://p5js.org/reference/#/p5.Image/updatePixels) function must be run to update the changes.

**Comment by nickmcintyre** [comment]
@dkessner @MsQCompSci here's a [staging version](https://computiful.dev/sod-image/reference/#group-Image) of the docs for this pull request. Don't wander too far off the Reference pages or stuff will break–patched just enough of the site to get this working.

Please let me know if you'd like to see further revisions or if we should request a merge.

**Comment by dkessner** [comment]
Hi Nick, the text looks very clear to me.  I have one suggestion for the Reference page Image section.  

The most commonly used functions are probably loadImage() and image(), so I think it would be helpful to put these two in the left column (the high-level interface functions).   createImage() will be used before pixel manipulation, so perhaps move it to the right.

**Comment by nickmcintyre** [comment]
Thanks, and thanks for the suggestions @dkessner! I like your idea of arranging based on usage. We can bring this up with the website design team once they get started.

**Comment by nickmcintyre** [comment]
@Qianqianye @davepagurek @limzykenneth if this pull request looks good to you, please go ahead merge.

**Review by davepagurek — APPROVED** [review]

**Pull request merged**
